### PR TITLE
Fixes an issue with opentsdb and a double space

### LINKED ISSUE #8244: OpentsdbWriter empty tag
## Describe the bug

When ingesting opentsdb metrics in victoriametrics, it errors out due to missing tag value for "".

The issue is Opentsdb using spaces as delimiters and icinga2 adds a double space between the value and the first tag.
This causes victoriametrics to find an empty tag.

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. Deploy a victoriametrics node with vmagent as the ingest agent.
2. Setup Icinga2 OpentsdbWriter to send metrics to the vmagent
3. View VMAgent logs for error
### example log extract
_victoriametrics_vmagent.1.qzlltcw2mivu@<dockernode>    | 2020-09-17T22:32:12.216Z	error	VictoriaMetrics/lib/protoparser/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "put icinga.service.procs.procs 1600381937 137  host=<host>": cannot unmarshal tags in "icinga.service.procs.procs 1600381937 137  host=<host>": missing tag value for ""_

## Expected behavior

Data to be ingested into victoriametrics.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): v2.12.0
* Operating System and version: CentOS 7 
* Enabled features (`icinga2 feature list`): api checker debuglog mainlog notification opentsdb
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
[2020-09-18 08:48:55 +1000] information/cli: Icinga application loader (version: v2.12.0)
[2020-09-18 08:48:55 +1000] information/cli: Loading configuration file(s).
[2020-09-18 08:48:55 +1000] information/ConfigItem: Committing config item(s).
[2020-09-18 08:48:55 +1000] information/ApiListener: My API identity: <host>
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 OpenTsdbWriter.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 User.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 UserGroup.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 3 Zones.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 11 Services.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 Host.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 12 Notifications.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 2 HostGroups.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 Endpoint.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 2 FileLoggers.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 ApiUser.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 236 CheckCommands.
[2020-09-18 08:48:55 +1000] information/ConfigItem: Instantiated 1 ApiListener.
[2020-09-18 08:48:55 +1000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-09-18 08:48:55 +1000] information/cli: Finished validating the configuration file(s).

## Additional context
The bug can be seen in the following code snippet. At Line 370 it prepends a space before each tag. Then on Line 379 it places a space between the value and the list of tags. This causes a double space between the value and first tag.

https://github.com/Icinga/icinga2/blob/2dfe777f48baac7e6ced4dd05e274366b51df7ac/lib/perfdata/opentsdbwriter.cpp#L369-L379

### PR DESCRIPTION
**Pull request by Ragnra**
There is a double space between the value and the tags causing an error with missing tag when ingesting the data

fixes #8244

### CODE REVIEW

File: lib/perfdata/opentsdbwriter.cpp [hunk 1]
```diff
@@ -376,7 +376,7 @@ void OpenTsdbWriter::SendMetric(const Checkable::Ptr& checkable, const String& m
 	 * put <metric> <timestamp> <value> <tagk1=tagv1[ tagk2=tagv2 ...tagkN=tagvN]>
 	 * "tags" must include at least one tag, we use "host=HOSTNAME"
 	 */
-	msgbuf << "put " << metric << " " << static_cast<long>(ts) << " " << Convert::ToString(value) << " " << tags_string;
+        msgbuf << "put " << metric << " " << static_cast<long>(ts) << " " << Convert::ToString(value) << tags_string;
```
Comment (Al2Klimov) [inline lib/perfdata/opentsdbwriter.cpp:379]: You have changed the tab to spaces. Please undo this.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Don't forget to use `git commit --amend` and `git push -f`.

File: lib/perfdata/opentsdbwriter.cpp (hunk 1 above)
Comment (Ragnra) [reply lib/perfdata/opentsdbwriter.cpp]: mm strange, not sure how that occurred, however this has been fixed

**Review by Al2Klimov — APPROVED** [review]
A non-empty `tags_string` is always prefixed w/ a space, so the extra space is not needed and removing it doesn't break anything.

**Review by julianbrost — APPROVED** [review]
