### PR TITLE
IcingaDB::SendCustomVarsChanged(): don't delete custom vars of not synced types

### LINKED ISSUE #9478: No object type for redis key icinga:dependency:customvar found
## Describe the bug

Icingadb daemon is crashing on start

```
2022-08-09T10:43:24.961-0400    INFO    icingadb        Starting Icinga DB
2022-08-09T10:43:24.961-0400    INFO    icingadb        Connecting to database at 'localhost:3306'
2022-08-09T10:43:24.967-0400    INFO    icingadb        Connecting to Redis at 'localhost:6380'
2022-08-09T10:43:24.968-0400    INFO    icingadb        Starting history sync
2022-08-09T10:43:25.853-0400    INFO    heartbeat       Received Icinga heartbeat       {"environment": "612491695a81d0cfb21c30d8e08ef32d631757e6"}
2022-08-09T10:43:25.862-0400    INFO    icingadb        Taking over
2022-08-09T10:43:25.869-0400    INFO    icingadb        Starting config sync
2022-08-09T10:43:25.869-0400    INFO    icingadb        Starting initial state sync
2022-08-09T10:43:25.869-0400    INFO    icingadb        Starting overdue sync
2022-08-09T10:43:26.182-0400    INFO    config-sync     Updating 8802 items of type host state
2022-08-09T10:43:26.389-0400    INFO    config-sync     Updating 21610 items of type service state
2022-08-09T10:43:27.579-0400    INFO    config-sync     Finished initial state sync in 1.710440468s
2022-08-09T10:43:27.579-0400    INFO    icingadb        Starting state runtime updates sync
2022-08-09T10:43:28.057-0400    INFO    config-sync     Inserting 981 items of type host customvar
2022-08-09T10:43:28.057-0400    INFO    config-sync     Deleting 980 items of type host customvar
2022-08-09T10:43:28.105-0400    INFO    icingadb        Starting history retention
2022-08-09T10:43:28.105-0400    INFO    icingadb        Starting config runtime updates sync
2022-08-09T10:43:28.105-0400    INFO    config-sync     Finished config sync in 2.236165018s
2022-08-09T10:43:28.122-0400    FATAL   icingadb        no object type for redis key icinga:dependency:customvar found
github.com/icinga/icingadb/pkg/icingadb.(*RuntimeUpdates).xRead.func1
        github.com/icinga/icingadb/pkg/icingadb/runtime_updates.go:262
golang.org/x/sync/errgroup.(*Group).Go.func1
        golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
        runtime/asm_amd64.s:1571

```

## To Reproduce

Apply custom vars to dependencies is what I'm guessing is crashing it

## Expected behavior

It should not crash and should accept custom vars in dependencies

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: v1.0.0
* Icinga 2 version: r2.13.4-1
* Operating System and version: Red Hat Enterprise Linux Server release 7.9 (Maipo)

## Additional context

An example of a decency we add via the API:

```
[root@icinga01 dependencies]# more newres-3-314-ap1\!newres-245-sw1.conf
object Dependency "newres-245-sw1" {
        child_host_name = "newres-3-314-ap1"
        parent_host_name = "newres-245-sw1"
        vars = {
                database_run = "Thu Jul 28 00:04:00 2022"
                database_source = "cmdb"
                device_type = "aruba_ap"
        }
        version = 1658982689.918957
        zone = "icinga01"
}
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
not to surprise (and crash) the Icinga DB daemon with unknown types.

fixes #9478

## Before

A such request

```
curl -ksSu root:123456 -H 'Accept: application/json' -X POST -d '{"attrs":{"vars.lollcat":"mewww"}}' https://127.0.0.1:5665/v1/objects/dependencies/'alexandersmbp2.int.netways.de!disk!p5d';echo
```

crashes Icinga DB immediately. (`pkg/icingadb/runtime_updates.go:262`)

## After

The message causing the crash isn't even written to Redis:

```
redis.XMessage{ID:"1660122773801-0", Values:map[string]interface {}{"id":"2943ebbf60473950c9a9ea41c4a08069d9e0e461", "redis_key":"icinga:dependency:customvar", "runtime_type":"delete"}}
```

Btw. _known_ types still work:

```
1660124916.091013 [0 127.0.0.1:58106] "XADD" "icinga:runtime" "MAXLEN" "~" "1000000" "*" "redis_key" "icinga:host:customvar" "id" "54b8c2d8074568bc08baac05362f66e884193021" "runtime_type" "delete"
```

### CODE REVIEW

File: lib/icingadb/icingadb.hpp [hunk 1]
```diff
@@ -232,6 +233,8 @@ class IcingaDB : public ObjectImpl<IcingaDB>
 	// initialization, the value is read-only and can be accessed without further synchronization.
 	static String m_EnvironmentId;
 	static std::mutex m_EnvironmentIdInitMutex;
+
+	static std::unordered_set<Type*> m_IndexedTypes;
```
Comment (julianbrost) [inline lib/icingadb/icingadb.hpp:237]: Why did you call it "indexed"?

**Review by julianbrost — CHANGES_REQUESTED** [review]
Deleting a dependency via the API still emits Redis messages:
```
1660128763.238197 [0 172.26.0.4:34452] "HDEL" "icinga:dependency" "b09b84fd174104b6181a58038f1d007cc10d4a07"
1660128763.238599 [0 172.26.0.4:34452] "HDEL" "icinga:checksum:dependency" "b09b84fd174104b6181a58038f1d007cc10d4a07"
1660128763.238658 [0 172.26.0.4:34452] "XADD" "icinga:runtime" "MAXLEN" "~" "1000000" "*" "redis_key" "icinga:dependency" "id" "b09b84fd174104b6181a58038f1d007cc10d4a07" "runtime_type" "delete"
```
which subsequently crash Icinga DB:
```
2022-08-10T10:51:45.714Z	FATAL	icingadb	no object type for redis key icinga:dependency found
github.com/icinga/icingadb/pkg/icingadb.(*RuntimeUpdates).xRead.func1
	github.com/icinga/icingadb/pkg/icingadb/runtime_updates.go:262
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
	runtime/asm_amd64.s:1571
```

File: lib/icingadb/icingadb.hpp (hunk 1 above)
Comment (Al2Klimov) [reply lib/icingadb/icingadb.hpp:237]: GetTypes() produces a vector, lookup: O(n). In contrast that is a hash table, lookup: O(1).

Comment (julianbrost) [reply lib/icingadb/icingadb.hpp:237]: Why can't this be a `std::unordered_set<Type::Ptr>` though? Compiled fine in my test, is this something about Boost version compatibility?

Comment (Al2Klimov) [reply lib/icingadb/icingadb.hpp:237]: It simply doesn’t have to ensure even that the pointers are valid, it's lookup-only.

Comment (julianbrost) [reply lib/icingadb/icingadb.hpp:237]: We usually just use `T::Ptr` instead of discussing where just `T*` would also be fine, so I don't see why this place should be special. Yes, it's fine here as the `Type` objects in here should be kept alive forever by some other reference, but in general, it might happen that some object in the set is freed, then a new object is allocated at the same address and then it would be in the set when it shouldn't.

Comment (julianbrost) [reply lib/icingadb/icingadb.hpp:237]: Just both instances of `std::unordered_set<Type*>`. But should probably also remove a few `.get()`, otherwise it would pointlessly increment and decrement reference counts.

Comment (Al2Klimov) [reply lib/icingadb/icingadb.hpp:237]: Boost version?

Comment (julianbrost) [reply lib/icingadb/icingadb.hpp:237]: 1.79.0

Comment (Al2Klimov) [reply lib/icingadb/icingadb.hpp:237]: Please try 1.66.

Comment (julianbrost) [reply lib/icingadb/icingadb.hpp:237]: I don't have that version lying around locally, so please let the CI do its job.

Comment (julianbrost) [reply lib/icingadb/icingadb.hpp]: Well, that looks like a nope to me:
> error: static assertion failed: hash function must be invocable with an argument of key type

Comment (Al2Klimov) [reply lib/icingadb/icingadb.hpp]: Shall I undo?

**Review by julianbrost — APPROVED** [review]
