### PR TITLE
Worker process doesn't let parallel API package stage updates to complete when terminated

### LINKED ISSUE #7898: API package calls do not complete while reload being called
## Describe the bug

```yaml
This is for master 2.10.5 so It could have been fixed/ redone in 2.11.x if so just let me know, sorry for mess then.
```

I have multiple sources talking with Icinga2 master. They send different package config updates.
However, it seems that reloads called break are another updates. 

- Here we see 2 sources talking to API, 1 manages Package A, second Package B
- A is first and it updates package stage, effectively Icinga automatically reloads. 
- After the reload is called. Package B is being updated. But right after icinga control is passed to another instance.
- The full reload with sync takes about 15 seconds. While App is responsive in that time. 
- In this time it returns 404 Path not found for status of Stage Package B 
- Eventually even after full reload or restart status file for B is missing status, and stage is not loaded.
- We later see that Package A but this is not important for B, it is show here just to show that it triggers reload as well

```bash
[11:02:03 +0000] HttpServerConnection: Request: POST /v1/config/stages/PACKAGE_A
[11:02:05 +0000] Application: Got reload command: Starting new instance.
[11:02:06 +0000] HttpServerConnection: Request: POST /v1/config/stages/PACKAGE_B
[11:02:07 +0000] Application: Reload requested, letting new process take over.
# Starting reload
[11:02:11 +0000] HttpServerConnection: Request: GET /v1/config/files/PACKAGE_B/PACKAGE_B_STAGE/status
[11:02:14 +0000] HttpServerConnection: Request: GET /v1/config/files/PACKAGE_B/PACKAGE_B_STAGE/status
[11:02:17 +0000] HttpServerConnection: Request: GET /v1/config/files/PACKAGE_B/PACKAGE_B_STAGE/status
[11:02:20 +0000] HttpServerConnection: Request: DELETE /v1/config/packages/PACKAGE_A
[11:02:20 +0000] HttpServerConnection: Request: GET /v1/config/files/PACKAGE_B/PACKAGE_B_STAGE/status
# Finished reload
[11:02:21 +0000] Application: Got reload command: Starting new instance.
[11:02:23 +0000] HttpServerConnection: Request: GET /v1/config/files/PACKAGE_B/PACKAGE_B_STAGE/status
[11:02:23 +0000] Application: Reload requested, letting new process take over.
```

What we see - requests for Package A and B collide.
Having multiple sources talking to API, interfere and break are another flows.

The calls between 
```bash
Application: Got reload command: Starting new instance.
#AND
Application: Reload requested, letting new process take over.
```
Simply do not pass successfully.

What is in the files on machine?  There is actually *stage* config with all data `EXCEPT` status and startup file. The *package* itself is missing active stage file.
Restart and reloads do not fix it.

## Expected behavior

The stage update to be completed successfully 
or auto-recovery after next reload/restart.

Instead I need to workaround it with retrys hoping that eventually 1 reload made by icinga will be called by my request, not my other sources

## Your Environment
```bash
icinga-rpm-release.noarch        7-2.el7.centos                  installed
icinga2.x86_64                   2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-bin.x86_64               2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-common.x86_64            2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-ido-mysql.x86_64         2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-selinux.x86_64           2.10.5-1.el7.icinga             @icinga-stable-release
```

```bash
The Icinga 2 network monitoring daemon (version: r2.10.5-1)
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.27.2.el7.x86_64
  Architecture: x86_64
```

### PR DESCRIPTION
**Pull request by yhabteab**
When the second request isn't finished processing till the new worker process is started and its configs are validated, the old worker is terminated immediately after the new worker becomes ready. When the worker process is terminated, all the worker threads of the `Process` class that are responsible for processing such requests are also destroyed. Thus, the second API request remains incomplete and produces a package stage without `startup` logs and `status` file.

**Changes:**

**Concurrent package updates are strictly prohibited.**

## To Reproduce

- First create two different config packages
  - `curl -k -s -S -i -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/config/packages/cmdb?pretty=1'`
  - `curl -k -s -S -i -u root:icinga -H 'Accept: application/json'  -X POST 'https://localhost:5665/v1/config/packages/test?pretty=1'`
- Next just update these packages asynchronously. You need also to specify different configuration each time so that the reload signal can be triggered internally. You also need to post the requests in a bit order (not strictly simultaneous) so that you can reproduce the issue.

```bash
curl -k -s -S -i -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/config/stages/cmdb'  -d '{ "files": { "conf.d/test.conf": "object Host \"cmdb-host\" { check_command = \"dummy\" }" }, "pretty": true }'
curl -k -s -S -i -u root:icinga -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/config/stages/test'  -d '{ "files": { "conf.d/test.conf": "object Host \"test-host\" { check_command = \"dummy\" }" }, "pretty": true }'
```

fixes #7898

### CODE REVIEW

**Comment by yhabteab** [comment]
What do you think of this kind of treatment?

File: lib/cli/daemoncommand.cpp [hunk 1]
```diff
@@ -432,6 +432,21 @@ static void WorkerSignalHandler(int num, siginfo_t *info, void*)
...
+				Application::OnShutdownRequested();
+
+				/*
+				 * Let the worker process flow till all outstanding "Process" tasks are finished to
+				 * prevent the Process worker threads from being destroyed prematurely e.g. before the
+				 * ongoing package stage updates are completed. Otherwise, we may end up with some
+				 * corrupted stages without startup logs and status file.
+				 */
+				while(Process::GetPendingTasks().load() != 0) {
+				}
```
Comment (Al2Klimov) [inline lib/cli/daemoncommand.cpp:448]: You can't block in a signal handler.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]

File: lib/cli/daemoncommand.cpp (hunk 1 above)
Comment (yhabteab) [reply lib/cli/daemoncommand.cpp:448]: Where would be the appropriate place to block? Inside the `Application::RunEventLoop()`?

**Comment by yhabteab** [comment]
> Fail concurrent requests for modification altogether

You want me to forbid concurrent stage updates that are completely independent from each other?

**Comment by Al2Klimov** [comment]
Tom and I also do. (Icinga/icingaweb2-module-director#2412)

File: lib/cli/daemoncommand.cpp (hunk 1 above)
Comment (yhabteab) [reply lib/cli/daemoncommand.cpp:448]: > Hanging plugins would block shutdown.

👇 
"Though it is up to the caller (which calls the `Process::Run()` member method) to decide which operation is critical and which not."

If you as a programmer decide to mark such plugin checks as important, then you obviously brought it on yourself!

File: lib/remote/configstageshandler.hpp [hunk 2]
```diff
@@ -47,6 +47,7 @@ class ConfigStagesHandler final : public HttpHandler
 		const Dictionary::Ptr& params
 	);
 
+	static bool m_RunningPackageUpdates;
```
Comment (julianbrost) [inline lib/remote/configstageshandler.hpp:50]: Is this variable guarded by any lock? (Or better directly use a mutex. Hint: have a look at `std::unique_lock` and `std::try_to_lock`)

File: lib/remote/configstageshandler.cpp [hunk 3]
```diff
@@ -128,19 +136,18 @@ void ConfigStagesHandler::HandlePost(
 		if (reload && !activate)
 			BOOST_THROW_EXCEPTION(std::invalid_argument("Parameter 'reload' must be false when 'activate' is false."));
 
-		std::unique_lock<std::mutex> lock(ConfigPackageUtility::GetStaticPackageMutex());
```
Comment (julianbrost) [inline lib/remote/configstageshandler.cpp:131]: This mutex is used in other places too, have you checked that it's safe to remove here?

File: lib/remote/configstageshandler.cpp [hunk 4]
```diff
@@ -128,19 +136,18 @@ void ConfigStagesHandler::HandlePost(
...
-
 		stageName = ConfigPackageUtility::CreateStage(packageName, files);
 
 		/* validate the config. on success, activate stage and reload */
-		ConfigPackageUtility::AsyncTryActivateStage(packageName, stageName, activate, reload);
+		ConfigPackageUtility::TryActivateStage(packageName, stageName, activate, reload);
```
Comment (julianbrost) [inline lib/remote/configstageshandler.cpp:142]: So the HTTP request uploading the new configuration will now wait for the complete config validation to complete? I don't think this is a good idea as this may cause timeouts in existing clients as this could take quite long.

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/remote/configstageshandler.cpp (hunk 4 above)
Comment (yhabteab) [reply lib/remote/configstageshandler.cpp:142]: Oh 🐘 , I hadn't thought of that.

File: lib/remote/configstageshandler.cpp (hunk 3 above)
Comment (yhabteab) [reply lib/remote/configstageshandler.cpp:131]: > This mutex is used in other places too

It is also allowed concurrent access everywhere it is still used.

> have you checked that it's safe to remove here?

There is no concurrent access here anymore, so this lock is not needed.

File: lib/remote/configstageshandler.cpp [hunk 5]
```diff
@@ -97,6 +100,11 @@ void ConfigStagesHandler::HandlePost(
 {
 	namespace http = boost::beast::http;
 
+	if (m_RunningPackageUpdates) {
+		return HttpUtility::SendJsonError(response, params, 409,
+			"Conflicting request, there is already an ongoing package update in progress. Please try it again later.");
+	}
```
Comment (julianbrost) [inline lib/remote/configstageshandler.cpp:106]: This still isn't synchronized properly. Two requests could still pass this test at the same time.

File: lib/remote/configstageshandler.cpp (hunk 3 above)
Comment (julianbrost) [reply lib/remote/configstageshandler.cpp:131]: There are other places than this one that also lock on `ConfigPackageUtility::GetStaticPackageMutex()`:
* `ConfigObjectUtility::CreateStorage()`
* `ConfigPackagesHandler::HandleGet(...)`
* `ConfigPackagesHandler::HandlePost(...)`
* `ConfigPackageUtility::TryActivateStageCallback(...)`

This PR (with fixed synchronization of `m_RunningPackageUpdates` will only prevent this function from running concurrently with the last one in that list. The lock could still be required for one of the other three functions running concurrently.

(I'm not implying that there is a problem with removing the lock here, but one has to carefully check if it's safe to do so.)

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/remote/configstageshandler.cpp (hunk 5 above)
Comment (yhabteab) [reply lib/remote/configstageshandler.cpp:106]: I was thinking that since all we do here is just reading (that is, not that one thread reads and while another writes), we don't need a mutex.

Comment (julianbrost) [reply lib/remote/configstageshandler.cpp:106]: The main goal here isn't protecting `m_RunningPackageUpdates` but rather ensuring that no two requests are allowed to update config packages at the same time (that's also why I suggested https://github.com/Icinga/icinga2/pull/9267#discussion_r818876906, i.e. directly use a mutex instead of a boolean that needs to be protected by a mutex).

With the current code, two threads may do the `if (m_RunningPackageUpdates)` check at the same time and both conclude that it's safe to continue when it isn't, only later setting that marker flag.

Apart from that, the mutex also synchronizes between threads in the sense that it ensures that changes by one thread become visible in the other one, so without it, another thread would even be allowed to use some cached value. (You can have a look at [cppreference](https://en.cppreference.com/w/cpp/atomic/memory_order) but that page isn't an easy read.)

File: lib/remote/configstageshandler.cpp [hunk 6]
```diff
@@ -97,6 +100,11 @@ void ConfigStagesHandler::HandlePost(
 {
 	namespace http = boost::beast::http;
 
+	if (m_RunningPackageUpdates) {
+		return HttpUtility::SendJsonError(response, params, 409,
```
Comment (Al2Klimov) [inline lib/remote/configstageshandler.cpp:104]: What about 423?

File: lib/remote/configstageshandler.cpp (hunk 5 above)
Comment (Al2Klimov) [reply lib/remote/configstageshandler.cpp:106]: What about an atomic variable?

Comment (julianbrost) [reply lib/remote/configstageshandler.cpp:106]: Would also work. Using a mutex has the advantage that you can use `std::unique_lock` which prevents forgetting to unlock on some code paths.

I haven't tried, but that situation might already exist in the code, I think these assignments can throw if the value isn't convertible to `bool` (via `double` I guess): https://github.com/Icinga/icinga2/blob/cecfca5592d8711d38b3b8b42fce77e299bf3462/lib/remote/configstageshandler.cpp#L120-L128

Comment (yhabteab) [reply lib/remote/configstageshandler.cpp:106]: > (that's also why I suggested [#9267 (comment)](https://github.com/Icinga/icinga2/pull/9267#discussion_r818876906), i.e. directly use a mutex instead of a boolean that needs to be protected by a mutex).

How do you check a mutex directly to see if it is locked/owned by this thread? When you unlock an already unlocked mutex is undefined behavior (I've read this before).

Comment (Al2Klimov) [reply lib/remote/configstageshandler.cpp:106]: Look up recursive mutexes.

File: lib/remote/configstageshandler.hpp (hunk 2 above)
Comment (Al2Klimov) [reply lib/remote/configstageshandler.hpp:55]: > Or better directly use a mutex.

"directly"?

File: lib/remote/configstageshandler.cpp (hunk 5 above)
Comment (julianbrost) [reply lib/remote/configstageshandler.cpp:106]: [You don't](https://en.cppreference.com/w/cpp/thread/mutex/unlock):
> The mutex must be locked by the current thread of execution, otherwise, the behavior is undefined.

If unlocking in another thread is required, just keeping a single mutex locked isn't an option. In this case, `std::atomic<bool>` is probably the best option.

Comment (Al2Klimov) [reply lib/remote/configstageshandler.cpp:106]: Yep.

File: lib/remote/configstageshandler.hpp (hunk 2 above)
Comment (julianbrost) [reply lib/remote/configstageshandler.hpp:55]: Use it as if it was a `std::atomic<bool>` that can conveniently be used with `std::unique_lock` (but not an option anyways if unlocking from another thread is required).

File: lib/remote/configstageshandler.cpp [hunk 7]
```diff
@@ -97,6 +99,11 @@ void ConfigStagesHandler::HandlePost(
 {
 	namespace http = boost::beast::http;
 
+	if (m_RunningPackageUpdates.load()) {
```
Comment (julianbrost) [inline lib/remote/configstageshandler.cpp:102]: > With the current code, two threads may do the `if (m_RunningPackageUpdates)` check at the same time and both conclude that it's safe to continue when it isn't, only later setting that marker flag.

The check looks different now, but that problem is still present.

File: lib/remote/configstageshandler.cpp (hunk 6 above)
Comment (julianbrost) [reply lib/remote/configstageshandler.cpp:103]: Yes, 423 Locked sounds more appropriate to signal "please try again later", 409 Conflict could also be interpreted as "the config you sent introduced a conflict, fix it and try again".

File: lib/remote/configstageshandler.hpp [hunk 8]
```diff
@@ -24,6 +24,8 @@ class ConfigStagesHandler final : public HttpHandler
 		HttpServerConnection& server
 	) override;
 
+	static void ReSetRunningPackageUpdates();
```
Comment (julianbrost) [inline lib/remote/configstageshandler.hpp:27]: Feels strange to have a function only for this operation and not the others. I'd go for no functions since these are rather simple single statements anyways. (But if you want to keep the functions, I think the capitalization looks strange and it should just be "Reset".)

File: lib/remote/configpackageutility.cpp [hunk 9]
```diff
@@ -196,6 +197,12 @@ void ConfigPackageUtility::TryActivateStageCallback(const ProcessResult& pr, con
 			<< "Config validation failed for package '"
 			<< packageName << "' and stage '" << stageName << "'.";
 	}
+
+	// Reset the stages' handler flag only when the config validation wasn't successful
+	// or the Icinga2 worker process doesn't need to be reloaded
+	if (! reload || pr.ExitStatus != 0) {
```
Comment (julianbrost) [inline lib/remote/configpackageutility.cpp:203]: Typically, when negating conditions, we don't put a space in there.

**Review by julianbrost — CHANGES_REQUESTED** [review]
In addition to the inline comments, please also make sure to test https://github.com/Icinga/icinga2/pull/9267#discussion_r820585319 (second paragraph).

File: lib/remote/configstageshandler.hpp (hunk 8 above)
Comment (yhabteab) [reply lib/remote/configstageshandler.hpp:27]: Just assumed that the other classes shouldn't have the ability to set this member variable to `true` but only reset it.

Comment (julianbrost) [reply lib/remote/configstageshandler.hpp:27]: Ok, things are split across classes, so that might be a fair point. I haven't looked too much at the context so far to be honest.

File: lib/remote/configstageshandler.cpp (hunk 5 above)
Comment (yhabteab) [reply lib/remote/configstageshandler.cpp]: > I haven't tried, but that situation might already exist in the code, I think these assignments can throw if the value isn't convertible to `bool` (via `double` I guess):

```
[2022-03-07 15:30:32 +0100] warning/HttpServerConnection: Error while processing HTTP request: Can't convert 'false' to a floating point number.
```

After this, `m_RunningPackageUpdates` stays true forever!

Comment (Al2Klimov) [reply lib/remote/configstageshandler.cpp]: To ensure proper flag reset, pack it into a `Shared<Defer>` and pass the (intrusive) pointer along with the actual deploy operation.

File: lib/remote/configpackageutility.cpp [hunk 10]
```diff
@@ -196,9 +197,15 @@ void ConfigPackageUtility::TryActivateStageCallback(const ProcessResult& pr, con
 			<< "Config validation failed for package '"
 			<< packageName << "' and stage '" << stageName << "'.";
 	}
+
+	// Don't let the deferred callback go out of scope when the config validation was successful
+	// and the Icinga2 worker process is going to be reloaded
+	if (reload && pr.ExitStatus == 0) {
```
Comment (julianbrost) [inline lib/remote/configpackageutility.cpp:203]: Given that this is now the same condition as where `Application::RequestRestart();` is called, please move it there.

File: lib/remote/configpackageutility.cpp [hunk 11]
```diff
@@ -196,9 +197,15 @@ void ConfigPackageUtility::TryActivateStageCallback(const ProcessResult& pr, con
...
+		ConfigStagesHandler::m_KeepRunning = resetPackageUpdates;
```
Comment (julianbrost) [inline lib/remote/configpackageutility.cpp:204]: Having this member just to prevent the destruction of the `Defer` feels a bit hacky. What about adding `Defer::Cancel()` which resets the captured function so that if it was called,  `~Defer()` just does nothing?

File: lib/remote/configpackageutility.cpp [hunk 12]
```diff
@@ -196,9 +197,15 @@ void ConfigPackageUtility::TryActivateStageCallback(const ProcessResult& pr, con
 			<< "Config validation failed for package '"
 			<< packageName << "' and stage '" << stageName << "'.";
 	}
+
+	// Don't let the deferred callback go out of scope when the config validation was successful
+	// and the Icinga2 worker process is going to be reloaded
```
Comment (julianbrost) [inline lib/remote/configpackageutility.cpp:202]: I think this comment would be more helpful if it also said why that's done.

File: lib/remote/configstageshandler.cpp [hunk 13]
```diff
@@ -97,6 +100,13 @@ void ConfigStagesHandler::HandlePost(
 {
 	namespace http = boost::beast::http;
 
+	if (m_RunningPackageUpdates.exchange(true)) {
+		return HttpUtility::SendJsonError(response, params, 423,
+			"Conflicting request, there is already an ongoing package update in progress. Please try it again later.");
+	}
+
+	auto resetPackageUpdates (Shared<Defer>::Make([]() { ConfigStagesHandler::m_RunningPackageUpdates.store(false); }));
```
Comment (julianbrost) [inline lib/remote/configstageshandler.cpp:108]: This should be done as late as possible, in particular after all the request validation that follows. These checks can be done safely before that lock is obtained.

**Review by julianbrost — CHANGES_REQUESTED** [review]
Where you add that new `Defer` parameter, lines are getting quite long, so I'd say it's time to add some line breaks.

File: lib/remote/configpackageutility.cpp (hunk 10 above)
Comment (yhabteab) [reply lib/remote/configpackageutility.cpp:203]: Not at all! The `activate` param is also required to be `true`, so that the application restart can be triggered.

Comment (julianbrost) [reply lib/remote/configpackageutility.cpp:203]: I'd expect that further requests are only prevented if the node actually reloads immediately. Shouldn't this be the case if and only if `Application::RequestRestart();` is called above?

File: lib/remote/configpackageutility.cpp [hunk 14]
```diff
@@ -5,6 +5,7 @@
 #include "base/application.hpp"
 #include "base/exception.hpp"
 #include "base/utility.hpp"
+#include "configstageshandler.hpp"
```
Comment (julianbrost) [inline lib/remote/configpackageutility.cpp:8]: Shouldn't be needed here anymore as the flag is no longer accessed directly.

File: lib/remote/configstageshandler.cpp [hunk 15]
```diff
@@ -107,6 +109,13 @@ void ConfigStagesHandler::HandlePost(
 	if (!ConfigPackageUtility::ValidatePackageName(packageName))
 		return HttpUtility::SendJsonError(response, params, 400, "Invalid package name '" + packageName + "'.");
 
+	if (m_RunningPackageUpdates.exchange(true)) {
+		return HttpUtility::SendJsonError(response, params, 423,
+			"Conflicting request, there is already an ongoing package update in progress. Please try it again later.");
+	}
+
+	auto resetPackageUpdates (Shared<Defer>::Make([]() { ConfigStagesHandler::m_RunningPackageUpdates.store(false); }));
```
Comment (julianbrost) [inline lib/remote/configstageshandler.cpp:117]: I think this can be moved down even further, all the way to after https://github.com/Icinga/icinga2/blob/129b1ddc88f43b469ec9660037108ddd56a145d7/lib/remote/configstageshandler.cpp#L137-L138

Everything up to there are just fetching data from the request or checks of that data, so if any of that fails the request, there's no need to obtain the lock at all.

**Review by julianbrost — CHANGES_REQUESTED** [review]

**Review by julianbrost — COMMENTED** [review]
@yhabteab Is this intentionally still in draft state? I don't have anything more code-wise so far. I'll still do some testing but preferably after you say you don't plan any other changes to the code.

File: lib/remote/configpackageutility.cpp [hunk 16]
```diff
@@ -198,7 +210,8 @@ void ConfigPackageUtility::TryActivateStageCallback(const ProcessResult& pr, con
 	}
 }
 
-void ConfigPackageUtility::AsyncTryActivateStage(const String& packageName, const String& stageName, bool activate, bool reload)
+void ConfigPackageUtility::AsyncTryActivateStage(const String& packageName, const String& stageName, bool activate, bool reload,
+	Shared<Defer>::Ptr resetPackageUpdates)
```
Comment (Al2Klimov) [inline lib/remote/configpackageutility.cpp:214]: Can (and therefore should) be a const ref. Btw.: explain in your own words why.

File: lib/remote/configpackageutility.hpp [hunk 17]
```diff
@@ -37,7 +39,8 @@ class ConfigPackageUtility
 	static void SetActiveStage(const String& packageName, const String& stageName);
 	static void SetActiveStageToFile(const String& packageName, const String& stageName);
 	static void ActivateStage(const String& packageName, const String& stageName);
-	static void AsyncTryActivateStage(const String& packageName, const String& stageName, bool activate, bool reload);
+	static void AsyncTryActivateStage(const String& packageName, const String& stageName, bool activate, bool reload,
+		Shared<Defer>::Ptr resetPackageUpdates = nullptr);
```
Comment (Al2Klimov) [inline lib/remote/configpackageutility.hpp:43]: What's the default for?

File: lib/remote/configpackageutility.hpp [hunk 18]
```diff
@@ -59,7 +62,8 @@ class ConfigPackageUtility
 	static void WritePackageConfig(const String& packageName);
 	static void WriteStageConfig(const String& packageName, const String& stageName);
 
-	static void TryActivateStageCallback(const ProcessResult& pr, const String& packageName, const String& stageName, bool activate, bool reload);
+	static void TryActivateStageCallback(const ProcessResult& pr, const String& packageName, const String& stageName, bool activate,
+		bool reload, const Shared<Defer>::Ptr& resetPackageUpdates = nullptr);
```
Comment (Al2Klimov) [inline lib/remote/configpackageutility.hpp:66]: What's the default for?

File: lib/remote/configstageshandler.cpp [hunk 19]
```diff
@@ -128,19 +131,25 @@ void ConfigStagesHandler::HandlePost(
...
 		/* validate the config. on success, activate stage and reload */
-		ConfigPackageUtility::AsyncTryActivateStage(packageName, stageName, activate, reload);
+		ConfigPackageUtility::AsyncTryActivateStage(packageName, stageName, activate, reload, resetPackageUpdates);
 	} catch (const std::exception& ex) {
 		return HttpUtility::SendJsonError(response, params, 500,
 			"Stage creation failed.",
 			DiagnosticInformation(ex));
 	}
 
-
```
Comment (Al2Klimov) [inline lib/remote/configstageshandler.cpp:143]: What's this?

File: lib/remote/configstageshandler.cpp [hunk 20]
```diff
@@ -212,4 +221,3 @@ void ConfigStagesHandler::HandleDelete(
 	response.result(http::status::ok);
 	HttpUtility::SendJsonBody(response, params, result);
 }
-
```
Comment (Al2Klimov) [inline lib/remote/configstageshandler.cpp:215]: What's this?

**Review by Al2Klimov — CHANGES_REQUESTED** [review]

File: lib/remote/configstageshandler.cpp (hunk 19 above)
Comment (yhabteab) [reply lib/remote/configstageshandler.cpp:143]: Just caught my eye and fixed it right away. Is this a reason for a change request?

File: lib/remote/configstageshandler.cpp (hunk 20 above)
Comment (yhabteab) [reply lib/remote/configstageshandler.cpp:215]: same 👆

File: lib/remote/configpackageutility.cpp (hunk 16 above)
Comment (yhabteab) [reply lib/remote/configpackageutility.cpp:214]: Well 🫤, since the deferred callback isn't going out of scope prior to the `AsyncTryActivateStage()` starting a new process, so it's fine to make it const ref, I guess.

**Comment by yhabteab** [comment]
> @yhabteab Is this intentionally still in draft state?

Sorry, forgot to press the ready!

File: lib/remote/configpackageutility.hpp (hunk 18 above)
Comment (yhabteab) [reply lib/remote/configpackageutility.hpp:66]: Not sure, does someone want to be able to use this method without this param or not? Did not want to break anything.

File: lib/base/defer.hpp [hunk 21]
```diff
@@ -30,13 +30,21 @@ class Defer
 	inline
 	~Defer()
 	{
-		try {
-			m_Func();
-		} catch (...) {
-			// https://stackoverflow.com/questions/130117/throwing-exceptions-out-of-a-destructor
+		if (m_Func != nullptr) {
```
Comment (Al2Klimov) [inline lib/base/defer.hpp:33]: Btw. wondering whether ` != nullptr` is actually necessary.

File: lib/remote/configpackageutility.cpp (hunk 16 above)
Comment (julianbrost) [reply lib/remote/configpackageutility.cpp:214]: `const Ptr&` is probably more consistent with how it's used in other places.

File: lib/base/defer.hpp (hunk 21 above)
Comment (julianbrost) [reply lib/base/defer.hpp:33]: Doesn't really make a difference, both does pretty much the same:
* https://en.cppreference.com/w/cpp/utility/functional/function/operator_cmp
* https://en.cppreference.com/w/cpp/utility/functional/function/operator_bool

File: lib/remote/configpackageutility.hpp (hunk 18 above)
Comment (julianbrost) [reply lib/remote/configpackageutility.hpp:66]: But the uses where the parameter is used are the only ones, aren't they? So doesn't really hurt to have the default, but it also isn't needed though.

**Review by Al2Klimov — APPROVED** [review]

**Comment by Al2Klimov** [comment]
@yhabteab Backport this PR.
