### PR TITLE
Ensure the daemon doesn't get killed by logrotate

### LINKED ISSUE #8050: Logrotate-related crash with icinga2 2.11.3-1
## Describe the bug

Last night one of our icinga2 satellites died. Application restart and logrotate for icinga2.log happened in the same minute. I found the following log entries:

**messages**
```
Jun  9 03:15:05 satellite02 logrotate: ALERT exited abnormally with [1]
Jun  9 03:15:07 satellite02 rhsmd: In order for Subscription Manager to provide your system with updates, your system must be registered with the Customer Portal. Please enter your Red Hat login to ensure your system is up-to-date.
Jun  9 03:15:49 satellite02 systemd: icinga2.service: main process exited, code=exited, status=138/n/a
Jun  9 03:15:49 satellite02 systemd: Unit icinga2.service entered failed state.
Jun  9 03:15:49 satellite02 systemd: icinga2.service failed.
```

**icinga2.log**

```
[2020-06-09 03:14:44 +0200] information/Application: Received request to shut down.
[2020-06-09 03:14:44 +0200] information/Application: Shutting down...
[2020-06-09 03:15:39 +0200] warning/JsonRpcConnection: API client disconnected for identity 'master02'
[2020-06-09 03:15:39 +0200] warning/ApiListener: Removing API client for endpoint 'master02'. 0 API clients left.
[2020-06-09 03:15:41 +0200] information/CheckerComponent: 'checker' stopped.
[2020-06-09 03:15:41 +0200] information/ApiListener: 'api' stopped.

```

## To Reproduce

It seems logrotete-related to me.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):

**satellite**
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.3-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.8 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1127.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Enabled features (`icinga2 feature list`):

**satellite**
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus notification opentsdb perfdata statusdata syslog
Enabled features: api checker mainlog
```

* Icinga Web 2 version and modules (System - About):

```
Icinga Web 2 Version
    2.7.3
Git Commit
    06cabfe8ba28cf545a42c92f25484383191a4e51
PHP Version
    7.1.8
Git Commit Datum
    2019-10-18
Copyright
    © 2013-2020 Das Icinga Projekt 
```

```
businessprocess 	2.2.0
graphite 	1.1.0
ipl 	v0.3.0
monitoring 	2.7.3
own module 	1.6 
```

* Config validation (`icinga2 daemon -C`):

**satellite**

```
[2020-06-09 09:43:14 +0200] information/cli: Icinga application loader (version: 2.11.3-1)
[2020-06-09 09:43:14 +0200] information/cli: Loading configuration file(s).
[2020-06-09 09:43:16 +0200] information/ConfigItem: Committing config item(s).
[2020-06-09 09:43:16 +0200] information/ApiListener: My API identity: satellite02
[2020-06-09 09:43:16 +0200] warning/CheckerComponent: Attribute 'concurrent_checks' for object 'checker' of type 'CheckerComponent' is deprecated and should not be used.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 76 HostGroups.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 12497 Hosts.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 2 Comments.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 14 Zones.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 12 Endpoints.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 305 CheckCommands.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 6 TimePeriods.
[2020-06-09 09:43:21 +0200] information/ConfigItem: Instantiated 48246 Services.
[2020-06-09 09:43:21 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-06-09 09:43:21 +0200] information/cli: Finished validating the configuration file(s).
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
refs #8050

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
[2020-08-11 15:37:00 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-08-11 15:37:00 +0200] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-08-11 15:37:00 +0200] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-08-11 15:37:00 +0200] notice/cli: Notifying umbrella process (PID 31120) about the config loading success
[2020-08-11 15:37:00 +0200] notice/cli: Worker process successfully loaded its config
[2020-08-11 15:37:00 +0200] information/Application: Reload done, old process shutting down. Child process with PID '31141' is taking over.
[2020-08-11 15:37:00 +0200] notice/cli: Waiting for the umbrella process to let us doing the actual work
[2020-08-11 15:37:00 +0200] information/Application: Received request to shut down.
[2020-08-11 15:37:00 +0200] information/Application: Shutting down...
[2020-08-11 15:37:00 +0200] information/CheckerComponent: 'checker' stopped.
[2020-08-11 15:37:00 +0200] information/NotificationComponent: 'notification' stopped.
[2020-08-11 15:37:00 +0200] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-08-11 15:37:00 +0200] information/IcingaApplication: Icinga has shut down.
[2020-08-11 15:37:00 +0200] notice/cli: Waited for 13 milliseconds on old process to exit.
[2020-08-11 15:37:00 +0200] notice/cli: Got signal 30, forwarding to seemless worker (PID 31141)
[2020-08-11 15:37:00 +0200] notice/cli: Seemless worker (PID 31141) stopped, stopping as well
➜  icinga2 git:(master) echo $?
158
```

## After

```
[2020-08-11 15:54:10 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-08-11 15:54:10 +0200] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-08-11 15:54:10 +0200] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-08-11 15:54:10 +0200] notice/cli: Notifying umbrella process (PID 32707) about the config loading success
[2020-08-11 15:54:10 +0200] notice/cli: Worker process successfully loaded its config
[2020-08-11 15:54:10 +0200] notice/cli: Waiting for the umbrella process to let us doing the actual work
[2020-08-11 15:54:10 +0200] information/Application: Reload done, old process shutting down. Child process with PID '32772' is taking over.
[2020-08-11 15:54:10 +0200] information/Application: Received request to shut down.
[2020-08-11 15:54:10 +0200] information/Application: Shutting down...
[2020-08-11 15:54:10 +0200] information/CheckerComponent: 'checker' stopped.
[2020-08-11 15:54:10 +0200] information/NotificationComponent: 'notification' stopped.
[2020-08-11 15:54:10 +0200] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-08-11 15:54:10 +0200] information/IcingaApplication: Icinga has shut down.
[2020-08-11 15:54:10 +0200] notice/cli: Waited for 13 milliseconds on old process to exit.
[2020-08-11 15:54:10 +0200] notice/cli: Got signal 30, forwarding to seemless worker (PID 32772)
[2020-08-11 15:54:10 +0200] notice/cli: The umbrella process let us continuing
[2020-08-11 15:54:10 +0200] information/ConfigObject: Restoring program state from file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-08-11 15:54:10 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'ConfigObject::RestoreObjects'
[2020-08-11 15:54:10 +0200] information/ConfigObject: Restored 281 objects. Loaded 0 new objects without state.
[2020-08-11 15:54:10 +0200] notice/WorkQueue: Stopped WorkQueue threads for 'ConfigObject::RestoreObjects'
[2020-08-11 15:54:10 +0200] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/modified-attributes.conf
[2020-08-11 15:54:10 +0200] information/ConfigItem: Triggering Start signal for config items
[2020-08-11 15:54:10 +0200] information/FileLogger: 'main-log' started.
[2020-08-11 15:54:10 +0200] information/NotificationComponent: 'notification' started.
[2020-08-11 15:54:10 +0200] information/CheckerComponent: 'checker' started.
[2020-08-11 15:54:10 +0200] information/ConfigItem: Activated all objects.
```

## Logrotate still works

```
[2020-08-11 15:56:43 +0200] notice/cli: Got signal 30, forwarding to seemless worker (PID 32848)
[2020-08-11 15:56:43 +0200] information/Application: Received USR1 signal, reopening application logs.
[2020-08-11 15:56:44 +0200] notice/Application: Reopening log files
```

File: lib/cli/daemoncommand.cpp [hunk 1]
```diff
@@ -367,6 +367,9 @@ static void UmbrellaSignalHandler(int num, siginfo_t *info, void*)
 static void WorkerSignalHandler(int num, siginfo_t *info, void*)
 {
 	switch (num) {
+		case SIGUSR1:
+			// Not ready, yet
```
Comment (julianbrost) [inline lib/cli/daemoncommand.cpp:371]: Comment could be better. Something along the lines of "Ignore SIGUSR1 during startup phase. This signal handler will be replaced with the real one in [reference to where it happens]."

**Review by julianbrost — APPROVED** [review]
