### PR TITLE
Cluster config sync: Fix new files not being moved

### LINKED ISSUE #7296: Staging config not copied to production
This is a followup for #7282 

Config sync is not working for master master for me anymore. Config is synced, but not moved to production. The comparison of staging and production is regarded as equal even if it clearly is not.

## Setup
Version dfws: v2.10.5-883-g09fe57039 (master)
Version icigna vagrant: bugfix/cluster-sync-checksum-change

Zones.conf:
```
object Endpoint "dfws" {
	host = "127.0.0.1"
}
object Endpoint "icinga2.vagrant.demo.icinga.com" {
	host = "192.168.33.5"
}
object Zone "double" {
	endpoints = [ "dfws", "icinga2.vagrant.demo.icinga.com"]
}
```

icinga vagrant box has accept config and commands set to true.

cat dfws/zones.d/double:
```
object Host "Horst" {
	check_command = "dummy"
	check_interval = 2s
	vars.foo = 2
}
```

Log on the master:
```
[2019-07-08 15:28:37 +0200] information/ApiListener: New client connection for identity 'icinga2.vagrant.demo.icinga.com' from [192.168.33.5]:50838
[2019-07-08 15:28:37 +0200] information/ApiListener: Sending config updates for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Syncing configuration files for global zone 'global-templates' to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Syncing configuration files for zone 'double' to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished sending config file updates for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Syncing runtime objects to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished syncing runtime objects to endpoint 'icinga2.vagrant.demo.icinga.com'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished sending runtime config updates for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Sending replay log for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished sending replay log for endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Finished syncing endpoint 'icinga2.vagrant.demo.icinga.com' in zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Applying config update from endpoint 'icinga2.vagrant.demo.icinga.com' of zone 'double'.
[2019-07-08 15:28:37 +0200] information/ApiListener: Ignoring config update from endpoint 'icinga2.vagrant.demo.icinga.com' for zone 'double' because we have an authoritative version of the zone's config.
[2019-07-08 15:28:37 +0200] information/ApiListener: Received configuration from endpoint 'icinga2.vagrant.demo.icinga.com' is equal to production, not triggering reload.
```
So far so good, on the other master:
```
[2019-07-08 15:33:09 +0200] information/ApiListener: New client connection for identity 'dfws' from [192.168.33.1]:33720
[2019-07-08 15:33:09 +0200] information/ApiListener: Sending config updates for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Syncing configuration files for zone 'double' to endpoint 'dfws'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished sending config file updates for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Syncing runtime objects to endpoint 'dfws'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished syncing runtime objects to endpoint 'dfws'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished sending runtime config updates for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Sending replay log for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Replayed 33 messages.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished sending replay log for endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Finished syncing endpoint 'dfws' in zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Applying config update from endpoint 'dfws' of zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Received configuration for zone 'double' from endpoint 'dfws'. Comparing the checksums.
[2019-07-08 15:33:09 +0200] information/ApiListener: Stage: Updating received configuration file '/var/lib/icinga2/api/zones-stage/double//_etc/host.conf' for zone 'double'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones-stage/double' (237 Bytes).
[2019-07-08 15:33:09 +0200] warning/ApiListener: Ignoring config update from endpoint 'dfws' for unknown zone 'global-templates'.
[2019-07-08 15:33:09 +0200] information/ApiListener: Received configuration from endpoint 'dfws' is equal to production, not triggering reload.
```
Querying the config replica:
```
[root@icinga2 zones]# curl -ks -u root:ecf17b9f3bbb583c https://127.0.0.1:5665/v1/objects/hosts/Horst | python -m json.tool
{
    "error": 404.0,
    "status": "No objects found."
}

[root@icinga2 zones]# cat /var/lib/icinga2/api/zones-stage/double/_etc/host.conf 
object Host "Horst" {
	check_command = "dummy"
	check_interval = 2s
	vars.foo = 2
}

[root@icinga2 zones]# cat /var/lib/icinga2/api/zones/double/_etc/host.conf 
cat: /var/lib/icinga2/api/zones/double/_etc/host.conf: No such file or directory
```

### PR DESCRIPTION
**Pull request by Crunsher**
This changes the algorithm for computing staging/production changes.

First we go over the old checksums and if one is missing or has changed we know we have to update. After this we traverse the new checksums to find out if one is new. This also adds a few possibly unnecessary Debug log messages.

Full test protocol will follow, so far I have tested this only for the case of no old config.

fixes #7296

### CODE REVIEW

**Comment by Crunsher** [comment]
Everything was tested with this setup:
```
object Zone "double" {
	endpoints = [ "dfws", "icinga2.vagrant.demo.icinga.com" ]
}
```

dfws being the config master with a current icinga2 snapshot and icinga2.vagrant.demo.icinga.com receiving the config on this PR. I'm skipping posting all the logs, to check if it works I'm using icinga2 object list and checking the folders.

Cases tested:
1. No config -> Some config
2. Some config -> Some more config
3. Some more config -> Less config
... And this leads to another reload loop

**Comment by Crunsher** [comment]
I suspect the issue here: https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener-filesync.cpp#L445
We delete the production config, but don't copy what we had in production over from staging. So when you have two files or more files, every reload some of them are prod the others new and just switch paces forever.

**Comment by Crunsher** [comment]
New commit fixes the reload loop, but now we always copy everything from staging. See #7307 to make this a none issue.

Or we improve how we handle our delta, something we got a bit of experience with from working with IcingaDB :whale:

**Comment by dnsmichi** [comment]
> but now we always copy everything from staging. 

Please elaborate with logs/examples, do you mean that the entire content from staging is copied as expected, or something else?

File: lib/remote/apilistener-filesync.cpp [hunk 1]
```diff
@@ -667,35 +663,81 @@ bool ApiListener::CheckConfigChange(const ConfigDirInformation& oldConfig, const
...
+						<< "Path '" << path << "' doesn't match old checksum '"
+						<< oldChecksum << "' with new checksum '" << newChecksum << "'.";
+				return true;
+			}
+		}
+	}
+
+	{
+		ObjectLock olock(newChecksums);
+		for (const Dictionary::Pair& kv : newChecksums) {
```
Comment (dnsmichi) [inline lib/remote/apilistener-filesync.cpp]: This duplicates the code, imho it is sufficient to pick the Dictionary with the greater length and iterate over it. It then can check against matches in the other Dictionary.

See https://github.com/Icinga/icinga2/pull/7306/commits/6af65a72488c8c136ad90d79c594c0c1a18d9d03 how you would assign the "generic" Dictionary for the loop depending on the size, and then iterate over it.

Comment (Crunsher) [reply lib/remote/apilistener-filesync.cpp]: The issue is that newChecksums has two additional checksums, so the following would lead to "no changed config" when not having the second loop and only going with the larger dictionary:
oldChecksums: {a, b, c, d}
newChecksums: {.timestamp, .checksums, a, b, c }

**Comment by Crunsher** [comment]
> Please elaborate with logs/examples, do you mean that the entire content from staging is copied as expected, or something else?

I am referring to what I describe in #7307, so this a separate issue/question. I commented here first before I noticed that.

File: lib/remote/apilistener-filesync.cpp [hunk 2]
```diff
@@ -468,7 +466,7 @@ Value ApiListener::ConfigUpdateHandler(const MessageOrigin::Ptr& origin, const D
 		}
 
 		Log(LogInformation, "ApiListener")
-			<< "Applying configuration file update for path '" << stageConfigZoneDir << "' ("
+			<< "AppStage: Updating received configuradate for path '" << stageConfigZoneDir << "' ("
```
Comment (dnsmichi) [inline lib/remote/apilistener-filesync.cpp]: Why the new term `AppStage`? Please leave the log message "as is", this follows known patterns from 2.10.x.

File: lib/remote/apilistener-filesync.cpp (hunk 1 above)
Comment (dnsmichi) [reply lib/remote/apilistener-filesync.cpp]: Ok, then please move this at least into a generic function which does the loop and checks. This avoids code duplication and possible errors.

File: lib/remote/apilistener-filesync.cpp (hunk 2 above)
Comment (Crunsher) [reply lib/remote/apilistener-filesync.cpp]: I don't know where that comes, probably a rebase fail

File: lib/remote/apilistener-filesync.cpp (hunk 1 above)
Comment (Crunsher) [reply lib/remote/apilistener-filesync.cpp]: I thought about that, the two loops are different. The first one compares checksums but the second does not care about that. So a function comareChecksums() would only need to be called once. As in the whole block becomes a function.

Comment (dnsmichi) [reply lib/remote/apilistener-filesync.cpp]: Ah, ok. After re-reading the code again, it makes sense.

**Comment by dnsmichi** [comment]
Rebased, fixed some style issues, removed comments, and updated author/commit messages.

File: lib/remote/apilistener-filesync.cpp (hunk 2 above)
Comment (Crunsher) [reply lib/remote/apilistener-filesync.cpp]: Has been changed back

**Comment by Crunsher** [comment]
Only thing left from my side is the debug messages. It's quite verbose currently and some of the information is doubled. Maybe we want to log both checksums dicts once and leave it at that?

**Comment by dnsmichi** [comment]
I'm fine with it for now.

**Comment by Crunsher** [comment]
Checked the code again, it's verbose but since it's ran rarely and could help us with skipped or missing files I'm fine with leaving it in too.

Feel free to merge :)

**Comment by dnsmichi** [comment]
Merging, thanks for the analysis and findings in this patch 👍
