### PR TITLE
PluginNotificationTask::ScriptFunc(): on Linux truncate output and comment

### LINKED ISSUE #9340: Notfication scripts exiting with "Argument list too long"
# Bug description

The notifications do not work if there are too many arguments passed when the error output that Icinga passes to the mail is too long.

# Reproduce

- Create a check like check_logfile that checks /tmp/foobar for ERROR. The check itself doesn't matter, it can happen with any check.
- Create the file /tmp/foobar
- Fill /tmp/foobar with a line starting with ERROR to trigger the check and then insert for example 100000 random characters after the ERROR and make a space every 100 characters.
- Icinga will now check the file and the attempt to send a message will fail with "terminated with exit code 128, output: execvpe(/etc/icinga2/scripts/mail-service-notification.py) failed: Argument list too long

The problem here is that the operating system determines how many characters arguments can have.
NOTE: THIS IS NOT A PROBLEM WITH NOTIFICATION SCRIPTS, IT DEPENDS ON THE FACT HOW LINUX WORK.

# Cause
The problem is, Icinga passes the whole unabridged error to the notification script, but then the OS comes along and says "no no, that's too much I'm on strike" and aborts the script with the above error.

# Affected versions
- all since at least 2.11 (we didn't check further back)

# Suggested solution
Passed errors should be shortened by Icinga directly before the call is passed to the OS.

### PR DESCRIPTION
**Pull request by Al2Klimov**
not to run into an exec(3) error E2BIG due to a too long argument.    This sends a notification with truncated output instead of not sending.

fixes #9340

### Reproduction before this PR

```
[2023-10-25 12:14:34 +0200] warning/PluginCheckTask: Check command for object 'e2big' (PID: 90872, arguments: 'true') terminated with exit code 128, output: execvpe(true) failed: Argument list too long
```

### CODE REVIEW

**Comment by julianbrost** [comment]
I strongly disagree with the basic idea of this PR: if a function is supposed to execute a specific command, it may not simply truncate the command and hope for the best. If you alter the command, you don't know if it still performs the same or at least a desirable action. For example, you don't know that you're not truncating a list of e-mail addresses, cut off a domain name somewhere in the middle and then send a notification to a wrong address. If automatic truncation should happen, it would have to know where it's safe to do so.

So for me, truncating specific values in the command definition as suggested by https://github.com/Icinga/icinga2/issues/9340#issuecomment-1181699738 sound like a way safer and better approach in the short term. In the longer term, we could discuss if it even makes sense allowing arbitrarily large check outputs or if it's a broken check that's just sending garbage anyways if it exceeds some limit.

**Comment by Al2Klimov** [comment]
@julianbrost Do you want to touch every single command definition? (As a user.) Before or after you realise that you're loosing notifications?

@lippserd Please share your opinion on the concept (as a review).

**Comment by julianbrost** [comment]
> Do you want to touch every single command definition? (As a user.)

If that and this PR are my only options, yes. If the configuration results in a command that's too long to execute, it's safer to return an error instead of arbitrarily removing parts of the command until it's short enough to execute.

There are other options we could do though. After all, your PR probably tries to truncate the plugin output but that code location no longer has the information what part was the plugin output, so you make a guess. For a safe option, we have to know what we're truncating. In order to achieve this for existing configurations without user intervention, we'd have to ensure that the `$output$` length is limited to a sane value, so one option could be to say that `$output$` is always truncated to 64K and if you really want it, there's some `$output_full$`. Or we could place a general limit on the output size, which might also be a good idea in terms of memory usage and database growth. But all of this sound more like something to be discussed for 2.15 instead of 2.14.1.

**Comment by slalomsk8er** [comment]
This reminds me of https://github.com/Linuxfabrik/monitoring-plugins/issues/559

**Comment by Al2Klimov** [comment]
I understand and respect your position. I just don't agree with it.

First of all, almost everything can handle long outputs. Only exec(3) can't. So IMAO _just it_ should shorten stuff as it's objectively necessary.

Second, why 64K? Let me derive a formula from your _unexpected shortening is bad_ opinion: the more you shorten unexpectedly, the worse. So I'd prefer to shorten only as much as the OS requires me to do. Admittedly the current algorithm is a bit radical while dividing strings by 2 every time. Maybe I can change this to, say, 1.5 if you wish. After all this is the slow path(TM) where such delay is acceptable.

Also, what about this alternative: the Process takes a bool whether to shorten which isn't set for checks. So you _notice_ when your checks fail due to long strings. Also, I mean... _we have to_ shorten notification cmd lines directly or indirectly. So, given this alternative, does it really matter where in the code that happens?

**Comment by julianbrost** [comment]
> does it really matter where in the code that happens?

Yes, you're changing a general "execute this command" function that does not know what exactly it's shortening. It should know that it's shortening the output and only the output (and maybe other fields that were explicitly marked as safe to be shortened). Otherwise, you don't know if your shortening operation is safe to perform.

**Comment by Al2Klimov** [comment]
> It should know that it's shortening the output and only the output (and maybe other fields that were explicitly marked as safe to be shortened).

OK if PluginNotificationTask::ScriptFunc() fetches host.output, service.output and notification.comment values, passes them down to PluginUtility::ExecuteCommand() and Process::Process() and the latter shortens only strings which equals those values? Of course if they're like >=1024 characters, so that's a safe match?

OK if the above shortening is based on string X _contains_ string Y? So -output=$output$ is also shortened, not just literal $output$.

**Comment by Al2Klimov** [comment]
# Test protocol II

## Config

```
object Host "lolcat" {
  check_command = "dummy"
var big = "x"
	for (i in range(20)) {
		big = big + big
	}
vars.dummy_state=2
max_check_attempts=1
  vars.dummy_text = big + "Y"
}

object NotificationCommand "lolcat" {
 command = ["bash", "-c", "echo $$0; exit 139", "$output$"]
}

object User "lolcat" {
}

object Notification "lolcat" {
  host_name = "lolcat"
  command = "lolcat"
  users = ["lolcat"]
}
```

## Result

```
...xxxxxxx
[2023-11-09 15:19:22 +0100] notice/CheckerComponent: Pending checkables: 0;...
```

👍 The Y in "$output$" of the NotificationCommand was truncated.

File: lib/base/process.cpp [hunk 1]
```diff
@@ -174,16 +212,65 @@ static Value ProcessSpawnImpl(struct msghdr *msgh, const Dictionary::Ptr& reques
...
+					if (safeToTruncateArgs.empty()) {
+						// Initialize safeToTruncateArgs
+						for (auto strings : {argv, envp}) {
+							for (auto it (strings); *it; ++it) {
+								auto s (*it);
+								auto len (strlen(s));
+
+								for (auto suffix : safeToTruncateStrings) {
+									if (suffix.second <= len) {
+										auto substr (s + len - suffix.second);
```
Comment (julianbrost) [inline lib/base/process.cpp:227]: The use of `auto` hides what's actually going on here and whether these operations are actually safe to perform in the forked process. I think this would greatly benefit from explicitly specifying the types.

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/base/process.cpp [hunk 2]
```diff
@@ -136,6 +140,40 @@ static Value ProcessSpawnImpl(struct msghdr *msgh, const Dictionary::Ptr& reques
...
+	std::vector<char*> safeToTruncateArgs;
+
+	if (safeToTruncate) {
+		// Lock here recursively, not in the fork(2)ed child
+		ObjectLock lock (safeToTruncate);
+
+		safeToTruncateStrings.reserve(safeToTruncate->GetLength());
+
+		for (auto& v : safeToTruncate) {
+			if (v.GetType() == ValueString) {
```
[the remark this answers is not in the document]
Comment (Al2Klimov) [reply lib/base/process.cpp:153]: It's part of _request_ which is passed via JSON IPC. Our JSON has dynamic types by design.

**Comment by Al2Klimov** [comment]
Honestly tried to unit test all this. Hits the Boost timeout, not to even mention GHA. a2ea751ec911dfa6c6f24de46f4d90efb9c6878f

File: lib/methods/pluginnotificationtask.cpp [hunk 3]
```diff
@@ -62,8 +62,26 @@ void PluginNotificationTask::ScriptFunc(const Notification::Ptr& notification,
...
+		safeToTruncate->Add(hostCr->GetOutput());
+	}
+
+	if (service) {
+		auto cr (service->GetLastCheckResult());
+
+		if (cr) {
+			safeToTruncate->Add(cr->GetOutput());
+		}
+	}
```
Comment (yhabteab) [inline lib/methods/pluginnotificationtask.cpp:79]: Why don't you just go with the output from the `cr` parameter and be done with it? After all, that given `cr` belongs to either a host or a service, so why do you need both?

File: lib/base/process.cpp [hunk 4]
```diff
@@ -174,16 +206,65 @@ static Value ProcessSpawnImpl(struct msghdr *msgh, const Dictionary::Ptr& reques
...
-		if (icinga2_execvpe(argv[0], argv, envp) < 0) {
-			char errmsg[512];
-			strcpy(errmsg, "execvpe(");
-			strncat(errmsg, argv[0], sizeof(errmsg) - strlen(errmsg) - 1);
-			strncat(errmsg, ") failed", sizeof(errmsg) - strlen(errmsg) - 1);
-			errmsg[sizeof(errmsg) - 1] = '\0';
-			perror(errmsg);
-		}
+		for (;;) {
+			if (icinga2_execvpe(argv[0], argv, envp) < 0) {
```
Comment (yhabteab) [inline lib/base/process.cpp:210]: All these nested for loops look kind of scary. Wouldn't it be better to truncate the arguments while they are longer than `ARG_MAX`, without calling `icinga2_execvpe` over and over again? Nothing should change in functionality, I would just find it better to read this way!

File: lib/methods/pluginnotificationtask.cpp (hunk 3 above)
Comment (julianbrost) [reply lib/methods/pluginnotificationtask.cpp:79]: You could have a `NotificationCommand` that passes both `$host.output$` and `$service.output$`, where both outputs could be excessively long.

File: lib/base/process.cpp (hunk 4 above)
Comment (julianbrost) [reply lib/base/process.cpp:210]: Additionally, all this happens after `fork()`, so you have to be extremely careful regarding what operations are safe to perform. If this would simply happen before, the code should be much simpler.

File: lib/methods/pluginnotificationtask.cpp [hunk 5]
```diff
@@ -12,6 +12,17 @@
 #include "base/process.hpp"
 #include "base/convert.hpp"
 
+#ifdef __linux__
+#	include <linux/binfmts.h>
+#	include <unistd.h>
+
+#	ifndef PAGE_SIZE
+#		define PAGE_SIZE getpagesize()
+#	endif /* PAGE_SIZE */
```
Comment (yhabteab) [inline lib/methods/pluginnotificationtask.cpp:21]: Why define a constant page size if you aren't going to use it in any way?

File: lib/methods/pluginnotificationtask.cpp [hunk 6]
```diff
@@ -48,8 +63,35 @@ void PluginNotificationTask::ScriptFunc(const Notification::Ptr& notification,
...
+
+	if (service) {
+#ifdef __linux__
+		auto cr (service->GetLastCheckResult());
+
+		if (cr) {
+			auto output (cr->GetOutput());
+
+			if (output.GetLength() > l_MaxOutLen) {
+				resolvers.emplace_back("service", new Dictionary({{"output", output.SubStr(0, l_MaxOutLen)}}));
```
Comment (yhabteab) [inline lib/methods/pluginnotificationtask.cpp:75]: If it's Linux, the macro resolver key `service` is set twice? Is it safe to rely on the vector element insertion order and expect this element to be found before the actual service object?

File: lib/methods/pluginnotificationtask.cpp [hunk 7]
```diff
@@ -12,6 +12,17 @@
...
 
+#ifdef __linux__
+#	include <linux/binfmts.h>
+#	include <unistd.h>
+
+#	ifndef PAGE_SIZE
+#		define PAGE_SIZE getpagesize()
+#	endif /* PAGE_SIZE */
+
+const static auto l_MaxOutLen = MAX_ARG_STRLEN * 3u / 4u;
```
Comment (yhabteab) [inline lib/methods/pluginnotificationtask.cpp:23]: It would be nice to have some docs explaining the numbers!

File: lib/methods/pluginnotificationtask.cpp (hunk 6 above)
Comment (Al2Klimov) [reply lib/methods/pluginnotificationtask.cpp:78]: _notification_ is already set twice, on all platforms.

File: test/methods-pluginnotificationtask.cpp [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+	nc->Unregister();
+
+	String commandline = Array::Ptr(future.get())->Join(" ");
+
+	BOOST_CHECK(commandline.Contains("echo Hx"));
+	BOOST_CHECK(!commandline.Contains("xh"));
+	BOOST_CHECK(commandline.Contains("x Sx"));
+	BOOST_CHECK(!commandline.Contains("xs"));
+	BOOST_CHECK(commandline.Contains("x Cx"));
+	BOOST_CHECK(!commandline.Contains("xc"));
```
Comment (yhabteab) [inline test/methods-pluginnotificationtask.cpp:71]: IMHO it would be much more realistic if you actually would test the actual length of the passed arguments.
```cxx
nc->SetCommandLine(new Array({"echo", "--host-output=", "$host.output$", "--service-output=", "$service.output$", "--comment=", "$notification.comment$"}), true);
```

You can then e.g test whether the `--host-output` value is actually `10%` shorter than its original length.

Comment (Al2Klimov) [reply test/methods-pluginnotificationtask.cpp:71]: But it doesn't matter whether it's 5%, 10% or 15% less than PAGE_SIZE times N. It only matters that really looooooooooooong values of X, Y and Z are truncated in a particular way.

Comment (julianbrost) [inline test/methods-pluginnotificationtask.cpp:71]: Wouldn't it be more straight-forward to check that the specific parts of the command line array are prefixes of the input values?

Also, this does actually execute `echo`, doesn't it? So wouldn't it make sense to also check check that exit code and output so that the test case also covers the actual execution?

File: test/methods-pluginnotificationtask.cpp [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+	((ConfigObject*)s.get())->OnAllConfigLoaded(); // link Host
+
+	nc->SetName("mail", true);
+	nc->SetCommandLine(new Array({"echo", "$host.output$", "$service.output$", "$notification.comment$"}), true);
+	nc->Register();
+
+	n->SetFieldByName("host_name", "example.com", false, DebugInfo());
+	n->SetFieldByName("service_name", "disk", false, DebugInfo());
+	n->SetFieldByName("command", "mail", false, DebugInfo());
+	((ConfigObject*)n.get())->OnAllConfigLoaded(); // link Service
```
Comment (julianbrost) [inline test/methods-pluginnotificationtask.cpp:51]: Same thing as in https://github.com/Icinga/icinga2/pull/9893#discussion_r1425100490: don't do strange casts to indirectly call a function that could and should just be public instead.

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/base/process.cpp [hunk 10]
```diff
@@ -60,6 +63,21 @@ Process::Process(Process::Arguments arguments, Dictionary::Ptr extraEnvironment)
 {
 #ifdef _WIN32
 	m_Overlapped.hEvent = CreateEvent(nullptr, TRUE, FALSE, nullptr);
+#else /* _WIN32 */
+	for (auto i (safeToTruncate.size()); i--;) {
+		auto pos (safeToTruncate.begin() + i);
```
[the remark this answers is not in the document]
Comment (julianbrost) [reply lib/base/process.cpp]: Forget this one, that's a left-over from some time ago.

File: test/methods-pluginnotificationtask.cpp (hunk 8 above)
Comment (yhabteab) [reply test/methods-pluginnotificationtask.cpp]: This is not yet solved! You haven't made any changes to the address this suggestion:
> So wouldn't it make sense to also check check that exit code and output so that the test case also covers the actual execution?

Comment (Al2Klimov) [reply test/methods-pluginnotificationtask.cpp]: Checking the actual execution via the output is totally enough.

**Review by julianbrost — APPROVED** [review]

**Review by yhabteab — APPROVED** [review]
