### PR TITLE
Fix unsafe concurrent access to m_DataBuffer in InfluxdbCommonWriter

### LINKED ISSUE #9102: Crash: double free or corruption (out)
## Describe the bug

Today our secondary master has died. Upon investigating we found the following logs. I hope this helps:

**crash report**

```
Caught SIGABRT.
Current time: 2021-11-29 07:31:41 +0100

  Application version: 2.11.11-1

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.45.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-507-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Stacktrace:
 0# icinga::Application::SigAbrtHandler(int) in /usr/lib64/icinga2/sbin/icinga2
 1# 0x00007FE0570C8630 in /lib64/libpthread.so.0
 2# gsignal in /lib64/libc.so.6
 3# abort in /lib64/libc.so.6
 4# 0x00007FE056D63F67 in /lib64/libc.so.6
 5# 0x00007FE056D6C329 in /lib64/libc.so.6
 6# icinga::InfluxdbWriter::Flush() in /usr/lib64/icinga2/sbin/icinga2
 7# icinga::InfluxdbWriter::SendMetric(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::Dictionary> const&, icinga::String const&, boost::intrusive_ptr<icinga::Dictionary> const&, double) in /usr/lib64/icinga2/sbin/icinga2
 8# icinga::InfluxdbWriter::CheckResultHandlerWQ(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&) in /usr/lib64/icinga2/sbin/icinga2
 9# icinga::WorkQueue::RunTaskFunction(std::function<void ()> const&) in /usr/lib64/icinga2/sbin/icinga2
10# icinga::WorkQueue::WorkerThreadProc() in /usr/lib64/icinga2/sbin/icinga2
11# 0x00007FE058FC8954 in /lib64/libboost_thread.so.1.69.0
12# 0x00007FE0570C0EA5 in /lib64/libpthread.so.0
13# clone in /lib64/libc.so.6

***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***
[lots of information]
```

**error.log**
```
*** Error in `/usr/lib64/icinga2/sbin/icinga2': double free or corruption (out): 0x00007fdc7414f9b0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7fe056d6c329]
/usr/lib64/icinga2/sbin/icinga2(_ZN6icinga14InfluxdbWriter5FlushEv+0xe8)[0xe0d678]
/usr/lib64/icinga2/sbin/icinga2(_ZN6icinga14InfluxdbWriter10SendMetricERKN5boost13intrusive_ptrINS_9CheckableEEERKNS2_INS_10DictionaryEEERKNS_6StringESA_d+0x70f)[0xe0f8df]
/usr/lib64/icinga2/sbin/icinga2(_ZN6icinga14InfluxdbWriter20CheckResultHandlerWQERKN5boost13intrusive_ptrINS_9CheckableEEERKNS2_INS_11CheckResultEEE+0xba3)[0xe180d3]
/usr/lib64/icinga2/sbin/icinga2(_ZN6icinga9WorkQueue15RunTaskFunctionERKSt8functionIFvvEE+0x21)[0x922381]
/usr/lib64/icinga2/sbin/icinga2(_ZN6icinga9WorkQueue16WorkerThreadProcEv+0x4c7)[0x9229e7]
/lib64/libboost_thread.so.1.69.0(+0xf954)[0x7fe058fc8954]
/lib64/libpthread.so.0(+0x7ea5)[0x7fe0570c0ea5]
/lib64/libc.so.6(clone+0x6d)[0x7fe056de9b0d]
======= Memory map: ========
00400000-01084000 r-xp 00000000 fd:00 18329799                           /usr/lib64/icinga2/sbin/icinga2
01283000-01284000 r--p 00c83000 fd:00 18329799                           /usr/lib64/icinga2/sbin/icinga2
01284000-01286000 rw-p 00c84000 fd:00 18329799                           /usr/lib64/icinga2/sbin/icinga2
01286000-0128e000 rw-p 00000000 00:00 0
02927000-02a84000 rw-p 00000000 00:00 0                                  [heap]
02a84000-390ea000 rw-p 00000000 00:00 0                                  [heap]

[ .. lots of memory adresses. I include only the ones with extra content .. ]

7fe042246000-7fe042524000 r-xp 00000000 fd:00 160025                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7fe042524000-7fe042723000 ---p 002de000 fd:00 160025                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7fe042723000-7fe04272c000 r--p 002dd000 fd:00 160025                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7fe04272c000-7fe042740000 rw-p 002e6000 fd:00 160025                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7fe042740000-7fe042746000 rw-p 00000000 00:00 0
7fe042746000-7fe042749000 r-xp 00000000 fd:00 362851                     /usr/lib64/icinga2/libmysql_shim.so.2.11.11
7fe042749000-7fe042948000 ---p 00003000 fd:00 362851                     /usr/lib64/icinga2/libmysql_shim.so.2.11.11
7fe042948000-7fe042949000 r--p 00002000 fd:00 362851                     /usr/lib64/icinga2/libmysql_shim.so.2.11.11
7fe042949000-7fe04294a000 rw-p 00003000 fd:00 362851                     /usr/lib64/icinga2/libmysql_shim.so.2.11.11
[..]
7fe04357a000-7fe044000000 r--s 00000000 fd:09 6306                       /var/lib/sss/mc/initgroups
[..]
7fe050351000-7fe050359000 r-xp 00000000 fd:00 25177205                   /usr/lib64/libnss_sss.so.2
7fe050359000-7fe050558000 ---p 00008000 fd:00 25177205                   /usr/lib64/libnss_sss.so.2
7fe050558000-7fe050559000 r--p 00007000 fd:00 25177205                   /usr/lib64/libnss_sss.so.2
7fe050559000-7fe05055a000 rw-p 00008000 fd:00 25177205                   /usr/lib64/libnss_sss.so.2
[..]
7fe052003000-7fe05200f000 r-xp 00000000 fd:00 25670544                   /usr/lib64/libnss_files-2.17.so
7fe05200f000-7fe05220e000 ---p 0000c000 fd:00 25670544                   /usr/lib64/libnss_files-2.17.so
7fe05220e000-7fe05220f000 r--p 0000b000 fd:00 25670544                   /usr/lib64/libnss_files-2.17.so
7fe05220f000-7fe052210000 rw-p 0000c000 fd:00 25670544                   /usr/lib64/libnss_files-2.17.so
[..]
7fe052216000-7fe052225000 r-xp 00000000 fd:00 25259018                   /usr/lib64/libbz2.so.1.0.6
7fe052225000-7fe052424000 ---p 0000f000 fd:00 25259018                   /usr/lib64/libbz2.so.1.0.6
7fe052424000-7fe052425000 r--p 0000e000 fd:00 25259018                   /usr/lib64/libbz2.so.1.0.6
7fe052425000-7fe052426000 rw-p 0000f000 fd:00 25259018                   /usr/lib64/libbz2.so.1.0.6
7fe052426000-7fe05243d000 r-xp 00000000 fd:00 25655298                   /usr/lib64/libelf-0.176.so
7fe05243d000-7fe05263c000 ---p 00017000 fd:00 25655298                   /usr/lib64/libelf-0.176.so
7fe05263c000-7fe05263d000 r--p 00016000 fd:00 25655298                   /usr/lib64/libelf-0.176.so
7fe05263d000-7fe05263e000 rw-p 00017000 fd:00 25655298                   /usr/lib64/libelf-0.176.so
7fe05263e000-7fe05269e000 r-xp 00000000 fd:00 25803432                   /usr/lib64/libpcre.so.1.2.0
7fe05269e000-7fe05289e000 ---p 00060000 fd:00 25803432                   /usr/lib64/libpcre.so.1.2.0
7fe05289e000-7fe05289f000 r--p 00060000 fd:00 25803432                   /usr/lib64/libpcre.so.1.2.0
7fe05289f000-7fe0528a0000 rw-p 00061000 fd:00 25803432                   /usr/lib64/libpcre.so.1.2.0
7fe0528a0000-7fe0528a4000 r-xp 00000000 fd:00 25259087                   /usr/lib64/libattr.so.1.1.0
7fe0528a4000-7fe052aa3000 ---p 00004000 fd:00 25259087                   /usr/lib64/libattr.so.1.1.0
7fe052aa3000-7fe052aa4000 r--p 00003000 fd:00 25259087                   /usr/lib64/libattr.so.1.1.0
7fe052aa4000-7fe052aa5000 rw-p 00004000 fd:00 25259087                   /usr/lib64/libattr.so.1.1.0
7fe052aa5000-7fe052aa8000 r-xp 00000000 fd:00 25261385                   /usr/lib64/libkeyutils.so.1.5
7fe052aa8000-7fe052ca7000 ---p 00003000 fd:00 25261385                   /usr/lib64/libkeyutils.so.1.5
7fe052ca7000-7fe052ca8000 r--p 00002000 fd:00 25261385                   /usr/lib64/libkeyutils.so.1.5
7fe052ca8000-7fe052ca9000 rw-p 00003000 fd:00 25261385                   /usr/lib64/libkeyutils.so.1.5
7fe052ca9000-7fe052cb7000 r-xp 00000000 fd:00 25699824                   /usr/lib64/libkrb5support.so.0.1
7fe052cb7000-7fe052eb7000 ---p 0000e000 fd:00 25699824                   /usr/lib64/libkrb5support.so.0.1
7fe052eb7000-7fe052eb8000 r--p 0000e000 fd:00 25699824                   /usr/lib64/libkrb5support.so.0.1
7fe052eb8000-7fe052eb9000 rw-p 0000f000 fd:00 25699824                   /usr/lib64/libkrb5support.so.0.1
7fe052eb9000-7fe052f07000 r-xp 00000000 fd:00 25781157                   /usr/lib64/libdw-0.176.so
7fe052f07000-7fe053107000 ---p 0004e000 fd:00 25781157                   /usr/lib64/libdw-0.176.so
7fe053107000-7fe053109000 r--p 0004e000 fd:00 25781157                   /usr/lib64/libdw-0.176.so
7fe053109000-7fe05310a000 rw-p 00050000 fd:00 25781157                   /usr/lib64/libdw-0.176.so
7fe05310a000-7fe053120000 r-xp 00000000 fd:00 25670770                   /usr/lib64/libresolv-2.17.so
7fe053120000-7fe053320000 ---p 00016000 fd:00 25670770                   /usr/lib64/libresolv-2.17.so
7fe053320000-7fe053321000 r--p 00016000 fd:00 25670770                   /usr/lib64/libresolv-2.17.so
7fe053321000-7fe053322000 rw-p 00017000 fd:00 25670770                   /usr/lib64/libresolv-2.17.so
[..]
7fe053324000-7fe053328000 r-xp 00000000 fd:00 25259037                   /usr/lib64/libgpg-error.so.0.10.0
7fe053328000-7fe053527000 ---p 00004000 fd:00 25259037                   /usr/lib64/libgpg-error.so.0.10.0
7fe053527000-7fe053528000 r--p 00003000 fd:00 25259037                   /usr/lib64/libgpg-error.so.0.10.0
7fe053528000-7fe053529000 rw-p 00004000 fd:00 25259037                   /usr/lib64/libgpg-error.so.0.10.0
7fe053529000-7fe0535a6000 r-xp 00000000 fd:00 25258910                   /usr/lib64/libgcrypt.so.11.8.2
7fe0535a6000-7fe0537a5000 ---p 0007d000 fd:00 25258910                   /usr/lib64/libgcrypt.so.11.8.2
7fe0537a5000-7fe0537a6000 r--p 0007c000 fd:00 25258910                   /usr/lib64/libgcrypt.so.11.8.2
7fe0537a6000-7fe0537a9000 rw-p 0007d000 fd:00 25258910                   /usr/lib64/libgcrypt.so.11.8.2
[..]
7fe0537aa000-7fe0537b8000 r-xp 00000000 fd:00 25270982                   /usr/lib64/liblz4.so.1.8.3
7fe0537b8000-7fe0539b7000 ---p 0000e000 fd:00 25270982                   /usr/lib64/liblz4.so.1.8.3
7fe0539b7000-7fe0539b8000 r--p 0000d000 fd:00 25270982                   /usr/lib64/liblz4.so.1.8.3
7fe0539b8000-7fe0539b9000 rw-p 0000e000 fd:00 25270982                   /usr/lib64/liblz4.so.1.8.3
7fe0539b9000-7fe0539de000 r-xp 00000000 fd:00 25283566                   /usr/lib64/liblzma.so.5.2.2
7fe0539de000-7fe053bdd000 ---p 00025000 fd:00 25283566                   /usr/lib64/liblzma.so.5.2.2
7fe053bdd000-7fe053bde000 r--p 00024000 fd:00 25283566                   /usr/lib64/liblzma.so.5.2.2
7fe053bde000-7fe053bdf000 rw-p 00025000 fd:00 25283566                   /usr/lib64/liblzma.so.5.2.2
7fe053bdf000-7fe053c03000 r-xp 00000000 fd:00 25386544                   /usr/lib64/libselinux.so.1
7fe053c03000-7fe053e02000 ---p 00024000 fd:00 25386544                   /usr/lib64/libselinux.so.1
7fe053e02000-7fe053e03000 r--p 00023000 fd:00 25386544                   /usr/lib64/libselinux.so.1
7fe053e03000-7fe053e04000 rw-p 00024000 fd:00 25386544                   /usr/lib64/libselinux.so.1
[..]
7fe053e06000-7fe053e0a000 r-xp 00000000 fd:00 25258486                   /usr/lib64/libcap.so.2.22
7fe053e0a000-7fe054009000 ---p 00004000 fd:00 25258486                   /usr/lib64/libcap.so.2.22
7fe054009000-7fe05400a000 r--p 00003000 fd:00 25258486                   /usr/lib64/libcap.so.2.22
7fe05400a000-7fe05400b000 rw-p 00004000 fd:00 25258486                   /usr/lib64/libcap.so.2.22
7fe05400b000-7fe054020000 r-xp 00000000 fd:00 25258931                   /usr/lib64/libz.so.1.2.7
7fe054020000-7fe05421f000 ---p 00015000 fd:00 25258931                   /usr/lib64/libz.so.1.2.7
7fe05421f000-7fe054220000 r--p 00014000 fd:00 25258931                   /usr/lib64/libz.so.1.2.7
7fe054220000-7fe054221000 rw-p 00015000 fd:00 25258931                   /usr/lib64/libz.so.1.2.7
7fe054221000-7fe054252000 r-xp 00000000 fd:00 25540214                   /usr/lib64/libk5crypto.so.3.1
7fe054252000-7fe054451000 ---p 00031000 fd:00 25540214                   /usr/lib64/libk5crypto.so.3.1
7fe054451000-7fe054453000 r--p 00030000 fd:00 25540214                   /usr/lib64/libk5crypto.so.3.1
7fe054453000-7fe054454000 rw-p 00032000 fd:00 25540214                   /usr/lib64/libk5crypto.so.3.1
7fe054454000-7fe054457000 r-xp 00000000 fd:00 25258475                   /usr/lib64/libcom_err.so.2.1
7fe054457000-7fe054656000 ---p 00003000 fd:00 25258475                   /usr/lib64/libcom_err.so.2.1
7fe054656000-7fe054657000 r--p 00002000 fd:00 25258475                   /usr/lib64/libcom_err.so.2.1
7fe054657000-7fe054658000 rw-p 00003000 fd:00 25258475                   /usr/lib64/libcom_err.so.2.1
7fe054658000-7fe054731000 r-xp 00000000 fd:00 25540220                   /usr/lib64/libkrb5.so.3.3
7fe054731000-7fe054930000 ---p 000d9000 fd:00 25540220                   /usr/lib64/libkrb5.so.3.3
7fe054930000-7fe05493e000 r--p 000d8000 fd:00 25540220                   /usr/lib64/libkrb5.so.3.3
7fe05493e000-7fe054941000 rw-p 000e6000 fd:00 25540220                   /usr/lib64/libkrb5.so.3.3
7fe054941000-7fe05498b000 r-xp 00000000 fd:00 25177583                   /usr/lib64/libgssapi_krb5.so.2.2
7fe05498b000-7fe054b8b000 ---p 0004a000 fd:00 25177583                   /usr/lib64/libgssapi_krb5.so.2.2
7fe054b8b000-7fe054b8c000 r--p 0004a000 fd:00 25177583                   /usr/lib64/libgssapi_krb5.so.2.2
7fe054b8c000-7fe054b8e000 rw-p 0004b000 fd:00 25177583                   /usr/lib64/libgssapi_krb5.so.2.2
7fe054b8e000-7fe054cf2000 r-xp 00000000 fd:00 25944537                   /usr/lib64/libicuuc.so.50.2
7fe054cf2000-7fe054ef2000 ---p 00164000 fd:00 25944537                   /usr/lib64/libicuuc.so.50.2
7fe054ef2000-7fe054f02000 r--p 00164000 fd:00 25944537                   /usr/lib64/libicuuc.so.50.2
7fe054f02000-7fe054f03000 rw-p 00174000 fd:00 25944537                   /usr/lib64/libicuuc.so.50.2
[..]
7fe054f07000-7fe0550f7000 r-xp 00000000 fd:00 25923485                   /usr/lib64/libicui18n.so.50.2
7fe0550f7000-7fe0552f7000 ---p 001f0000 fd:00 25923485                   /usr/lib64/libicui18n.so.50.2
7fe0552f7000-7fe055303000 r--p 001f0000 fd:00 25923485                   /usr/lib64/libicui18n.so.50.2
7fe055303000-7fe055305000 rw-p 001fc000 fd:00 25923485                   /usr/lib64/libicui18n.so.50.2
[..]
7fe055306000-7fe0566d8000 r-xp 00000000 fd:00 25923483                   /usr/lib64/libicudata.so.50.2
7fe0566d8000-7fe0568d7000 ---p 013d2000 fd:00 25923483                   /usr/lib64/libicudata.so.50.2
7fe0568d7000-7fe0568d8000 r--p 013d1000 fd:00 25923483                   /usr/lib64/libicudata.so.50.2
7fe0568d8000-7fe0568d9000 rw-p 013d2000 fd:00 25923483                   /usr/lib64/libicudata.so.50.2
7fe0568d9000-7fe0568e0000 r-xp 00000000 fd:00 25555054                   /usr/lib64/librt-2.17.so
7fe0568e0000-7fe056adf000 ---p 00007000 fd:00 25555054                   /usr/lib64/librt-2.17.so
7fe056adf000-7fe056ae0000 r--p 00006000 fd:00 25555054                   /usr/lib64/librt-2.17.so
7fe056ae0000-7fe056ae1000 rw-p 00007000 fd:00 25555054                   /usr/lib64/librt-2.17.so
7fe056ae1000-7fe056ae9000 r-xp 00000000 fd:00 25657612                   /usr/lib64/libboost_chrono.so.1.69.0
7fe056ae9000-7fe056ce9000 ---p 00008000 fd:00 25657612                   /usr/lib64/libboost_chrono.so.1.69.0
7fe056ce9000-7fe056cea000 r--p 00008000 fd:00 25657612                   /usr/lib64/libboost_chrono.so.1.69.0
7fe056cea000-7fe056ceb000 rw-p 00009000 fd:00 25657612                   /usr/lib64/libboost_chrono.so.1.69.0
7fe056ceb000-7fe056eaf000 r-xp 00000000 fd:00 25260581                   /usr/lib64/libc-2.17.so
7fe056eaf000-7fe0570ae000 ---p 001c4000 fd:00 25260581                   /usr/lib64/libc-2.17.so
7fe0570ae000-7fe0570b2000 r--p 001c3000 fd:00 25260581                   /usr/lib64/libc-2.17.so
7fe0570b2000-7fe0570b4000 rw-p 001c7000 fd:00 25260581                   /usr/lib64/libc-2.17.so
[..]
7fe0570b9000-7fe0570d0000 r-xp 00000000 fd:00 25670687                   /usr/lib64/libpthread-2.17.so
7fe0570d0000-7fe0572cf000 ---p 00017000 fd:00 25670687                   /usr/lib64/libpthread-2.17.so
7fe0572cf000-7fe0572d0000 r--p 00016000 fd:00 25670687                   /usr/lib64/libpthread-2.17.so
7fe0572d0000-7fe0572d1000 rw-p 00017000 fd:00 25670687                   /usr/lib64/libpthread-2.17.so
[..]
7fe0572d5000-7fe0572ea000 r-xp 00000000 fd:00 27040953                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fe0572ea000-7fe0574e9000 ---p 00015000 fd:00 27040953                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fe0574e9000-7fe0574ea000 r--p 00014000 fd:00 27040953                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fe0574ea000-7fe0574eb000 rw-p 00015000 fd:00 27040953                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fe0574eb000-7fe0575ec000 r-xp 00000000 fd:00 25670397                   /usr/lib64/libm-2.17.so
7fe0575ec000-7fe0577eb000 ---p 00101000 fd:00 25670397                   /usr/lib64/libm-2.17.so
7fe0577eb000-7fe0577ec000 r--p 00100000 fd:00 25670397                   /usr/lib64/libm-2.17.so
7fe0577ec000-7fe0577ed000 rw-p 00101000 fd:00 25670397                   /usr/lib64/libm-2.17.so
7fe0577ed000-7fe0578d6000 r-xp 00000000 fd:00 25652730                   /usr/lib64/libstdc++.so.6.0.19
7fe0578d6000-7fe057ad6000 ---p 000e9000 fd:00 25652730                   /usr/lib64/libstdc++.so.6.0.19
7fe057ad6000-7fe057ade000 r--p 000e9000 fd:00 25652730                   /usr/lib64/libstdc++.so.6.0.19
7fe057ade000-7fe057ae0000 rw-p 000f1000 fd:00 25652730                   /usr/lib64/libstdc++.so.6.0.19
[..]
7fe057af5000-7fe057b1a000 r-xp 00000000 fd:00 25258760                   /usr/lib64/libtinfo.so.5.9
7fe057b1a000-7fe057d1a000 ---p 00025000 fd:00 25258760                   /usr/lib64/libtinfo.so.5.9
7fe057d1a000-7fe057d1e000 r--p 00025000 fd:00 25258760                   /usr/lib64/libtinfo.so.5.9
7fe057d1e000-7fe057d1f000 rw-p 00029000 fd:00 25258760                   /usr/lib64/libtinfo.so.5.9
7fe057d1f000-7fe057d54000 r-xp 00000000 fd:00 25261329                   /usr/lib64/libedit.so.0.0.42
7fe057d54000-7fe057f53000 ---p 00035000 fd:00 25261329                   /usr/lib64/libedit.so.0.0.42
7fe057f53000-7fe057f56000 r--p 00034000 fd:00 25261329                   /usr/lib64/libedit.so.0.0.42
7fe057f56000-7fe057f57000 rw-p 00037000 fd:00 25261329                   /usr/lib64/libedit.so.0.0.42
[..]
7fe057f5c000-7fe057f8b000 r-xp 00000000 fd:00 25259912                   /usr/lib64/libsystemd.so.0.6.0
7fe057f8b000-7fe05818b000 ---p 0002f000 fd:00 25259912                   /usr/lib64/libsystemd.so.0.6.0
7fe05818b000-7fe05818c000 r--p 0002f000 fd:00 25259912                   /usr/lib64/libsystemd.so.0.6.0
7fe05818c000-7fe05818d000 rw-p 00030000 fd:00 25259912                   /usr/lib64/libsystemd.so.0.6.0
7fe05818d000-7fe0583c4000 r-xp 00000000 fd:00 25177185                   /usr/lib64/libcrypto.so.1.0.2k
7fe0583c4000-7fe0585c3000 ---p 00237000 fd:00 25177185                   /usr/lib64/libcrypto.so.1.0.2k
7fe0585c3000-7fe0585df000 r--p 00236000 fd:00 25177185                   /usr/lib64/libcrypto.so.1.0.2k
7fe0585df000-7fe0585ec000 rw-p 00252000 fd:00 25177185                   /usr/lib64/libcrypto.so.1.0.2k
[..]
7fe0585f0000-7fe058657000 r-xp 00000000 fd:00 25627150                   /usr/lib64/libssl.so.1.0.2k
7fe058657000-7fe058857000 ---p 00067000 fd:00 25627150                   /usr/lib64/libssl.so.1.0.2k
7fe058857000-7fe05885b000 r--p 00067000 fd:00 25627150                   /usr/lib64/libssl.so.1.0.2k
7fe05885b000-7fe058862000 rw-p 0006b000 fd:00 25627150                   /usr/lib64/libssl.so.1.0.2k
7fe058862000-7fe05893a000 r-xp 00000000 fd:00 25678317                   /usr/lib64/libboost_regex.so.1.69.0
7fe05893a000-7fe058b3a000 ---p 000d8000 fd:00 25678317                   /usr/lib64/libboost_regex.so.1.69.0
7fe058b3a000-7fe058b3f000 r--p 000d8000 fd:00 25678317                   /usr/lib64/libboost_regex.so.1.69.0
7fe058b3f000-7fe058b41000 rw-p 000dd000 fd:00 25678317                   /usr/lib64/libboost_regex.so.1.69.0
7fe058b41000-7fe058bb1000 r-xp 00000000 fd:00 25678239                   /usr/lib64/libboost_program_options.so.1.69.0
7fe058bb1000-7fe058db0000 ---p 00070000 fd:00 25678239                   /usr/lib64/libboost_program_options.so.1.69.0
7fe058db0000-7fe058db6000 r--p 0006f000 fd:00 25678239                   /usr/lib64/libboost_program_options.so.1.69.0
7fe058db6000-7fe058db7000 rw-p 00075000 fd:00 25678239                   /usr/lib64/libboost_program_options.so.1.69.0
7fe058db7000-7fe058db8000 r-xp 00000000 fd:00 25554975                   /usr/lib64/libboost_system.so.1.69.0
7fe058db8000-7fe058fb7000 ---p 00001000 fd:00 25554975                   /usr/lib64/libboost_system.so.1.69.0
7fe058fb7000-7fe058fb8000 r--p 00000000 fd:00 25554975                   /usr/lib64/libboost_system.so.1.69.0
7fe058fb8000-7fe058fb9000 rw-p 00001000 fd:00 25554975                   /usr/lib64/libboost_system.so.1.69.0
7fe058fb9000-7fe058fd7000 r-xp 00000000 fd:00 25166980                   /usr/lib64/libboost_thread.so.1.69.0
7fe058fd7000-7fe0591d6000 ---p 0001e000 fd:00 25166980                   /usr/lib64/libboost_thread.so.1.69.0
7fe0591d6000-7fe0591d9000 r--p 0001d000 fd:00 25166980                   /usr/lib64/libboost_thread.so.1.69.0
7fe0591d9000-7fe0591da000 rw-p 00020000 fd:00 25166980                   /usr/lib64/libboost_thread.so.1.69.0
7fe0591da000-7fe0591f1000 r-xp 00000000 fd:00 25678238                   /usr/lib64/libboost_filesystem.so.1.69.0
7fe0591f1000-7fe0593f1000 ---p 00017000 fd:00 25678238                   /usr/lib64/libboost_filesystem.so.1.69.0
7fe0593f1000-7fe0593f2000 r--p 00017000 fd:00 25678238                   /usr/lib64/libboost_filesystem.so.1.69.0
7fe0593f2000-7fe0593f3000 rw-p 00018000 fd:00 25678238                   /usr/lib64/libboost_filesystem.so.1.69.0
7fe0593f3000-7fe059403000 r-xp 00000000 fd:00 25678322                   /usr/lib64/libboost_date_time.so.1.69.0
7fe059403000-7fe059603000 ---p 00010000 fd:00 25678322                   /usr/lib64/libboost_date_time.so.1.69.0
7fe059603000-7fe059604000 r--p 00010000 fd:00 25678322                   /usr/lib64/libboost_date_time.so.1.69.0
7fe059604000-7fe059605000 rw-p 00011000 fd:00 25678322                   /usr/lib64/libboost_date_time.so.1.69.0
7fe059605000-7fe05960c000 r-xp 00000000 fd:00 25669981                   /usr/lib64/libboost_coroutine.so.1.69.0
7fe05960c000-7fe05980c000 ---p 00007000 fd:00 25669981                   /usr/lib64/libboost_coroutine.so.1.69.0
7fe05980c000-7fe05980d000 r--p 00007000 fd:00 25669981                   /usr/lib64/libboost_coroutine.so.1.69.0
7fe05980d000-7fe05980e000 rw-p 00008000 fd:00 25669981                   /usr/lib64/libboost_coroutine.so.1.69.0
7fe05980e000-7fe059814000 r-xp 00000000 fd:00 25663427                   /usr/lib64/libboost_context.so.1.69.0
7fe059814000-7fe059a14000 ---p 00006000 fd:00 25663427                   /usr/lib64/libboost_context.so.1.69.0
7fe059a14000-7fe059a15000 r--p 00006000 fd:00 25663427                   /usr/lib64/libboost_context.so.1.69.0
7fe059a15000-7fe059a16000 rw-p 00007000 fd:00 25663427                   /usr/lib64/libboost_context.so.1.69.0
7fe059a16000-7fe059a18000 r-xp 00000000 fd:00 25518415                   /usr/lib64/libdl-2.17.so
7fe059a18000-7fe059c18000 ---p 00002000 fd:00 25518415                   /usr/lib64/libdl-2.17.so
7fe059c18000-7fe059c19000 r--p 00002000 fd:00 25518415                   /usr/lib64/libdl-2.17.so
7fe059c19000-7fe059c1a000 rw-p 00003000 fd:00 25518415                   /usr/lib64/libdl-2.17.so
7fe059c1a000-7fe059c3c000 r-xp 00000000 fd:00 25261284                   /usr/lib64/ld-2.17.so
[..]
7fe059e3b000-7fe059e3c000 r--p 00021000 fd:00 25261284                   /usr/lib64/ld-2.17.so
7fe059e3c000-7fe059e3d000 rw-p 00022000 fd:00 25261284                   /usr/lib64/ld-2.17.so
[..]
7ffe1d6b1000-7ffe1d6d2000 rw-p 00000000 00:00 0                          [stack]
7ffe1d742000-7ffe1d744000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Caught SIGABRT.
Current time: 2021-11-29 07:31:41 +0100
```

## To Reproduce

unknown so far. this crash has happened for the first time.

## Expected behavior

Icinga sould not die.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.11-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.45.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-507-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Operating System and version: 
`RHEL 7.9`
* Enabled features (`icinga2 feature list`):
```
Disabled features: command compatlog debuglog elasticsearch gelf livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker graphite ido-mysql influxdb mainlog notification
```
* Icinga Web 2 version and modules (System - About):
```

Icinga Web 2 Version
    2.7.5
Git Commit
    18996270b264976adf18d20da557d0c2806217c5
PHP Version
    7.1.8
Git Commit Datum
    2021-07-12
Copyright
    © 2013-2021 Das Icinga Projekt 
```
* Config validation (`icinga2 daemon -C`):

```
[2021-11-29 14:30:43 +0100] information/cli: Icinga application loader (version: 2.11.11-1)
[2021-11-29 14:30:43 +0100] information/cli: Loading configuration file(s).
[2021-11-29 14:30:46 +0100] information/ConfigItem: Committing config item(s).
[2021-11-29 14:30:47 +0100] information/ApiListener: My API identity: master02
[2021-11-29 14:30:56 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 56, rate: 84.9333/s (5096/min 5096/5min 5096/15min);
[2021-11-29 14:30:56 +0100] information/WorkQueue: #6 (InfluxdbWriter, influx01) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2021-11-29 14:30:56 +0100] information/WorkQueue: #5 (GraphiteWriter, graphite) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2021-11-29 14:30:56 +0100] information/WorkQueue: #7 (InfluxdbWriter, influx02) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2021-11-29 14:30:57 +0100] information/WorkQueue: #9 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2021-11-29 14:30:57 +0100] information/WorkQueue: #10 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 2 InfluxdbWriters.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 User.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 6 TimePeriods.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 6270 Zones.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 147157 Services.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 69 ScheduledDowntimes.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 196967 Notifications.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 NotificationCommand.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 41 Comments.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 6278 Endpoints.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 256 HostGroups.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 24949 Hosts.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 630 Downtimes.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 362 CheckCommands.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 9 ApiUsers.
[2021-11-29 14:31:21 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2021-11-29 14:31:21 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2021-11-29 14:31:21 +0100] information/cli: Finished validating the configuration file(s).
```

### PR DESCRIPTION
**Pull request by julianbrost**
There is no explicit synchronization of access to `m_DataBuffer` which is fine if it is only accessed from the single-threaded work queue. However, there were two exceptions which are fixed by this PR:
1. `Stop()` also called `Flush()` in another thread which modifies `m_DataBuffer`, this is fixed by also using the work queue.
2. `StatsFunc()`: called `m_DataBuffer.size()` which is unsafe if `m_DataBuffer` is modified concurrently. This is fixed by adding a new `std::atomic_size_t` to communicate the current size from the work queue to the stats function.

Other changes in this PR:
* `Flush()` is renamed to `FlushWQ()` to show that it should only be called from the work queue. Additionally, it now asserts that it is running on the work queue.
* Visibility of some data members is changed from protected to private. No other classes have to access these at the moment. By this change, accidental concurrent access from derived classes in the future is prevented.

### Tests

As this is supposed to fix a race-condition that's not easy to trigger reliably and there should be no other change in behavior, I just did some basic tests to confirm that (1) data is still written to InfluxDB and (2) `/v1/status` returns a plausible number for `data_buffer_items`.

fixes #9102

### CODE REVIEW

File: lib/perfdata/influxdbcommonwriter.cpp [hunk 1]
```diff
@@ -109,20 +109,13 @@ void InfluxdbCommonWriter::Pause()
...
 		<< "Flushing pending data buffers.";
 
-	Flush();
-
-	/* Work on the missing tasks. TODO: Find a way to cache them on disk. */
-	Log(LogDebug, GetReflectionType()->GetName())
-		<< "Joining existing WQ tasks.";
+	m_WorkQueue.Enqueue([this]() {
+		FlushWQ();
+	}, PriorityHigh);
```
Comment (Al2Klimov) [inline lib/perfdata/influxdbcommonwriter.cpp:114]: `PriorityHigh`? Are you sure? (Have a look how `RedisConnection#Sync()` is built.)

Comment (Al2Klimov) [inline lib/perfdata/influxdbcommonwriter.cpp:114]: Btw. all this on one line looks better IMAO.

File: lib/perfdata/influxdbcommonwriter.cpp [hunk 2]
```diff
@@ -109,20 +109,13 @@ void InfluxdbCommonWriter::Pause()
 	Log(LogDebug, GetReflectionType()->GetName())
 		<< "Flushing pending data buffers.";
 
-	Flush();
-
-	/* Work on the missing tasks. TODO: Find a way to cache them on disk. */
-	Log(LogDebug, GetReflectionType()->GetName())
-		<< "Joining existing WQ tasks.";
```
Comment (Al2Klimov) [inline lib/perfdata/influxdbcommonwriter.cpp:116]: Why? What’s the problem?

File: lib/perfdata/influxdbcommonwriter.hpp [hunk 3]
```diff
@@ -50,14 +48,17 @@ class InfluxdbCommonWriter : public ObjectImpl<InfluxdbCommonWriter>
 
 private:
 	Timer::Ptr m_FlushTimer;
+	WorkQueue m_WorkQueue{10000000, 1};
+	std::vector<String> m_DataBuffer;
+	std::atomic_size_t m_DataBufferSize;
```
Comment (Al2Klimov) [inline lib/perfdata/influxdbcommonwriter.hpp:53]: Huh? No deterministic init value? (Hint: `icinga::Atomic<T>`)

File: lib/perfdata/influxdbcommonwriter.hpp [hunk 4]
```diff
@@ -78,7 +79,7 @@ void InfluxdbCommonWriter::StatsFunc(const Dictionary::Ptr& status, const Array:
 	for (const typename InfluxWriter::Ptr& influxwriter : ConfigType::GetObjectsByType<InfluxWriter>()) {
 		size_t workQueueItems = influxwriter->m_WorkQueue.GetLength();
 		double workQueueItemRate = influxwriter->m_WorkQueue.GetTaskCount(60) / 60.0;
-		size_t dataBufferItems = influxwriter->m_DataBuffer.size();
+		size_t dataBufferItems = influxwriter->m_DataBufferSize;
```
Comment (Al2Klimov) [inline lib/perfdata/influxdbcommonwriter.hpp:82]: Btw. could this also be done by a high-prio WQ item?

**Review by Al2Klimov — CHANGES_REQUESTED** [review]

File: lib/perfdata/influxdbcommonwriter.hpp (hunk 4 above)
Comment (julianbrost) [reply lib/perfdata/influxdbcommonwriter.hpp:82]: Could be implemented that way but it would risk having to wait for at least the currently-running work queue job. This might be a flush, which does a TLS connection and might run into timeouts and so on.

File: lib/perfdata/influxdbcommonwriter.hpp (hunk 3 above)
Comment (julianbrost) [reply lib/perfdata/influxdbcommonwriter.hpp:53]: Indeed, that one isn't initialized properly. But I don't get why `icinga::Atomic` would improve anything compared to `std::atomic`.

File: lib/perfdata/influxdbcommonwriter.cpp (hunk 2 above)
Comment (julianbrost) [reply lib/perfdata/influxdbcommonwriter.cpp:116]: What do you mean? Why this message was removed? Because it would provide no meaningful information anymore compared to the one before. The wording could be integrated into the other message though.

File: lib/perfdata/influxdbcommonwriter.hpp (hunk 3 above)
Comment (Al2Klimov) [reply lib/perfdata/influxdbcommonwriter.hpp:53]: It has an atomic constructor in addition.

Comment (julianbrost) [reply lib/perfdata/influxdbcommonwriter.hpp:53]: What's an atomic constructor even supposed to do? If the code decides to construct the same object concurrently, I think that's the issue, not that a constructor wouldn't handle it (I'm not even sure if it would actually be possible to handle this correctly). If I understand https://en.cppreference.com/w/cpp/atomic/atomic/atomic correctly, if you use that default constructor of `std::atomic`, you'd actually have to call `std::atomic_init()` on it to initialize it properly which `icinga::Atomic` doesn't do.

Comment (Al2Klimov) [reply lib/perfdata/influxdbcommonwriter.hpp]: Rationale: call store() at construction time, i.e. before anyone else calls any other method, so that the instance is well initialised before usage. Doesn’t

```cpp
std::atomic<T> x;
x.store(y);
```

initialises x properly?

Comment (julianbrost) [reply lib/perfdata/influxdbcommonwriter.hpp]: See the "Notes" section on https://en.cppreference.com/w/cpp/atomic/atomic/atomic:

> The default-initialized `std::atomic<T>` does not contain a `T` object, and its only valid uses are destruction and initialization by `std::atomic_init`, see LWG 2334

So I think the call to `x.store(y);` is incorrect when strictly following the standard without calling `std::atomic_init(&x, 0);` first.

Comment (Al2Klimov) [reply lib/perfdata/influxdbcommonwriter.hpp]: But atomic_init "is not atomic" (https://en.cppreference.com/w/cpp/atomic/atomic_init). At least store() is.

Comment (julianbrost) [reply lib/perfdata/influxdbcommonwriter.hpp]: Why would you need this to be atomic in the first place? What should access the object concurrently while constructing it?

Comment (Al2Klimov) [reply lib/perfdata/influxdbcommonwriter.hpp]: I believe an atomic operation shall only follow an atomic operation, so Atomic<T> performs atomic construction.

Comment (Al2Klimov) [reply lib/perfdata/influxdbcommonwriter.hpp]: Also: why store() shouldn’t _just do it_?
