### PR TITLE
Fix null pointer dereferences when deleting objects while scheduling downtimes

### LINKED ISSUE #8583: icinga2 segfault
## Describe the bug

Hello,

last week our icinga-qs configmaster **(2.11.7)** died.
Just before the crash happened, a coleague of mine was testing with downtimes via api.

/var/log/messages
```
Dec 23 13:31:10 qs-master-01 kernel: [1782953.469945] icinga2[26370]: segfault at fffffffffffffff8 ip 00007f6e0463df7b sp 00007f6dfeb4a430 error 5 in libstdc++.so.6.0.19[7f6e0457f000+e9000]
Dec 23 13:31:10 qs-master-01 kernel: icinga2[26370]: segfault at fffffffffffffff8 ip 00007f6e0463df7b sp 00007f6dfeb4a430 error 5 in libstdc++.so.6.0.19[7f6e0457f000+e9000]
Dec 23 13:31:13 qs-master-01 systemd: icinga2.service: main process exited, code=exited, status=139/n/a
Dec 23 13:31:13 qs-master-01 systemd: Unit icinga2.service entered failed state.
Dec 23 13:31:13 qs-master-01 systemd: icinga2.service failed.
```

icinga2.log
```  
[2020-12-23 13:30:39 +0100] information/ApiListener: Replayed 1 messages.
[2020-12-23 13:30:39 +0100] information/ApiListener: Finished sending replay log for endpoint 'qs-master-02' in zone 'master'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Finished syncing endpoint 'qs-master-02' in zone 'master'.
[2020-12-23 13:30:39 +0100] information/IdoMysqlConnection: Pending queries: 122 (Input: 8/s; Output: 3/s)
[2020-12-23 13:30:39 +0100] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 2244, rate:  0/s (0/min 4327/5min 7626/15min); empty in 2 minutes and 48 seconds
[2020-12-23 13:30:39 +0100] information/ApiListener: Reconnecting to endpoint 'qs-master-02' via host 'x.x.x.x' and port '5665'
[2020-12-23 13:30:39 +0100] information/ApiListener: New client connection for identity 'qs-master-02' to [x.x.x.x]:5665
[2020-12-23 13:30:39 +0100] information/ApiListener: Sending config updates for endpoint 'qs-master-02' in zone 'master'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Finished reconnecting to endpoint 'qs-master-02' via host 'x.x.x.x' and port '5665'
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing configuration files for global zone 'global-templates' to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing configuration files for global zone 'windows-commands' to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing configuration files for zone 'zone-01' to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] warning/JsonRpcConnection: API client disconnected for identity 'qs-master-02'
[2020-12-23 13:30:39 +0100] warning/ApiListener: Removing API client for endpoint 'qs-master-02'. 0 API clients left.
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing configuration files for zone 'zone-02' to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing configuration files for zone 'master' to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing configuration files for global zone 'linux-commands' to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing configuration files for zone 'zone-03' to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Finished sending config file updates for endpoint 'qs-master-02' in zone 'master'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Syncing runtime objects to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Finished syncing runtime objects to endpoint 'qs-master-02'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Finished sending runtime config updates for endpoint 'qs-master-02' in zone 'master'.
[2020-12-23 13:30:39 +0100] information/ApiListener: Sending replay log for endpoint 'qs-master-02' in zone 'master'.
[2020-12-23 13:31:03 +0100] information/ApiListener: New client connection from [x.x.x.x]:44226 (no client certificate)
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: Request: GET /v1/objects/hosts/sn5ktest05 (from [x.x.x.x]:44226), user: api-user, agent: Mojolicious (Perl), status: OK).
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: HTTP client disconnected (from [x.x.x.x]:44226)
[2020-12-23 13:31:03 +0100] information/ApiListener: New client connection from [x.x.x.x]:44228 (no client certificate)
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!Interface Usage!service-notifcation-name' of type 'Notification'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!Interface Usage!2296b69e-a21e-4835-a9ec-d7adb28f1eb1' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!ping4!service-notifcation-name' of type 'Notification'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!Interface Usage' of type 'Service'.
[2020-12-23 13:31:03 +0100] information/Checkable: Checkable 'sn5ktest05!CPU' has 1 notification(s). Checking filters for type 'DowntimeEnd', sends will be logged.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!CPU!e0ae1a38-b5b3-4c1a-b1d9-7a16ff41f699' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!CPU!service-notifcation-name' of type 'Notification'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!CPU' of type 'Service'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!CPU!e0ae1a38-b5b3-4c1a-b1d9-7a16ff41f699' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!CPU!service-notifcation-name' of type 'Notification'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!ping4!4787bd5c-bad4-441d-9d70-24ba50581c4e' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!host-notifcation-name' of type 'Notification'.
[2020-12-23 13:31:03 +0100] information/Checkable: Checkable 'sn5ktest05' has 1 notification(s). Checking filters for type 'DowntimeEnd', sends will be logged.
[2020-12-23 13:31:03 +0100] information/Notification: Sending 'DowntimeEnd' notification 'sn5ktest05!downtime-name' for user 'qs-notification-user'
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!78a759b9-bc60-41ad-86fb-168687815c0a' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!downtime-name' of type 'Notification'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05!ping4' of type 'Service'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Deleted object 'sn5ktest05' of type 'Host'.
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: Request: DELETE /v1/objects/hosts/sn5ktest05 (from [x.x.x.x]:44228), user: api-user, agent: Mojolicious (Perl), status: OK).
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: HTTP client disconnected (from [x.x.x.x]:44228)
[2020-12-23 13:31:03 +0100] information/ApiListener: New client connection from [x.x.x.x]:44230 (no client certificate)
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Created and activated object 'sn5ktest05' of type 'Host'.
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: Request: PUT /v1/objects/hosts/sn5ktest05 (from [x.x.x.x]:44230), user: api-user, agent: Mojolicious (Perl), status: OK).
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: HTTP client disconnected (from [x.x.x.x]:44230)
[2020-12-23 13:31:03 +0100] information/ApiListener: New client connection from [x.x.x.x]:44236 (no client certificate)
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: Request: GET /v1/objects/hosts/sn5ktest05 (from [x.x.x.x]:44236), user: api-user, agent: Mojolicious (Perl), status: OK).
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: HTTP client disconnected (from [x.x.x.x]:44236)
[2020-12-23 13:31:03 +0100] information/ApiListener: New client connection from [x.x.x.x]:44238 (no client certificate)
[2020-12-23 13:31:03 +0100] information/Downtime: Triggering downtime 'sn5ktest05!67757328-4604-41ea-8405-601040d6ea7f' for checkable 'sn5ktest05'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Created and activated object 'sn5ktest05!67757328-4604-41ea-8405-601040d6ea7f' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/Downtime: Added downtime 'sn5ktest05!67757328-4604-41ea-8405-601040d6ea7f' between '2020-12-23 13:31:03' and '2025-12-23 13:31:03', author: 'icingaweb2-user', fixed
[2020-12-23 13:31:03 +0100] information/Downtime: Triggering downtime 'sn5ktest05!CPU!ce693194-aca4-40ba-8e78-826a7e602413' for checkable 'sn5ktest05!CPU'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Created and activated object 'sn5ktest05!CPU!ce693194-aca4-40ba-8e78-826a7e602413' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/Downtime: Added downtime 'sn5ktest05!CPU!ce693194-aca4-40ba-8e78-826a7e602413' between '2020-12-23 13:31:03' and '2025-12-23 13:31:03', author: 'icingaweb2-user', fixed
[2020-12-23 13:31:03 +0100] information/Downtime: Triggering downtime 'sn5ktest05!Interface Usage!cf5bbc30-0f92-43fe-b8fd-09a3da5a2994' for checkable 'sn5ktest05!Interface Usage'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Created and activated object 'sn5ktest05!Interface Usage!cf5bbc30-0f92-43fe-b8fd-09a3da5a2994' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/Downtime: Added downtime 'sn5ktest05!Interface Usage!cf5bbc30-0f92-43fe-b8fd-09a3da5a2994' between '2020-12-23 13:31:03' and '2025-12-23 13:31:03', author: 'icingaweb2-user', fixed
[2020-12-23 13:31:03 +0100] information/Downtime: Triggering downtime 'sn5ktest05!ping4!019cc082-a9b6-4fe4-a52a-0ea4a91f88ba' for checkable 'sn5ktest05!ping4'.
[2020-12-23 13:31:03 +0100] information/ConfigObjectUtility: Created and activated object 'sn5ktest05!ping4!019cc082-a9b6-4fe4-a52a-0ea4a91f88ba' of type 'Downtime'.
[2020-12-23 13:31:03 +0100] information/Downtime: Added downtime 'sn5ktest05!ping4!019cc082-a9b6-4fe4-a52a-0ea4a91f88ba' between '2020-12-23 13:31:03' and '2025-12-23 13:31:03', author: 'icingaweb2-user', fixed
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: Request: POST /v1/actions/schedule-downtime (from [x.x.x.x]:44238), user: api-user, agent: Mojolicious (Perl), status: OK).
[2020-12-23 13:31:03 +0100] information/HttpServerConnection: HTTP client disconnected (from [x.x.x.x]:44238)
[2020-12-23 13:31:10 +0100] information/ApiListener: Replayed 1 messages.
[2020-12-23 13:31:10 +0100] information/ApiListener: Finished sending replay log for endpoint 'qs-master-02' in zone 'master'.
[2020-12-23 13:31:10 +0100] information/ApiListener: Finished syncing endpoint 'qs-master-02' in zone 'master'.
```  

## To Reproduce

Unknown

## Expected behavior

Icinga should not die.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
`2.11.7`
* Operating System and version:
`RHEL 7.9`
* Enabled features (`icinga2 feature list`):
```
Disabled features: command compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb statusdata syslog
Enabled features: api checker graphite ido-mysql mainlog notification perfdata
```
* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
    2.7.4
Git Commit
    3ebfb5c38330d22966d24d2ace57d7eb3fb2a6db
PHP Version
    7.1.8
Git Commit Datum
    2020-08-17
Copyright
    © 2013-2021 Das Icinga Projekt 
```
* Config validation (`icinga2 daemon -C`):
```
[2021-01-04 10:10:40 +0100] information/cli: Icinga application loader (version: 2.11.7-1)
[2021-01-04 10:10:40 +0100] information/cli: Loading configuration file(s).
[2021-01-04 10:10:40 +0100] information/ConfigItem: Committing config item(s).
[2021-01-04 10:10:40 +0100] information/ApiListener: My API identity: qs-master-01
[2021-01-04 10:10:40 +0100] warning/ApplyRule: Apply rule 'Parent' (in /etc/icinga2/zones.d/global-templates/network.conf: 13:1-13:67) for type 'Dependency' does not match anywhere!
[2021-01-04 10:10:40 +0100] warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-templates/services.conf: 71:1-71:52) for type 'Service' does not match anywhere!
[2021-01-04 10:10:40 +0100] warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/global-templates/web.conf: 14:1-14:62) for type 'Service' does not match anywhere!
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 2 ScheduledDowntimes.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 37 HostGroups.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 NotificationCommand.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 284 Notifications.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 30 Hosts.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 16 Downtimes.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 9 Zones.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 9 Endpoints.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 5 ApiUsers.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 242 CheckCommands.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 3 TimePeriods.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 1 User.
[2021-01-04 10:10:40 +0100] information/ConfigItem: Instantiated 244 Services.
[2021-01-04 10:10:40 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2021-01-04 10:10:40 +0100] information/cli: Finished validating the configuration file(s).
```

### PR DESCRIPTION
**Pull request by julianbrost**
This pull requests fixes multiple null pointer dereferences that can occur if config objects are deleted while downtimes are scheduled. One affects scheduling service downtimes on hosts which are deleted in parallel, the others affect downtimes already being deleted while they are still in the progress of being deleted. Please see the individual commit messages for details.

fixes #8583

### CODE REVIEW

**Review by N-o-X — APPROVED** [review]

File: lib/icinga/downtime.cpp [hunk 1]
```diff
@@ -208,7 +206,7 @@ int Downtime::GetNextDowntimeID()
 	return l_NextDowntimeID;
 }
 
-String Downtime::AddDowntime(const Checkable::Ptr& checkable, const String& author,
+Downtime::Ptr Downtime::AddDowntime(const Checkable::Ptr &checkable, const String& author,
```
Comment (Al2Klimov) [inline lib/icinga/downtime.cpp:209]: `s/T& x/T &x/` is TBD and another construction area.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]

File: lib/icinga/downtime.cpp (hunk 1 above)
Comment (julianbrost) [reply lib/icinga/downtime.cpp]: Didn't want to start that discussion, I blame IDE auto-formatting :D

Comment (Al2Klimov) [reply lib/icinga/downtime.cpp]: Which IDE auto-formatting?

**Review by Al2Klimov — APPROVED** [review]

File: lib/icinga/downtime.cpp (hunk 1 above)
Comment (julianbrost) [reply lib/icinga/downtime.cpp]: Haven't bothered with configuring Icinga coding style in detail, so it still tends to attach `&` to the name instead of the type, this probably happened here as I undid some style changes and probably forgot this one.
