### PR TITLE
Fix update execution message discarded. refs #8616

### LINKED ISSUE #8616: ExecuteCommand API - Agent cannot update executions
## Describe the bug

We have the following setup:
* a master
* an agent that connects to the master and accepts configurations from the master
* a host with the same name of the agent endpoint

By sending an execute-command API request to the agent endpoint with this host as the checkable, the master discards the update execution message from the agent due to an "Unauthorized access" error. S

The error seems to originate from this line:
https://github.com/Icinga/icinga2/blob/dbdfe189c0bd3d006cd3adf6d85e3dfde9f409a4/lib/icinga/clusterevents.cpp#L1255

We notice that the logic for agents seems to be that the hostname should be equal to the endpoint name. We would thus propose an additional condition for host_name != command_endpoint

## To Reproduce

Master Configuration:

```
object Endpoint "master" {
}

object Zone "master" {
        endpoints = [ "master" ]
}


const NodeName = "master"

const ZoneName = "master"

object Endpoint "agent" {
    host = "172.17.0.3"
    log_duration = 0s
}

object Zone "agent" {
    parent = "master"
    endpoints = [ "agent" ]
}

object Host "agent" {
    import "myhost"

    address = "172.17.0.3"
}

template Host "myhost" {
    check_command = "hostalive"
}

object CheckCommand "cmdorchestrator_1_ls_tmp" {
    import "plugin-check-command"
    command = [ "ls", "/tmp/" ]
}
```

Agent configuration:

```
const NodeName = "agent"

const ZoneName = "agent"

object Endpoint "master" {
        host = "172.17.0.4"
        port = "5665"
}

object Zone "master" {
        endpoints = [ "master" ]
}

object Endpoint "agent" {
}

object Zone "agent" {
        endpoints = [ "agent" ]
        parent = "master"
}
```

Curl request:
```
curl -v -k -s -u root:<pwd> -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/actions/execute-command' -d '{"type":"Host", "host": "agent", "ttl":"15", "macros": {"command_endpoint": "agent"}, "command": "cmdorchestrator_1_ls_tmp", "command_type": "CheckCommand" }'
```
Curl response:
```
{"results":[{"checkable":"agent","code":202.0,"execution":"652687e2-a650-4989-91ac-6cafa45d2f6e","status":"Accepted"}]}
```
Execution status:
```
{
    "deadline": 1612261239.39249,
    "pending": true
}
```

Icinga master log:
```
[2021-02-02 10:00:20 +0000] information/ApiListener: New client connection from [127.0.0.1]:54710 (no client certificate)
[2021-02-02 10:00:20 +0000] notice/ApiListener: New HTTP client
[2021-02-02 10:00:20 +0000] information/HttpServerConnection: Request: POST /v1/actions/execute-command (from [127.0.0.1]:54710), user: root, agent: curl/7.29.0).
[2021-02-02 10:00:20 +0000] debug/HttpUtility: Request body: '{"type":"Host", "host": "agent", "ttl":"15", "macros": {"command_endpoint": "agent"}, "command": "cmdorchestrator_1_ls_tmp", "command_type": "CheckCommand" }'
[2021-02-02 10:00:20 +0000] notice/ApiActionHandler: Running action execute-command
[2021-02-02 10:00:20 +0000] notice/ApiListener: Relaying 'event::UpdateExecutions' message
[2021-02-02 10:00:20 +0000] notice/ApiListener: Relaying 'event::ExecuteCommand' message
[2021-02-02 10:00:20 +0000] notice/ApiListener: Sending message 'event::ExecuteCommand' to 'agent'
[2021-02-02 10:00:20 +0000] information/HttpServerConnection: HTTP client disconnected (from [127.0.0.1]:54710)
[2021-02-02 10:00:20 +0000] notice/JsonRpcConnection: Received 'event::ExecutedCommand' message from identity 'agent'.
[2021-02-02 10:00:20 +0000] notice/ClusterEvents: Discarding 'update executions API handler' message for checkable 'agent' from 'agent': Unauthorized access.
```

Icinga agent log:
```
[2021-02-02 10:51:29 +0000] notice/JsonRpcConnection: Received 'event::ExecuteCommand' message from identity 'master'.
[2021-02-02 10:51:29 +0000] notice/Process: Running command 'ls' '/tmp/': PID 33993
[2021-02-02 10:51:29 +0000] notice/Process: PID 33993 ('ls' '/tmp/') terminated with exit code 0
[2021-02-02 10:51:29 +0000] notice/ApiListener: Sending message 'event::ExecutedCommand' to 'master'
```

## Expected behavior

We expect that the agent can set successfully the execution.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): we used the rpms provided here: https://git.icinga.com/packaging/rpm-icinga2/-/pipelines/14188
* Operating System and version: CentOS Linux release 7.9.2009 (Core)
* Enabled features (`icinga2 feature list`): api checker debuglog ido-mysql influxdb livestatus mainlog notification
* Icinga Web 2 version and modules (System - About): icingaweb2-2.8.2_neteye1.82.1-1.el7.noarch
* Config validation (`icinga2 daemon -C`):
`
[2021-02-02 10:28:28 +0000] information/cli: Icinga application loader (version: r2.11.6-1)
[2021-02-02 10:28:28 +0000] information/cli: Loading configuration file(s).
[2021-02-02 10:28:29 +0000] information/ConfigItem: Committing config item(s).
[2021-02-02 10:28:29 +0000] information/ApiListener: My API identity: master
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 LivestatusListener.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 2 NotificationCommands.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 2 FileLoggers.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 2 Hosts.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 4 Zones.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 2 Endpoints.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 7 ApiUsers.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 239 CheckCommands.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2021-02-02 10:28:29 +0000] information/ConfigItem: Instantiated 1 Service.
[2021-02-02 10:28:29 +0000] information/ScriptGlobal: Dumping variables to file '/neteye/shared/icinga2/data/cache/icinga2/icinga2.vars'
[2021-02-02 10:28:29 +0000] information/cli: Finished validating the configuration file(s).
`
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

### PR DESCRIPTION
**Pull request by mcodato**
Hi, this is our proposal for fixes #8616

### Configuration for test

**/etc/icinga2/conf.d/test.conf**
Use this configuration on master, satellite and agent

```
object Host "satellite" {
    address = "127.0.0.1"
    check_command = "hostalive"
    zone = "satellite"
    vars.ls_dir = "/tmp/host"
    enable_active_checks = false
}

object Host "agent" {
    address = "127.0.0.1"
    check_command = "hostalive"
    zone = "satellite"
    vars.ls_dir = "/tmp/host"
    enable_active_checks = false
}

object Host "master" {
    address = "127.0.0.1"
    check_command = "hostalive"
}

object CheckCommand "custom_command" {
    command = [ "/usr/bin/ls", "$ls_dir$" ]
    zone = "global-commands"
}
```

## Master

**/etc/icinga2/zones.conf**

```
object Zone "global-commands" {
    global = true
}

object Zone "global-templates" {
    global = true
}

object Zone "director-global" {
    global = true
}

object Endpoint "master" {
}

object Zone "master" {
    endpoints = [ "master" ]
}

object Endpoint "satellite" {
}

object Zone "satellite" {
    endpoints = [ "satellite" ]
    parent = "master"
}

object Endpoint "agent" {
    log_duration = 0s
}

object Zone "agent" {
    endpoints = [ "agent" ]
    parent = "satellite"
}
```

## Satellite

**/etc/icinga2/zones.conf**

```
object Zone "global-commands" {
  global = true
}

object Zone "global-templates" {
    global = true
}

object Zone "director-global" {
    global = true
}

object Endpoint "master" {
    host = "127.0.0.1"
    port = "5665"
}

object Zone "master" {
    endpoints = [ "master" ]
}

object Endpoint "satellite" {
}

object Zone "satellite" {
    endpoints = [ "satellite" ]
    parent = "master"
}

object Endpoint "agent" {
    host = "127.0.0.1"
    port = "5663"
    log_duration = 0s
}

object Zone "agent" {
    endpoints = [ "agent" ]
    parent = "satellite"
}
```

## Agent

**/etc/icinga2/zones.conf**

```
object Zone "global-commands" {
    global = true
}

object Endpoint "satellite" {
    host = "127.0.0.1"
    port = "5664"
}

object Zone "satellite" {
    endpoints = [ "satellite" ]
}

object Endpoint "agent" {
}

object Zone "agent" {
    endpoints = [ "agent" ]
    parent = "satellite"
}

object Zone "global-templates" {
    global = true
}

object Zone "director-global" {
    global = true
}
```

## Test before the fix

**Request**
```
curl -k -sS -u root:admin -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/actions/execute-command' -d '{"type":"Host", "host": "agent", "ttl":"60", "endpoint": "agent", "macros": { "ls_dir":"/tmp/foo" }, "command": "custom_command", "command_type": "CheckCommand" }'
```

**Response**
```
{"results":[{"checkable":"agent","code":202.0,"execution":"beca0a2c-a99d-4804-90a3-9bd7e142b302","status":"Accepted"}]}
```

**Execution status**
```
"beca0a2c-a99d-4804-90a3-9bd7e142b302" = {
    deadline = 1612800769.001815
    pending = true
}
```
**Master logs**

```
[2021-02-08 17:11:49 +0100] notice/ApiListener: New HTTP client
[2021-02-08 17:11:49 +0100] debug/HttpUtility: Request body: '{"type":"Host", "host": "agent", "ttl":"60", "endpoint": "agent", "macros": { "ls_dir":"/tmp/foo" }, "command": "custom_command", "command_type": "CheckCommand" }'
[2021-02-08 17:11:49 +0100] notice/ApiActionHandler: Running action execute-command
[2021-02-08 17:11:49 +0100] notice/ApiListener: Relaying 'event::UpdateExecutions' message
[2021-02-08 17:11:49 +0100] notice/ApiListener: Sending message 'event::UpdateExecutions' to 'satellite'
[2021-02-08 17:11:49 +0100] notice/ApiListener: Relaying 'event::ExecuteCommand' message
[2021-02-08 17:11:49 +0100] notice/ApiListener: Sending message 'event::ExecuteCommand' to 'satellite'
>> {"jsonrpc":"2.0","method":"event::UpdateExecutions","params":{"executions":{"beca0a2c-a99d-4804-90a3-9bd7e142b302":{"deadline":1612800769.001815,"pending":true}},"host":"agent"},"ts":1612800709.00188}
[2021-02-08 17:11:49 +0100] information/HttpServerConnection: Request: POST /v1/actions/execute-command (from [::1]:37268), user: root, agent: curl/7.71.1, status: Accepted).
>> {"jsonrpc":"2.0","method":"event::ExecuteCommand","params":{"command":"custom_command","command_type":"check_command","deadline":1612800769.001815,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"beca0a2c-a99d-4804-90a3-9bd7e142b302"},"ts":1612800709.001983}
[2021-02-08 17:11:49 +0100] information/HttpServerConnection: HTTP client disconnected (from [::1]:37268)
```

**Satellite logs**

```
[2021-02-08 17:11:49 +0100] notice/JsonRpcConnection: Received 'event::UpdateExecutions' message from identity 'master'.
[2021-02-08 17:11:49 +0100] notice/ApiListener: Relaying 'event::UpdateExecutions' message
<< {"jsonrpc":"2.0","method":"event::ExecuteCommand","params":{"command":"custom_command","command_type":"check_command","deadline":1612800769.001815,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"beca0a2c-a99d-4804-90a3-9bd7e142b302"},"ts":1612800709.001983}
[2021-02-08 17:11:49 +0100] notice/JsonRpcConnection: Received 'event::ExecuteCommand' message from identity 'master'.
[2021-02-08 17:11:49 +0100] notice/ApiListener: Relaying 'event::ExecuteCommand' message
[2021-02-08 17:11:49 +0100] notice/ApiListener: Sending message 'event::ExecuteCommand' to 'agent'
>> {"jsonrpc":"2.0","method":"event::ExecuteCommand","originZone":"master","params":{"command":"custom_command","command_type":"check_command","deadline":1612800769.001815,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"beca0a2c-a99d-4804-90a3-9bd7e142b302"},"ts":1612800709.002931}
<< {"jsonrpc":"2.0","method":"event::ExecutedCommand","params":{"end":1612800709.006358,"execution":"beca0a2c-a99d-4804-90a3-9bd7e142b302","exit":2.0,"host":"agent","output":"/usr/bin/ls: cannot access '/tmp/foo': No such file or directory\n","start":1612800709.003923}}
[2021-02-08 17:11:49 +0100] notice/JsonRpcConnection: Received 'event::ExecutedCommand' message from identity 'agent'.
[2021-02-08 17:11:49 +0100] notice/ClusterEvents: Discarding 'update executions API handler' message for checkable 'agent' from 'agent': Unauthorized access.
```

**Agent logs**

```
[2021-02-08 17:11:49 +0100] notice/JsonRpcConnection: Received 'event::UpdateExecutions' message from identity 'master'.
[2021-02-08 17:11:49 +0100] notice/ApiListener: Relaying 'event::UpdateExecutions' message
<< {"jsonrpc":"2.0","method":"event::ExecuteCommand","params":{"command":"custom_command","command_type":"check_command","deadline":1612800769.001815,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"beca0a2c-a99d-4804-90a3-9bd7e142b302"},"ts":1612800709.001983}
[2021-02-08 17:11:49 +0100] notice/JsonRpcConnection: Received 'event::ExecuteCommand' message from identity 'master'.
[2021-02-08 17:11:49 +0100] notice/ApiListener: Relaying 'event::ExecuteCommand' message
[2021-02-08 17:11:49 +0100] notice/ApiListener: Sending message 'event::ExecuteCommand' to 'agent'
>> {"jsonrpc":"2.0","method":"event::ExecuteCommand","originZone":"master","params":{"command":"custom_command","command_type":"check_command","deadline":1612800769.001815,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"beca0a2c-a99d-4804-90a3-9bd7e142b302"},"ts":1612800709.002931}
<< {"jsonrpc":"2.0","method":"event::ExecutedCommand","params":{"end":1612800709.006358,"execution":"beca0a2c-a99d-4804-90a3-9bd7e142b302","exit":2.0,"host":"agent","output":"/usr/bin/ls: cannot access '/tmp/foo': No such file or directory\n","start":1612800709.003923}}
[2021-02-08 17:11:49 +0100] notice/JsonRpcConnection: Received 'event::ExecutedCommand' message from identity 'agent'.
[2021-02-08 17:11:49 +0100] notice/ClusterEvents: Discarding 'update executions API handler' message for checkable 'agent' from 'agent': Unauthorized access.
```

## Test with the fix

**Request**

```
curl -k -sS -u root:admin -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/actions/execute-command' -d '{"type":"Host", "host": "agent", "ttl":"60", "endpoint": "agent", "macros": { "ls_dir":"/tmp/foo" }, "command": "custom_command", "command_type": "CheckCommand" }'
```

**Response**
```
{"results":[{"checkable":"agent","code":202.0,"execution":"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e","status":"Accepted"}]}
```

**Exectuion status***
```
"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e" = {
		deadline = 1612801142.086969
		end = 1612801082.090901
		exit = 2.000000
		output = "/usr/bin/ls: cannot access '/tmp/foo': No such file or directory\n"
		start = 1612801082.088762
	}
```

**Master logs**

```
[2021-02-08 17:18:02 +0100] notice/ApiListener: New HTTP client
[2021-02-08 17:18:02 +0100] debug/HttpUtility: Request body: '{"type":"Host", "host": "agent", "ttl":"60", "endpoint": "agent", "macros": { "ls_dir":"/tmp/foo" }, "command": "custom_command", "command_type": "CheckCommand" }'
[2021-02-08 17:18:02 +0100] notice/ApiActionHandler: Running action execute-command
[2021-02-08 17:18:02 +0100] notice/ApiListener: Relaying 'event::UpdateExecutions' message
[2021-02-08 17:18:02 +0100] notice/ApiListener: Sending message 'event::UpdateExecutions' to 'satellite'
[2021-02-08 17:18:02 +0100] notice/ApiListener: Relaying 'event::ExecuteCommand' message
[2021-02-08 17:18:02 +0100] notice/ApiListener: Sending message 'event::ExecuteCommand' to 'satellite'
[2021-02-08 17:18:02 +0100] information/HttpServerConnection: Request: POST /v1/actions/execute-command (from [::1]:38370), user: root, agent: curl/7.71.1, status: Accepted).
>> {"jsonrpc":"2.0","method":"event::UpdateExecutions","params":{"executions":{"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e":{"deadline":1612801142.086969,"pending":true}},"host":"agent"},"ts":1612801082.087048}
>> {"jsonrpc":"2.0","method":"event::ExecuteCommand","params":{"command":"custom_command","command_type":"check_command","deadline":1612801142.086969,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e"},"ts":1612801082.087107}
[2021-02-08 17:18:02 +0100] information/HttpServerConnection: HTTP client disconnected (from [::1]:38370)
<< {"jsonrpc":"2.0","method":"event::UpdateExecutions","params":{"executions":{"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e":{"deadline":1612801142.086969,"end":1612801082.090901,"exit":2.0,"output":"/usr/bin/ls: cannot access '/tmp/foo': No such file or directory\n","start":1612801082.088762}},"host":"agent"},"ts":1612801082.091564}
[2021-02-08 17:18:02 +0100] notice/JsonRpcConnection: Received 'event::UpdateExecutions' message from identity 'satellite'.
[2021-02-08 17:18:02 +0100] notice/ApiListener: Relaying 'event::UpdateExecutions' message
```

**Satellite logs**

```
<< {"jsonrpc":"2.0","method":"event::UpdateExecutions","params":{"executions":{"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e":{"deadline":1612801142.086969,"pending":true}},"host":"agent"},"ts":1612801082.087048}
[2021-02-08 17:18:02 +0100] notice/JsonRpcConnection: Received 'event::UpdateExecutions' message from identity 'master'.
[2021-02-08 17:18:02 +0100] notice/ApiListener: Relaying 'event::UpdateExecutions' message
<< {"jsonrpc":"2.0","method":"event::ExecuteCommand","params":{"command":"custom_command","command_type":"check_command","deadline":1612801142.086969,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e"},"ts":1612801082.087107}
[2021-02-08 17:18:02 +0100] notice/JsonRpcConnection: Received 'event::ExecuteCommand' message from identity 'master'.
[2021-02-08 17:18:02 +0100] notice/ApiListener: Relaying 'event::ExecuteCommand' message
[2021-02-08 17:18:02 +0100] notice/ApiListener: Sending message 'event::ExecuteCommand' to 'agent'
>> {"jsonrpc":"2.0","method":"event::ExecuteCommand","originZone":"master","params":{"command":"custom_command","command_type":"check_command","deadline":1612801142.086969,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e"},"ts":1612801082.087914}
<< {"jsonrpc":"2.0","method":"event::ExecutedCommand","params":{"end":1612801082.090901,"execution":"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e","exit":2.0,"host":"agent","output":"/usr/bin/ls: cannot access '/tmp/foo': No such file or directory\n","start":1612801082.088762}}
[2021-02-08 17:18:02 +0100] notice/JsonRpcConnection: Received 'event::ExecutedCommand' message from identity 'agent'.
[2021-02-08 17:18:02 +0100] notice/ApiListener: Relaying 'event::UpdateExecutions' message
[2021-02-08 17:18:02 +0100] notice/ApiListener: Sending message 'event::UpdateExecutions' to 'master'
>> {"jsonrpc":"2.0","method":"event::UpdateExecutions","params":{"executions":{"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e":{"deadline":1612801142.086969,"end":1612801082.090901,"exit":2.0,"output":"/usr/bin/ls: cannot access '/tmp/foo': No such file or directory\n","start":1612801082.088762}},"host":"agent"},"ts":1612801082.091564}
```

**Aagent logs**

```
<< {"jsonrpc":"2.0","method":"event::ExecuteCommand","originZone":"master","params":{"command":"custom_command","command_type":"check_command","deadline":1612801142.086969,"endpoint":"agent","host":"agent","macros":{"ls_dir":"/tmp/foo"},"source":"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e"},"ts":1612801082.087914}
[2021-02-08 17:18:02 +0100] notice/JsonRpcConnection: Received 'event::ExecuteCommand' message from identity 'satellite'.
[2021-02-08 17:18:02 +0100] notice/Process: Running command '/usr/bin/ls' '/tmp/foo': PID 1367365
[2021-02-08 17:18:02 +0100] notice/Process: PID 1367365 ('/usr/bin/ls' '/tmp/foo') terminated with exit code 2
[2021-02-08 17:18:02 +0100] notice/ApiListener: Sending message 'event::ExecutedCommand' to 'satellite'
>> {"jsonrpc":"2.0","method":"event::ExecutedCommand","params":{"end":1612801082.090901,"execution":"ce72a2a5-6237-41fe-a21b-a896d2fa1c5e","exit":2.0,"host":"agent","output":"/usr/bin/ls: cannot access '/tmp/foo': No such file or directory\n","start":1612801082.088762}}
```

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Colleagues, any security objections?

File: lib/icinga/clusterevents.cpp [hunk 1]
```diff
@@ -1252,7 +1253,8 @@ Value ClusterEvents::UpdateExecutionsAPIHandler(const MessageOrigin::Ptr& origin
 
 	ObjectLock oLock (checkable);
 
-	if (origin->FromZone && !origin->FromZone->CanAccessObject(checkable)) {
+	if (origin->FromZone && !origin->FromZone->CanAccessObject(checkable) &&
+		endpoint->GetName() != host->GetName()) {
```
Comment (julianbrost) [inline lib/icinga/clusterevents.cpp:1257]: `endpoint` is obtained by `origin->FromClient->GetEndpoint()`, i.e. the client from which the current node received the cluster message. In case the message is relayed by a satellite, this is not the node from which the message originated but the one that relayed it.

**Review by julianbrost — CHANGES_REQUESTED** [review]
Let me try to summarize to see if I understand correctly:

In order to schedule the execute a command on another node, this command has to be sent from a parent node to be accepted. This command references some config object which is then asynchronously updated with the result. However, this update performs a different permission check: the object must be accessible from the zone that sends the update. You can execute the command on any object though.

So a possible workaround should be to create a dummy host/service that is in the zone of the endpoint executing the command.

This PR would now introduce a new relationship between endpoint and host objects if they share the same name, allowing this update nonetheless. An alternative to this could probably be to store the command endpoint with the pending execution result and use this for update permission checks.

**Comment by mcodato** [comment]
Hi @julianbrost, thanks for your feedback, we like the idea of storing the command endpoint in the execution object and we have implemented it. It can be tested with the same test above.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Please squash your commits.

File: lib/icinga/clusterevents.cpp [hunk 2]
```diff
@@ -1188,6 +1181,14 @@ Value ClusterEvents::ExecutedCommandAPIHandler(const MessageOrigin::Ptr& origin,
 		return Empty;
 	}
 
+	if (origin->FromZone && !origin->FromZone->CanAccessObject(checkable) &&
+		endpoint->GetName() != execution->Get("endpoint")) {
```
Comment (julianbrost) [inline lib/icinga/clusterevents.cpp:1185]: This still has the issue that it won't work with additional satellites in between. Unfortunately the naming is a bit misleading: `origin->FromClient->GetEndpoint()` isn't the endpoint on which the message originated but the one from which the current node received it.

Without having tested this: I think `!origin->FromZone->CanAccessObject(Endpoint::GetByName(execution->Get("endpoint")))` (+ additional checks to ensure that the endpoint (still) exists) should do the trick. This should then also make the check for `!origin->FromZone->CanAccessObject(checkable)` obsolete.

**Review by julianbrost — CHANGES_REQUESTED** [review]

**Comment by julianbrost** [comment]
Seems like I've overlooked something when suggesting to change the permission check in this way: The permission check would be fine, but the object on which the execution is updated won't exist on intermediate satellites, so this won't help. This would be a general problem when decoupling the execution endpoint from the object's zone completely.

Endpoint names in the following examples refer to this cluster structure:
```
       m
      / \
     /   \
    /     \
  s-1     s-2
   |       |
   |       |
  a-1    s-2-1
           |
           |
          a-2
```

So in the most extreme case, the API would currently accept a command for the host object `a-1` which is in zone `s-1` (so `a-1` is a command endpoint) to be executed on endpoint `a-2`. Executing this should be fine, however the result would never make it back as `s-2` and `s-2-1` don't know about the `a-1` host object at all. The same would also happen if the object was in zone `m` or `s-2`, then `s-2-1` still wouldn't be aware of it.

This could be fixed but would need major changes in how the results are returned (would have to be forwarded up the cluster without relying on any local objects). But I think this isn't even a use-case that you'd need but you only have this discrepancy in the object's zone because you're using the command endpoint feature.

So I see two possibilities how this could be fixed without completely overthrowing how the feature works:
1. Restricting the `endpoint` parameter of the `/v1/actions/execute-command` API to those values, where we could currently execute and retrieve the result. That is the object's zone, all its parent zones and any direct child of a aforementioned zone. In this example, for an object in zone `s-2-1`, checks could be executed on `m`, `s-2`, `s-2-1`, `a-2` and `s-1` (but **not** `a-1`). For me this feels like a quite arbitrary restriction from a user's perspective.
2. Removing the `endpoint` parameter from the `/v1/actions/execute-command` API and always using the `command_endpoint`, i.e. the current default. This would mean that the check is always executed where it would be if it was scheduled normally. This sounds like a reasonable restriction to me, but there's one caveat: if `command_endpoint` is only used for services but not the host itself, for example to perform a ping check from the satellite, executing on the host object would also execute the command on the satellite and you'd have to execute on a service object to execute on the actual host.

So please let me know what you think about this and which options would fit your needs so that we can figure out together how to proceed.

**Comment by mcodato** [comment]
Hi @julianbrost sorry for the delay,
We believe the first proposal is the most appropriate for our use case.
We have implemented it, please let us know if this is correct

**Review by julianbrost — CHANGES_REQUESTED** [review]
> Hi @julianbrost sorry for the delay,

Well, I think I can't complain about that and have to say sorry for the delayed review myself.

**Comment by julianbrost** [comment]
@cla-bot check

File: lib/icinga/apiactions.cpp [hunk 3]
```diff
@@ -890,6 +891,27 @@ Dictionary::Ptr ApiActions::ExecuteCommand(const ConfigObject::Ptr& object, cons
 						return ApiActions::CreateResult(202, "Accepted", result);
 					}
 				}
+
+				/* Check if the child zone can access the checkable */
+				if (!zone->CanAccessObject(checkable)) {
```
[the remark this answers is not in the document]
Comment (w1ll-i-code) [reply lib/icinga/apiactions.cpp:896]: I think it's always better to give the caller immediately a HTTP error. This allows for easier error handling.

**Comment by Al2Klimov** [comment]
C'mon Julian, you've even not resolved your threads not to mention not approved.

File: lib/icinga/apiactions.cpp [hunk 4]
```diff
@@ -890,6 +891,32 @@ Dictionary::Ptr ApiActions::ExecuteCommand(const ConfigObject::Ptr& object, cons
...
```
Comment (julianbrost) [inline lib/icinga/apiactions.cpp:896]: This only checks if the direct child zone can access the object. But the hierarchy is known so it should be possible to check earlier if the zone of `endpointPtr` can access `checkable`. This could also make other checks redundant.

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/icinga/apiactions.cpp [hunk 5]
```diff
@@ -890,6 +891,32 @@ Dictionary::Ptr ApiActions::ExecuteCommand(const ConfigObject::Ptr& object, cons
...
+					/* Update execution */
+					double now = Utility::GetTime();
+					pending_execution->Set("exit", 126);
+					pending_execution->Set(
+						"output",
+						"Zone '" + zone->GetName() + "' cannot access to checkable '" + checkable->GetName() + "'."
+					);
+					pending_execution->Set("start", now);
+					pending_execution->Set("end", now);
+					pending_execution->Remove("pending");
```
[the remark this answers is not in the document]
Comment (julianbrost) [reply lib/icinga/apiactions.cpp]: In combination with https://github.com/Icinga/icinga2/pull/8627#discussion_r1094764155, it should be possible to perform this check earlier. And if that check fails, the API request can just be refused before adding an execution, like it's already done if the command doesn't exist.

[the remark this answers is not in the document]
Comment (mcodato) [reply lib/icinga/apiactions.cpp]: Got it and applied, thank you

**Review by Al2Klimov — DISMISSED** [review]
Describe the big picture. Then vs. now. At best with diagrams. The can be hand drawn and photographed if you don't wanna deal with digital tools.

**Comment by Al2Klimov** [comment]
Also consider splitting your commit into multiple ones which successively lead from then to now. E.g. see commits here:

* https://github.com/Icinga/icingadb-web/pull/721

File: lib/icinga/apiactions.cpp [hunk 6]
```diff
@@ -681,6 +681,15 @@ Dictionary::Ptr ApiActions::ExecuteCommand(const ConfigObject::Ptr& object, cons
 	if (!endpointPtr)
 		return ApiActions::CreateResult(404, "Can't find a valid endpoint for '" + resolved_endpoint + "'.");
 
+    /* Check if the endpoint zone can access the checkable */
+    Zone::Ptr endpointZone = endpointPtr->GetZone();
+    if (!endpointZone->CanAccessObject(checkable)) {
```
Comment (julianbrost) [inline lib/icinga/apiactions.cpp:686]: This check prevents executing commands for checkables with `command_endpoint` in a child zone on that agent. So for example with `agent-1!hostname` having `zone = "master"` and `command_endpoint = "agent-1"` where that agent-1 is a direct child of the master zone, this results in the following error:

```console
$ curl -sSku root:icinga https://localhost:5665/v1/actions/execute-command --json '{"type": "Service", "service": "agent-1!hostname", "ttl": 15, "macros": {"command_endpoint": "agent-1"}, "command": "hostname", "command_type": "CheckCommand", "pretty": true}'
{
    "results": [
        {
            "code": 409,
            "status": "Zone 'agent-1' cannot access checkable 'agent-1!hostname'."
        }
    ]
}
```

So the check should probably be whether the parent zone of `endpointZone` (if it exists, otherwise that zone itself) can access `checkable` to allow for that situation.

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/icinga/clusterevents.cpp [hunk 7]
```diff
@@ -1213,6 +1267,22 @@ Value ClusterEvents::ExecutedCommandAPIHandler(const MessageOrigin::Ptr& origin,
...
+	Endpoint::Ptr command_endpoint = Endpoint::GetByName(execution->Get("endpoint"));
+	if (!command_endpoint) {
+		Log(LogNotice, "ClusterEvents")
+			<< "Discarding 'update executions API handler' message from '" << origin->FromClient->GetIdentity()
+			<< "': Command endpoint does not exists.";
+
+		return Empty;
+	}
+
+	if (origin->FromZone && !origin->FromZone->CanAccessObject(command_endpoint->GetZone())) {
```
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:1279]: Apropos, I consider zoneA->CanAccessObject(zoneB) kinda confusing. Doesn’t this -according to CanAccessObject() code- query for a child/parent relationship?

File: lib/icinga/apiactions.cpp (hunk 6 above)
Comment (mcodato) [reply lib/icinga/apiactions.cpp:686]: Hi @julianbrost, since I'm not able to reproduce the problem may I ask you to confirm if the following configuration is the one that you used for the test or if you can provide me the correct one? Thank you

master zones.conf
```
object Endpoint "master" {
}

object Zone "master" {
    endpoints = [ "master", "agent-1" ]
}

object Endpoint "agent-1" {
    host = "127.0.0.1"
    port = "5662"
}
```

master.conf
```
object Host "master" {
    address = "127.0.0.1"
    check_command = "hostalive"
}

object Host "agent-1" {
    address = "127.0.0.1"
    check_command = "hostalive"
    zone = "master"
    enable_active_checks = false
}

object Service "hostname" {
    host_name = "agent-1"
    check_command = "ping"
}
```

agent-1 zones.conf
```
object Endpoint "master" {
    host = "127.0.0.1"
    port = "5665"
}

object Zone "master" {
    endpoints = [ "master", "agent-1" ]
}

object Endpoint "agent-1" {
}
```
agent-1.conf
```
object Host "agent-1" {
    address = "127.0.0.1"
    check_command = "hostalive"
    zone = "master"
    enable_active_checks = false
}

object Service "hostname" {
    host_name = "agent-1"
    check_command = "ping"
}
```

Comment (julianbrost) [reply lib/icinga/apiactions.cpp:686]: > object Zone "master" {
>     endpoints = [ "master", "agent-1" ]
> }

The agent-1 Endpoint object has to be in its own zone. That config above would be for an HA master zone.

So more like this:

master `zones.conf`:
```
object Endpoint "master" {
}

object Zone "master" {
    endpoints = [ "master" ]
}

object Endpoint "agent-1" {
    host = "127.0.0.1"
    port = "5662"
}

object Zone "agent-1" {
    parent = "master"
    endpoints = [ "agent-1" ]
}
```

master `zones.d/master/agent-1.conf`:
```
object Host "agent-1" {
    address = "127.0.0.1"
    check_command = "hostalive"
    enable_active_checks = false
}

object Service "hostname" {
    host_name = "agent-1"
    check_command = "ping"
    command_endpoint = "agent-1"
}
```

agent-1 `zones.conf`:
```
object Endpoint "master" {
    host = "127.0.0.1"
    port = "5665"
}

object Zone "master" {
    endpoints = [ "master" ]
}

object Endpoint "agent-1" {
}

object Zone "agent-1" {
    parent = "master"
    endpoints = [ "agent-1" ]
}
```

And no additional Host/Service objects for `agent-1!hostname` on the agent, due to `command_endpoint = "agent-1"` they don't have to be present there.

File: lib/icinga/clusterevents.cpp (hunk 7 above)
Comment (Al2Klimov) [reply lib/icinga/clusterevents.cpp:1279]: If this is what you wanna check for, yes. IMAO it's more descriptive. But let's Julian cross-check first..

File: lib/icinga/apiactions.cpp (hunk 6 above)
Comment (mcodato) [reply lib/icinga/apiactions.cpp:686]: I did some testing and it seems that using the parent zone with the following configuration:
```
       m
      / \
     /   \
    /     \
  s-1     s-2  
```
it's possible to execute a command with checkable `s-1` in the `s-2` endpoint because the master zone can access `s-2`

I suggest checking if the endpointZone can access the checkable only when the endpoint where I want to execute the command is different than the command endpoint of the checkable, so with a check like the following one

```
    Zone::Ptr endpointZone = endpointPtr->GetZone();
    Endpoint::Ptr commandEndpoint = checkable->GetCommandEndpoint();
    if (endpointPtr != commandEndpoint && !endpointZone->CanAccessObject(checkable)) {
```

What do you think?

Comment (julianbrost) [reply lib/icinga/apiactions.cpp:686]: > it's possible to execute a command with checkable `s-1` in the `s-2` endpoint because the master zone can access `s-2`

That doesn't come as a surprise so me, that's a simpler scenario of one what I described in https://github.com/Icinga/icinga2/pull/8627#issuecomment-780581632:

> 1. Restricting the `endpoint` parameter of the `/v1/actions/execute-command` API to those values, where we could currently execute and retrieve the result. That is the object's zone, all its parent zones and any direct child of a aforementioned zone. In this example, for an object in zone `s-2-1`, checks could be executed on `m`, `s-2`, `s-2-1`, `a-2` and `s-1` (but **not** `a-1`). For me this feels like a quite arbitrary restriction from a user's perspective.

Last sentence is still true, so yes, that's a bit strange. But it's not a huge problem, `s-2` can't impersonate `s-1`, it can only update an execution on `s-1` if that execution was sent to `s-2`, which is somewhat of a strange input in the first place.

> ```
>     Zone::Ptr endpointZone = endpointPtr->GetZone();
>     Endpoint::Ptr commandEndpoint = checkable->GetCommandEndpoint();
>     if (endpointPtr != commandEndpoint && !endpointZone->CanAccessObject(checkable)) {
> ```

So with this change compared to the current state of the PR, it would additionally accept the command in the very specific `command_endpoint` case. Sounds reasonable, so if that works, go ahead.

**Review by julianbrost — APPROVED** [review]
LGTM now.

@Al2Klimov Do you want to have another look at this before merging? The change is basically [storing the execution endpoint in the slot for the result](https://github.com/Icinga/icinga2/pull/8627#issuecomment-779265321) (where the deadline is already stored for example) and then changes to the message forwarding and related permission checks to actually make it work.

File: lib/icinga/apiactions.cpp [hunk 8]
```diff
@@ -681,6 +681,21 @@ Dictionary::Ptr ApiActions::ExecuteCommand(const ConfigObject::Ptr& object, cons
...
+	 */
+    Zone::Ptr endpointZone = endpointPtr->GetZone();
+    Endpoint::Ptr commandEndpoint = checkable->GetCommandEndpoint();
+    if (endpointPtr != commandEndpoint && !endpointZone->CanAccessObject(checkable)) {
+        return ApiActions::CreateResult(
+            409,
+            "Zone '" + endpointZone->GetName() + "' cannot access checkable '" + checkable->GetName() + "'."
+        );
+    }
+
```
Comment (Al2Klimov) [inline lib/icinga/apiactions.cpp:698]: OK this makes sense to me...

File: lib/icinga/clusterevents.cpp [hunk 9]
```diff
@@ -761,9 +761,18 @@ Value ClusterEvents::ExecuteCommandAPIHandler(const MessageOrigin::Ptr& origin,
...
 	if (params->Contains("endpoint")) {
 		Endpoint::Ptr execEndpoint = Endpoint::GetByName(params->Get("endpoint"));
 
+		if (!execEndpoint) {
+			Log(LogWarning, "ClusterEvents")
+				<< "Discarding 'execute command' message " << executionUuid
+				<< ": Endpoint " << params->Get("endpoint") << " does not exist";
+			return Empty;
+		}
+
```
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:775]: So far so good...

File: lib/icinga/clusterevents.cpp [hunk 10]
```diff
@@ -1303,7 +1377,7 @@ Value ClusterEvents::UpdateExecutionsAPIHandler(const MessageOrigin::Ptr& origin
 	updateMessage->Set("method", "event::UpdateExecutions");
 	updateMessage->Set("params", params);
 
-	listener->RelayMessage(origin, Zone::GetLocalZone(), updateMessage, true);
+	listener->RelayMessage(origin, checkable, updateMessage, true);
```
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:1380]: LGTM

File: lib/icinga/clusterevents.cpp [hunk 11]
```diff
@@ -1213,6 +1271,22 @@ Value ClusterEvents::ExecutedCommandAPIHandler(const MessageOrigin::Ptr& origin,
...
+	Endpoint::Ptr command_endpoint = Endpoint::GetByName(execution->Get("endpoint"));
+	if (!command_endpoint) {
+		Log(LogNotice, "ClusterEvents")
+			<< "Discarding 'update executions API handler' message from '" << origin->FromClient->GetIdentity()
+			<< "': Command endpoint does not exists.";
+
+		return Empty;
+	}
+
+	if (origin->FromZone && !command_endpoint->GetZone()->IsChildOf(origin->FromZone)) {
```
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:1283]: The only problem I see are messages from the own zone, but then -I guess- !!origin->FromZone wouldn’t be true. (JsonRpcConnection::MessageHandler())

File: lib/icinga/clusterevents.cpp [hunk 12]
```diff
@@ -803,6 +812,62 @@ Value ClusterEvents::ExecuteCommandAPIHandler(const MessageOrigin::Ptr& origin,
...
+						);
+						executedParams->Set("start", now);
+						executedParams->Set("end", now);
+
+						Dictionary::Ptr executedMessage = new Dictionary();
+						executedMessage->Set("jsonrpc", "2.0");
+						executedMessage->Set("method", "event::ExecutedCommand");
+						executedMessage->Set("params", executedParams);
+
+						listener->RelayMessage(nullptr, nullptr, executedMessage, true);
```
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:868]: Huh? nullptr, nullptr? Not...

File: lib/icinga/clusterevents.cpp (hunk 10 above)
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:1380]: ... origin, checkable? Not even origin? Please explain.

File: lib/icinga/clusterevents.cpp [hunk 13]
```diff
@@ -803,6 +812,62 @@ Value ClusterEvents::ExecuteCommandAPIHandler(const MessageOrigin::Ptr& origin,
 							return Empty;
 						}
 					}
+
+					Checkable::Ptr checkable;
+					Host::Ptr host = Host::GetByName(params->Get("host"));
+					if (!host) {
+						Log(LogWarning, "ClusterEvents")
+                            << "Discarding 'execute command' message " << executionUuid
```
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:820]: A bit of indentation...

File: lib/icinga/clusterevents.cpp [hunk 14]
```diff
@@ -803,6 +812,62 @@ Value ClusterEvents::ExecuteCommandAPIHandler(const MessageOrigin::Ptr& origin,
...
+					else
+						checkable = host;
+
+					if (!checkable) {
+						String checkableName = host->GetName();
+						if (params->Contains("service"))
+							checkableName += "!" + params->Get("service");
+
+						Log(LogWarning, "ClusterEvents")
+                            << "Discarding 'execute command' message " << executionUuid
```
Comment (Al2Klimov) [inline lib/icinga/clusterevents.cpp:836]: ... wouldn’t hurt.

File: lib/icinga/clusterevents.cpp (hunk 12 above)
Comment (julianbrost) [reply lib/icinga/clusterevents.cpp:868]: To be honest, I haven't put much thought into these parameters here as the existing `event::ExecutedCommand` message already used the same ones.

However, are you sure about origin? This is sending a response that originates here, so with the origin of the incoming message, that might prevent the response from being sent back.

Comment (mcodato) [reply lib/icinga/clusterevents.cpp:868]: From what I tested, I agree with Julian, using `origin, checkable` the message is not sent back and the execution remains in the pending state
```
	"a9086343-4da7-44ae-8fd6-5f16641cbd5e" = {
		deadline = 1681388550.850034
		endpoint = "agent"
		pending = true
	}
```

Comment (Al2Klimov) [reply lib/icinga/clusterevents.cpp:868]: Oops. 😅 🐘

**Review by Al2Klimov — COMMENTED** [review]
Just to be clear: I asked you for splitting commits by things of what you changed since master (which you did by now). IMAO this doesn’t contradict my previous squash request which targeted fixes of the changeset itself. Apropos: Please squash not everything, but just the indentation fixes into the respective commit(s?) the misindentation comes from. So you get two commits again, but both of them w/o misindentation – and you're finally (😅) done.

**Review by Al2Klimov — APPROVED** [review]
Make it so!

**Review by julianbrost — APPROVED** [review]
Only whitespace changes since my last review, so that one is pretty much still valid.
