### PR TITLE
Fix fork error handling

### LINKED ISSUE #5617: Crash with premature EOF on resource limited OS
Related to #5611 icinga2 can crash on limited resources.

Here the child process failed forking checks, exited. And the pipe to the master went EOF.

```
[2017-09-25 13:31:25 +0200] critical/checker: Exception occured while checking 'test-420': Error: parse error: premature EOF
                                       
                     (right here) ------^


        (0) libbase.so.2.7.1: <unknown function> (+0xa33e5) [0x7fa3d50133e5]
        (1) libbase.so.2.7.1: icinga::JsonDecode(icinga::String const&) (+0x37e) [0x7fa3d50142be]
        (2) libbase.so.2.7.1: icinga::Process::Run(boost::function<void (icinga::ProcessResult const&)> const&) (+0x48b) [0x7fa3d506d1bb]
        (3) libicinga.so.2.7.1: icinga::PluginUtility::ExecuteCommand(boost::intrusive_ptr<icinga::Command> const&, boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&, std::vector<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> >, std::allocator<std::pair<icinga::String, boost::intrusive_ptr<icinga::Object> > > > const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool, boost::function<void (icinga::Value const&, icinga::ProcessResult const&)> const&) (+0x952) [0x7fa3d16e12f2]
        (4) libmethods.so.2.7.1: icinga::PluginCheckTask::ScriptFunc(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool) (+0x5a4) [0x7fa3d12f3d34]
        (5) libmethods.so.2.7.1: <unknown function> (+0x19e06) [0x7fa3d12efe06]
        (6) libmethods.so.2.7.1: <unknown function> (+0x15b4d) [0x7fa3d12ebb4d]
        (7) libbase.so.2.7.1: icinga::Function::Invoke(std::vector<icinga::Value, std::allocator<icinga::Value> > const&) (+0x3c) [0x7fa3d504815c]
        (8) libicinga.so.2.7.1: icinga::CheckCommand::Execute(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&, boost::intrusive_ptr<icinga::Dictionary> const&, bool) (+0x163) [0x7fa3d15e6c13]
        (9) libicinga.so.2.7.1: icinga::Checkable::ExecuteCheck() (+0xa7f) [0x7fa3d16fa85f]
        (10) libchecker.so.2.7.1: <unknown function> (+0x2623f) [0x7fa3d108923f]
        (11) libbase.so.2.7.1: icinga::ThreadPool::WorkerThread::ThreadProc(icinga::ThreadPool::Queue&) (+0x365) [0x7fa3d508b825]
        (12) libboost_thread.so.1.54.0: <unknown function> (+0xcc0a) [0x7fa3d6953c0a]
        (13) libpthread.so.0: <unknown function> (+0x8744) [0x7fa3d2f81744]
        (14) libc.so.6: clone (+0x6d) [0x7fa3d2cbfaad]


        (0) Executing check for object 'test-420'


[2017-09-25 13:31:25 +0200] critical/checker: Exception occured while checking 'test-349': Error: Function call 'fork' failed with error code 11, 'Resource temporarily unavailable'

        (0) Executing check for object 'test-349'



linux-u5o3:/etc/icinga2/conf.d # systemctl status icinga2.service
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/usr/lib/systemd/system/icinga2.service; disabled; vendor preset: disabled)
   Active: deactivating (stop-sigterm) since Mon 2017-09-25 13:33:06 CEST; 47s ago
 Main PID: 2500 (icinga2)
    Tasks: 69 (limit: 512)
   CGroup: /system.slice/icinga2.service
           └─2500 /usr/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon -d -e /var/log/icinga2/error.log

Sep 25 13:30:51 linux-u5o3 systemd[1]: Stopped Icinga host/service/network monitoring system.
Sep 25 13:30:51 linux-u5o3 systemd[1]: Starting Icinga host/service/network monitoring system...
Sep 25 13:30:52 linux-u5o3 systemd[1]: Started Icinga host/service/network monitoring system.
Sep 25 13:31:23 linux-u5o3 systemd[1]: [/usr/lib/systemd/system/icinga2.service:14] Unknown lvalue 'DefaultTasksMax' in section 'Service'
Sep 25 13:31:23 linux-u5o3 systemd[1]: [/usr/lib/systemd/system/icinga2.service:14] Unknown lvalue 'DefaultTasksMax' in section 'Service'
Sep 25 13:31:25 linux-u5o3 systemd[1]: [/usr/lib/systemd/system/icinga2.service:14] Unknown lvalue 'DefaultTasksMax' in section 'Service'
Sep 25 13:31:26 linux-u5o3 systemd[1]: [/usr/lib/systemd/system/icinga2.service:14] Unknown lvalue 'DefaultTasksMax' in section 'Service'
Sep 25 13:33:06 linux-u5o3 systemd[1]: Stopping Icinga host/service/network monitoring system...
```

### PR DESCRIPTION
**Pull request by N-o-X**
fixes #5617

### CODE REVIEW

File: lib/base/process.cpp [hunk 1]
```diff
@@ -1081,6 +1093,8 @@ bool Process::DoEvents(void)
 	int status, exitcode;
 	if (could_not_kill) {
 		exitcode = 128;
+	} else if (m_PID == -1) {
```
Comment (gunnarbeutner) [inline lib/base/process.cpp]: Maybe merge  this into the previous if branch?

File: lib/base/process.cpp [hunk 2]
```diff
@@ -424,6 +426,11 @@ static pid_t ProcessSpawn(const std::vector<String>& arguments, const Dictionary
 	String jresponse = String(buf, buf + rc);
 
 	Dictionary::Ptr response = JsonDecode(jresponse);
+
+	if (response->Get("rc") == -1) {
```
Comment (gunnarbeutner) [inline lib/base/process.cpp]: The `{` and `}` braces are not necessary for single-line expressions.

File: lib/base/process.cpp [hunk 3]
```diff
@@ -138,10 +138,10 @@ static Value ProcessSpawnImpl(struct msghdr *msgh, const Dictionary::Ptr& reques
 
 	pid_t pid = fork();
 
+	int errorCode = 0;
+
 	if (pid < 0) {
```
Comment (gunnarbeutner) [inline lib/base/process.cpp]: The `{` and `}` braces are not necessary for single-line expressions.

File: lib/base/process.cpp [hunk 4]
```diff
@@ -164,8 +164,8 @@ static Value ProcessSpawnImpl(struct msghdr *msgh, const Dictionary::Ptr& reques
 		(void)close(fds[2]);
 
 #ifdef HAVE_NICE
-		if (adjustPriority && nice(5) < 0)
-			Log(LogWarning, "base", "Failed to renice child process.");
+		if (adjustPriority)
+			nice(5);
```
Comment (dnsmichi) [inline lib/base/process.cpp]: If nice() fails, shouldn't we still log a warning?

Comment (N-o-X) [reply lib/base/process.cpp]: I think the child process should not write into the log. This could result in some mutex problems. Please correct me, if I'm wrong.
