### PR TITLE
Fix missing values in PerfData normalization

### LINKED ISSUE #9634: IcingaDB: PerfData normalization drops min/max when there is no warn/crit
## Describe the bug
Normalization incorrectly drops min/max values. e.g. `'test'=10;;;0;20` is normalized to `'test'=10`.

This prevents icingadb-web from displaying pie charts.

## To Reproduce

1. Create dummy test with dummy_text = `'test'=10;;;0;20`
2. Wait for service to be updated.
3. Check icingadb database in the servicestate table

## Expected behavior

As much of the performance data as possible should be forwarded.
In this case I expect `example|'test'=10;;;0;20`

## Actual behavior

Data in table gets shortened to `'test'=10`

icinga_perfdata_drop

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): r2.13.6-1
* Operating System and version: Debian 11
* Enabled features (`icinga2 feature list`): api checker graphite icingadb ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About): 2.11.3
* Config validation (`icinga2 daemon -C`): some unrelated warnings

## Additional context

Documentation doesn't mention that warn/crit are required.

- https://icinga.com/docs/icinga-2/latest/doc/05-service-monitoring/#performance-data-metrics
- https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

Perfdata without warn/crit can be helpful for reporting on and assessing a problem.

I believe it would suffice to change the nesting in this if-structure, but I don't have a working dev environment atm:
https://github.com/Icinga/icinga2/blob/ce5e6e7d13a8701031072f56e22b5e34bb6a2492/lib/base/perfdatavalue.cpp#L366-L380

### PR DESCRIPTION
**Pull request by macdems**
This is a fix to annoying bug #9634. It does not show problems with tests like #9807.

fixes #9634

### CODE REVIEW

**Comment by macdems** [comment]
already signed

**Comment by macdems** [comment]
signed with another email

**Comment by macdems** [comment]
I don't know what's going on. I have signed the CLA.

**Comment by lippserd** [comment]
Thanks for your contribution! We‘ll verify the CLA process.

Cheers,
Eric

File: test/icinga-perfdata.cpp [hunk 1]
```diff
@@ -313,7 +313,16 @@ BOOST_AUTO_TEST_CASE(ignore_invalid_warn_crit_min_max)
...
+	BOOST_CHECK(pv->Format() == "test=123456;;;3000;4000");
+}
+
+BOOST_AUTO_TEST_CASE(empty_warn_crit_min_max)
+{
+	Array::Ptr pd = PluginUtility::SplitPerfdata("testA=5;;7;1;9 testB=5;7;;1;9 testC=5;;;1;9 testD=2m;;;1 testE=5;;7;;");
+	BOOST_CHECK(pd->GetLength() == 5);
+
+	String str = PluginUtility::FormatPerfdata(pd, true);
+	BOOST_CHECK(str == "testA=5;;7;1;9 testB=5;7;;1;9 testC=5;;;1;9 testD=120s;;;60 testE=5;;7");
```
Comment (yhabteab) [inline test/icinga-perfdata.cpp:325]: I know it's a bit awkward to request a change here since literally all the test cases in that file already do it that way, but it would be nice if you could use `BOOST_CHECK_EQUAL(actual, expect);` instead. Doing so would allow you to get the actual difference as part of the assertion's error messages without having to debug and re-run the tests to figure out what's actually going wrong. Here is what it could look like if the test case fails.
```cxx
... error: in "icinga_perfdata/empty_warn_crit_min_max": check str == "testA=5;;7;1;9 testB=5;7;;1;9 testC=5;;;1;9 testD=120s;;;60s testE=5;;7" has failed [testA=5;;7;1;9 testB=5;7;;1;9 testC=5;;;1;9 testD=120s;;;60 testE=5;;7 != testA=5;;7;1;9 testB=5;7;;1;9 testC=5;;;1;9 testD=120s;;;60s testE=5;;7]
```

**Review by yhabteab — CHANGES_REQUESTED** [review]

File: lib/base/perfdatavalue.cpp [hunk 2]
```diff
@@ -363,20 +363,35 @@ String PerfdataValue::Format() const
...
 
+	std::ostringstream interm;
+
+	interm << ";";
 	if (!GetWarn().IsEmpty()) {
-		result << ";" << Convert::ToString(GetWarn());
+		interm << Convert::ToString(GetWarn());
+		result << interm.str();
+		interm.str("");
+		interm.clear();
```
[the remark this answers is not in the document]
Comment (macdems) [reply lib/base/perfdatavalue.cpp:373]: Ok. But why not `std::string` then?

File: test/icinga-perfdata.cpp (hunk 1 above)
Comment (macdems) [reply test/icinga-perfdata.cpp:325]: It is actually quite trivial to update all check in the file.

File: lib/base/perfdatavalue.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (macdems) [reply lib/base/perfdatavalue.cpp]: Done with `std::string`. `String` uses it internally anyway, so no need to complicate things.

File: test/icinga-perfdata.cpp
Comment (yhabteab) [inline test/icinga-perfdata.cpp:1]: Initially I didn't mean that you have to adjust all the test cases, but now that it's done, please push the changes that are not related to the actual issue in a separate commit.

File: test/icinga-perfdata.cpp [hunk 3]
```diff
@@ -11,309 +11,318 @@ BOOST_AUTO_TEST_SUITE(icinga_perfdata)
...
+	BOOST_CHECK_EQUAL(pv->GetWarn(), Empty);
+	BOOST_CHECK_EQUAL(pv->GetCrit(), Empty);
+	BOOST_CHECK_EQUAL(pv->GetMin(), 3000);
+	BOOST_CHECK_EQUAL(pv->GetMax(), 4000);
+
+	BOOST_CHECK_EQUAL(pv->Format(), "test=123456;;;3000;4000");
+}
 
-	BOOST_CHECK(pv->Format() == "test=123456");
+BOOST_AUTO_TEST_CASE(empty_warn_crit_min_max)
```
Comment (yhabteab) [inline test/icinga-perfdata.cpp:319]: I missed pointing this out to you yesterday, but you need to add this new case [here](https://github.com/Icinga/icinga2/blob/master/test/CMakeLists.txt#L49), otherwise `make test` won't run it.

**Review by yhabteab — CHANGES_REQUESTED** [review]

**Comment by yhabteab** [comment]
Please also add yourself to the [authors](https://github.com/Icinga/icinga2/blob/master/AUTHORS) file.

File: AUTHORS [hunk 4]
```diff
@@ -299,3 +299,4 @@ Yohan Jarosz <yohanjarosz@yahoo.fr>
 Yonas Habteab <yonas.habteab@icinga.com>
 Zachary McGibbon <zachary.mcgibbon@gmail.com>
 Zoltan Nagy <abesto@abesto.net>
+Maciej Dems <macdems@gmail.com>
```
Comment (yhabteab) [inline AUTHORS:302]: Seems like you're using a different email to push the changes that's the GitHub action is complaining about. `Maciej Dems <maciej.dems@p.lodz.pl>`

While you're fixing this, please respect the order of the authors' names (ordered alphabetically) and push these changes also as part of the second commit, not the first one. Thanks!

File: test/icinga-perfdata.cpp (hunk 3 above)
Comment (yhabteab) [reply test/icinga-perfdata.cpp:319]: Forgot to push the changes that address this one?

Comment (macdems) [reply test/icinga-perfdata.cpp:319]: It was a bit messy when splitting into two commits. Should be ok now.

**Review by yhabteab — CHANGES_REQUESTED** [review]
I just noticed one last thing, this PR should be fine then! With your recent changes, this [test case](https://github.com/Icinga/icinga2/blob/8437f08a5e326a215e341fbdb3bd156b9dc72d65/test/icinga-perfdata.cpp#L306) name doesn't make sense anymore as we no longer ignore min/max even when empty/invalid warn/crit thresholds are provided. Given that the warn/crit thresholds tested there are actually defined as a range `1000:2000;0:3000` which isn't supported yet (https://github.com/Icinga/icinga2/issues/9038), it should be changed to something like `ignore_warn_crit_ranges`.  Remember to adjust the name in the `test/CMakeLists.txt` file as well.

**Review by yhabteab — APPROVED** [review]
LFTM! Thanks for your contributions!

**Review by Al2Klimov — APPROVED** [review]
