### PR TITLE
FireSuppressedNotifications(const Notification::Ptr&): don't send notifications while suppressed by checkable

### LINKED ISSUE #8509: Icinga sending notifications for service with scheduled downtime after change in timeperiod
## Describe the bug

Hello,

We recently updated to Icinga 2.12.1-1.stretch and are noticing something change.
When we schedule downtime for a service, we still receive notifications for it once the time transitions into a new time period. See logs below:

```
[2020-11-26 02:59:57 +0100] information/HttpServerConnection: Request: POST /v1/actions/schedule-downtime (from [::ffff:127.0.0.1]:44024), user: icingaweb2, agent: ).
[2020-11-26 02:59:57 +0100] information/Downtime: Triggering downtime 'n03c01!gluster!ca4024e2-d7a5-483f-9a89-14d11c764d64' for checkable 'n03c01.!gluster'.
[2020-11-26 02:59:57 +0100] information/ConfigObjectUtility: Created and activated object 'n03c01!gluster!ca4024e2-d7a5-483f-9a89-14d11c764d64' of type 'Downtime'.
[2020-11-26 02:59:57 +0100] information/Downtime: Added downtime 'n03c01!gluster!ca4024e2-d7a5-483f-9a89-14d11c764d64' between '2020-11-26 02:59:46' and '2020-12-08 03:59:46', author: 'rn0001', fixed


[2020-11-26 07:00:30 +0100] information/Notification: Sending 'Problem' notification 'n03c01!gluster!mail-service-weekday-pd' for user 'pagerduty'
[2020-11-26 07:00:30 +0100] information/Notification: Completed sending 'Problem' notification 'n03c01!gluster!mail-service-weekday-pd' for checkable 'n03c01!gluster' and user 'pagerduty' using command 'notify-service-by-pagerduty'.
```

You can see here we scheduled a downtime on 2020-11-26 02:59:46 that should last until 2020-12-08 03:59:46  
However we got a notification on 2020-11-26 07:00:30 +0100 that the service was down.

The time corresponds with our time period:  

```
object TimePeriod "day" {
  import "legacy-timeperiod"

  display_name = "Icinga 2 daytime TimePeriod"
  ranges = {
    "monday"    = "07:00-24:00"
    "tuesday"   = "07:00-24:00"
    "wednesday" = "07:00-24:00"
    "thursday"  = "07:00-24:00"
    "friday"    = "07:00-24:00"
    "saturday"  = "07:00-24:00"
    "sunday"    = "07:00-24:00"
  }
}

object TimePeriod "night" {
  import "legacy-timeperiod"

  display_name = "Icinga 2 nighttime TimePeriod"
  ranges = {
    "monday"    = "00:00-07:00"
    "tuesday"   = "00:00-07:00"
    "wednesday" = "00:00-07:00"
    "thursday"  = "00:00-07:00"
    "friday"    = "00:00-07:00"
    "saturday"  = "00:00-07:00"
    "sunday"    = "00:00-07:00"
  }
}
```

```
apply Notification "mail-service-weekday-pd" to Service {
  command = "notify-service-by-pagerduty"
  users = [ "pagerduty" ]
  period = "weekday"
  times.begin = 10m

  assign where service.vars.day_notify == true
  ignore where host.vars.disable_notifications
}
```

```
object CheckCommand "custom_check_gluster" {
  command = [ PluginDir + "/custom/check_gluster.sh" ]
}

apply Service "gluster" {
  import "generic-service"

  check_command = "custom_check_gluster"
  command_endpoint = host.vars.client_endpoint
  vars.generic_notify = true
  vars.day_notify = true
  vars.night_notify = true
  assign where host.vars.client_endpoint && host.vars.gluster
}
```

We want the downtime scheduling to be universal and ignore the time periods. When we say a service/host is down between $x and $y there should be no notifications at all between those date/times. Previously that was the case. 

Now it seems the downtime is only applied to the current time-period or something like that ..?

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.1-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-12-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: runner-wytxxqbb-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Enabled features (`icinga2 feature list`):
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite icingadb influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification
```

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
2.8.2
Git commit
e5af1684a0156d3c8385c908330abd477ca17065

```

Name | Version
-- | --
monitoring | 2.8.2

### PR DESCRIPTION
**Pull request by Al2Klimov**
... e.g. if a notification enters its time period (not suppressed anymore), but its checkable has entered a downtime (suppressed).

fixes #8509

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

#8509

## After

```
➜  icinga2 git:(bugfix/notifications-downtime-change-in-timeperiod-8509) cat 8509.conf
object CheckerComponent "cc" { }
object NotificationComponent "nc" { }

object CheckCommand "dummy" {
        import "dummy-check-command"
}

object Host "8509" {
        check_command = "dummy"
        #max_check_attempts = 1
        check_interval = 10s

        var that = this
        var commitTime = get_time()

        vars.dummy_state = function() use(that, commitTime) {
                return if (get_time() - commitTime < 1m) { 0 } else { 2 }
        }
        vars.dummy_text = " "
}

object NotificationCommand "false" {
        command = [ "false" ]
}

object User "me" {
}

object TimePeriod "8509" {
        ranges = {
                "friday" = "18:35-18:45"
        }
}

object Notification "8509" {
        host_name = "8509"
        command = "false"
        users = [ "me" ]
        period = "8509"
}

object Downtime "8509" {
        host_name = "8509"
        author = "me"
        comment = "8509"
        start_time = get_time() + 5m
        end_time = start_time + 10m
        fixed = true
}
➜  icinga2 git:(bugfix/notifications-downtime-change-in-timeperiod-8509) prefix/sbin/icinga2 daemon -x notice -c 8509.conf
[2020-11-27 18:26:05 +0100] information/cli: Icinga application loader (version: v2.12.0-186-gc0e843cfa)
[2020-11-27 18:26:05 +0100] notice/cli: Spawning seemless worker process doing the actual work
[2020-11-27 18:26:05 +0100] notice/cli: Spawned worker process (PID 11980), waiting for it to load its config
[2020-11-27 18:26:05 +0100] information/cli: Loading configuration file(s).
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: 8509.conf
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/include.conf
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/8c30df0e-9af9-47dc-ae0a-54bafc02262f/include.conf
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/8c30df0e-9af9-47dc-ae0a-54bafc02262f/../active.conf
[2020-11-27 18:26:05 +0100] information/ConfigItem: Committing config item(s).
[2020-11-27 18:26:05 +0100] notice/WorkQueue: Spawning WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 Downtime.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 Host.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 Notification.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 NotificationCommand.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 TimePeriod.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 User.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-27 18:26:05 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-27 18:26:05 +0100] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-11-27 18:26:05 +0100] notice/cli: Notifying umbrella process (PID 11966) about the config loading success
[2020-11-27 18:26:05 +0100] notice/cli: Worker process successfully loaded its config
[2020-11-27 18:26:05 +0100] notice/cli: Waiting for the umbrella process to let us doing the actual work
[2020-11-27 18:26:05 +0100] notice/cli: The umbrella process let us continuing
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/modified-attributes.conf
[2020-11-27 18:26:05 +0100] information/ConfigItem: Triggering Start signal for config items
[2020-11-27 18:26:05 +0100] notice/Downtime: Checkable '8509' already in a NOT-OK state. Triggering downtime now.
[2020-11-27 18:26:05 +0100] information/NotificationComponent: 'nc' started.
[2020-11-27 18:26:05 +0100] information/CheckerComponent: 'cc' started.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Activated all objects.
[2020-11-27 18:26:05 +0100] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonCommand::Run'
[2020-11-27 18:26:05 +0100] notice/ApiListener: Updating object authority for local objects.
[2020-11-27 18:26:05 +0100] notice/Checkable: State Change: Checkable '8509' hard state change from DOWN to UP detected.
[2020-11-27 18:26:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:26:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:26:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:26:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:26:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:26:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:26:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:26:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:26:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:26:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:10 +0100] notice/Checkable: State Change: Checkable '8509' soft state change from UP to DOWN detected.
[2020-11-27 18:27:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:27:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:27:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:27:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:27:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:27:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:27:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:27:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:28:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:28:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:07 +0100] notice/Checkable: State Change: Checkable '8509' soft state change from DOWN to DOWN detected.
[2020-11-27 18:28:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:29:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:29:04 +0100] notice/Checkable: State Change: Checkable '8509' hard state change from DOWN to DOWN detected.
[2020-11-27 18:29:04 +0100] information/Checkable: Checkable '8509' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-11-27 18:29:04 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object '8509!8509'.
[2020-11-27 18:29:04 +0100] notice/Notification: Not sending notifications for notification object '8509!8509': not in timeperiod '8509'
[2020-11-27 18:29:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:29:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:29:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:29:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:29:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:29:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:29:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:29:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:29:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:29:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:29:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:30:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:30:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:30:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:30:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:30:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:30:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:30:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:30:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:30:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:30:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:30:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:30:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:05 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-11-27 18:31:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:05 +0100] information/Checkable: Checkable '8509' has 1 notification(s). Checking filters for type 'DowntimeStart', sends will be logged.
[2020-11-27 18:31:05 +0100] notice/Notification: Attempting to send notifications of type 'DowntimeStart' for notification object '8509!8509'.
[2020-11-27 18:31:05 +0100] notice/Notification: Not sending notifications for notification object '8509!8509': not in timeperiod '8509'
[2020-11-27 18:31:05 +0100] information/Downtime: Triggering downtime '8509!8509' for checkable '8509'.
[2020-11-27 18:31:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:31:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:32:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:33:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:34:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:35:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:05 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-11-27 18:36:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:36:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:37:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:38:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:39:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:40:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:05 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-11-27 18:41:05 +0100] notice/NotificationComponent: Attempting to re-send previously suppressed notification '8509!8509'.
[2020-11-27 18:41:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:05 +0100] notice/Notification: Attempting to send notifications of type 'Problem' for notification object '8509!8509'.
[2020-11-27 18:41:05 +0100] information/Notification: Sending 'Problem' notification '8509!8509' for user 'me'
[2020-11-27 18:41:05 +0100] notice/Process: Running command 'false': PID 12053
[2020-11-27 18:41:05 +0100] information/Notification: Completed sending 'Problem' notification '8509!8509' for checkable '8509' and user 'me' using command 'false'.
[2020-11-27 18:41:05 +0100] notice/Process: PID 12053 ('false') terminated with exit code 1
[2020-11-27 18:41:05 +0100] warning/PluginNotificationTask: Notification command for object '8509' (PID: 12053, arguments: 'false') terminated with exit code 1, output:
[2020-11-27 18:41:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:26 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:31 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:36 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:41 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:46 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:51 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:41:56 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:01 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:06 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:11 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:16 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:21 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:26 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:31 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:36 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:41 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:46 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:51 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:42:56 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:43:01 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:43:06 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:43:11 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:43:16 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:43:21 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:43:26 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:43:31 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
^C[2020-11-27 18:43:31 +0100] notice/cli: Got signal 2, forwarding to seemless worker (PID 11980)
[2020-11-27 18:43:31 +0100] information/Application: Received request to shut down.
[2020-11-27 18:43:31 +0100] information/Application: Shutting down...
[2020-11-27 18:43:31 +0100] information/CheckerComponent: 'cc' stopped.
[2020-11-27 18:43:31 +0100] information/NotificationComponent: 'nc' stopped.
[2020-11-27 18:43:31 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-11-27 18:43:31 +0100] information/IcingaApplication: Icinga has shut down.
[2020-11-27 18:43:31 +0100] notice/cli: Seemless worker (PID 11980) stopped, stopping as well
➜  icinga2 git:(bugfix/notifications-downtime-change-in-timeperiod-8509)
```

File: lib/icinga/checkable-notification.cpp [hunk 1]
```diff
@@ -258,6 +241,27 @@ bool Checkable::NotificationReasonApplies(NotificationType type)
 	}
 }
 
+/**
+ * Returns whether *this not allows sending a notification of type type right now.
+ *
+ * @param type The type of notification to send (or not to send).
+ *
+ * @return Whether not to send the notification.
+ */
```
Comment (julianbrost) [inline lib/icinga/checkable-notification.cpp:250]:
```suggestion
/**
 * Checks if notifications of a given type should be suppressed for this Checkable at the moment.
 *
 * @param type The notification type for which to query the suppression status.
 *
 * @return true if no notification of this type should be sent.
 */
```

**Review by julianbrost — CHANGES_REQUESTED** [review]
Seems fine, I just find the documentation comment hard to read, see my suggestion.

**Review by julianbrost — APPROVED** [review]
LGTM, feel free to squash the commits.

**Comment by Al2Klimov** [comment]
Too bad Eric forbid that in such cases.
