### PR TITLE
Make compilable on Boost v1.81

### LINKED ISSUE #9618: Build failure with Boost 1.81
## Describe the bug

Icinga2 2.13.6 fails to compile against Boost 1.81.

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. Upgrade Boost to Boost 1.81
2. Build Icinga with the following options:
`-DICINGA2_UNITY_BUILD=no -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DICINGA2_SYSCONFIGFILE=/etc/conf.d/icinga2 -DICINGA2_PLUGINDIR=/usr/lib64/nagios/plugins -DICINGA2_USER=icinga -DICINGA2_GROUP=icingacmd -DICINGA2_COMMAND_GROUP=icingacmd -DICINGA2_RUNDIR=/run -DINSTALL_SYSTEMD_SERVICE_AND_INITSCRIPT=ON -DUSE_SYSTEMD=yes -DLOGROTATE_HAS_SU=ON -DICINGA2_LTO_BUILD=yes -DICINGA2_WITH_PGSQL=no -DICINGA2_WITH_MYSQL=yes`
3. Build fails:
```
FAILED: lib/remote/CMakeFiles/remote.dir/httphandler.cpp.o 
/var/tmp/portage/net-analyzer/icinga2-2.13.6/temp/clang-wrappers/x86_64-pc-linux-gnu-g++ -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DBOOST_FILESYSTEM_NO_DEPRECATED -D_GNU_SOURCE -I/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6/third-party/nlohmann_json -I/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6/third-party/utf8cpp/source -I/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6 -I/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6/lib -I/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6_build -I/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6_build/lib  -O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches -Wreturn-type -D_GLIBCXX_ASSERTIONS -g -pthread -Winvalid-pch -flto -std=c++0x -fdiagnostics-color=always -MD -MT lib/remote/CMakeFiles/remote.dir/httphandler.cpp.o -MF lib/remote/CMakeFiles/remote.dir/httphandler.cpp.o.d -o lib/remote/CMakeFiles/remote.dir/httphandler.cpp.o -c /var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6/lib/remote/httphandler.cpp
/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6/lib/remote/httphandler.cpp: In static member function ‘static void icinga::HttpHandler::ProcessRequest(icinga::AsioTlsStream&, const icinga::ApiUser::Ptr&, boost::beast::http::request<boost::beast::http::basic_string_body<char> >&, boost::beast::http::response<boost::beast::http::basic_string_body<char> >&, boost::asio::yield_context&, icinga::HttpServerConnection&)’:
/var/tmp/portage/net-analyzer/icinga2-2.13.6/work/icinga2-2.13.6/lib/remote/httphandler.cpp:61:49: error: ‘using string_view = boost::core::string_view’ {aka ‘class boost::core::basic_string_view<char>’} has no member named ‘to_string’
   61 |         Url::Ptr url = new Url(request.target().to_string());
      |                                                 ^~~~~~~~~
```

Full log: https://bugs.gentoo.org/attachment.cgi?id=844789.

## Expected behavior

Successful compilation.

## Your Environment

* Version used (`icinga2 --version`):
* Operating System and version: Gentoo, rolling distro
* Enabled features (`icinga2 feature list`): N/A
* Icinga Web 2 version and modules (System - About): N/A
* Config validation (`icinga2 daemon -C`): N/A
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes: N/A

## Additional context

- This is a forward of a downstream report in Gentoo at https://bugs.gentoo.org/888063
- Alpine Linux has a patch at https://git.alpinelinux.org/aports/commit/?id=2255728eeb75fe2e71d58f4c9a00a661de5b7406

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #9618

### CODE REVIEW

File: lib/base/string.hpp [hunk 1]
```diff
@@ -23,6 +24,13 @@ class Value;
  */
 class String
 {
+private:
+#if BOOST_VERSION >= 108100
+	typedef boost::beast::string_view BeastStringView;
+#else
+	typedef boost::string_view BeastStringView;
+#endif
+
```
Comment (julianbrost) [inline lib/base/string.hpp:33]: [`boost::beast::string_view` already existed before](https://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/ref/boost__beast__string_view.html) and [1.81 only changed the type it's aliased to](https://github.com/boostorg/beast/commit/9d23bec2bc523223a377582302bd28d04cb514ed). So you shouldn't need `#if` here and just always use it.

**Review by julianbrost — CHANGES_REQUESTED** [review]

**Review by julianbrost — APPROVED** [review]
