### PR TITLE
Fix cluster message routing for global zones

### LINKED ISSUE #8439: API: Runtime creation/update/deletion of config objects in global zones doesn't get synced properly
Creation/Update/Deletion of config objects in global zones via API doesn't get synced properly by our cluster routing.

`ApiListener::RelayMessageOne` doesn't handle global zones correctly. It only relays the message to one zone and considers it relayed. This results in only one child zone getting updated.

### Setup
- 1 Master
- 3 Agents

### Steps 
1. Create a host group (any type works) in a global zone:
```
curl -s -k -u root:icinga -H 'Accept: application/json' -X PUT -k "https://localhost:5665/v1/objects/hostgroups/testhostgroup" -d '{ "attrs": { "zone": "global-templates" } }'
```

2. Have a look at the agents logs. Only one of them should get this message:
```
[2020-11-05 09:30:54 +0000] information/ConfigObjectUtility: Created and activated object 'testhostgroup' of type 'HostGroup'.
```

3. Delete host group (should also only be synced to one agent):
```
curl -s -k -u root:icinga -H 'Accept: application/json' -X DELETE -k "https://localhost:5665/v1/objects/hostgroups/testhostgroup"
```

----
ref/NC/693847

### PR DESCRIPTION
**Pull request by julianbrost**
RelayMessageOne used to relay the message only to one other endpoint for other zones, which is fine, as long as the target zone is a child/parent zone but breaks if the target zone is a global one. In this case, the message has to be forwarded within the local zone as well as to one node in each child zone.

The diff looks way worse than what got actually changed: instead of iterating over all endpoints combined from multiple zones, this now happens in nested loops for the zones and their endpoints and the `relayed`/`log_needed`/`log_done` logic is done separately for each zone.

fixes #8439

### CODE REVIEW

**Comment by julianbrost** [comment]
With this PR, multiple agents properly receive the config update (without, only one agent logs this message):

PUT:

```
master-1_1  | [2020-11-05 14:55:32 +0000] information/ApiListener: New client connection from [172.23.0.1]:55494 (no client certificate)
master-1_1  | [2020-11-05 14:55:32 +0000] information/HttpServerConnection: Request: PUT /v1/objects/hostgroups/testhostgroup (from [172.23.0.1]:55494), user: root, agent: curl/7.73.0).
master-1_1  | [2020-11-05 14:55:32 +0000] information/ConfigObjectUtility: Created and activated object 'testhostgroup' of type 'HostGroup'.
master-1_1  | [2020-11-05 14:55:32 +0000] information/HttpServerConnection: HTTP client disconnected (from [172.23.0.1]:55494)
agent-2_1   | [2020-11-05 14:55:32 +0000] information/ConfigObjectUtility: Created and activated object 'testhostgroup' of type 'HostGroup'.
agent-1_1   | [2020-11-05 14:55:32 +0000] information/ConfigObjectUtility: Created and activated object 'testhostgroup' of type 'HostGroup'.
```

DELETE:

```
master-1_1  | [2020-11-05 14:55:36 +0000] information/ApiListener: New client connection from [172.23.0.1]:55498 (no client certificate)
master-1_1  | [2020-11-05 14:55:36 +0000] information/HttpServerConnection: Request: DELETE /v1/objects/hostgroups/testhostgroup (from [172.23.0.1]:55498), user: root, agent: curl/7.73.0).
master-1_1  | [2020-11-05 14:55:36 +0000] information/ConfigObjectUtility: Deleted object 'testhostgroup' of type 'HostGroup'.
agent-2_1   | [2020-11-05 14:55:36 +0000] information/ConfigObjectUtility: Deleted object 'testhostgroup' of type 'HostGroup'.
agent-1_1   | [2020-11-05 14:55:36 +0000] information/ConfigObjectUtility: Deleted object 'testhostgroup' of type 'HostGroup'.
master-1_1  | [2020-11-05 14:55:36 +0000] information/HttpServerConnection: HTTP client disconnected (from [172.23.0.1]:55498)
```

**Comment by julianbrost** [comment]
Good for review from my side, but as this touches code very deep in the cluster communication, this still needs more testing in different cluster scenarios.

**Comment by julianbrost** [comment]
Now started testing this in more detail. Replaying the delete message to endpoints that were offline when the delete request was issued did *not* work. Will investigate.

**Comment by julianbrost** [comment]
The problem I was observing seems to be more related to how config sync works in general than to the code I am touching in this PR, as the routing seems to work as expected.

To me it looks like config sync is supposed to work without the replay log. Both `ApiListener::UpdateConfigObject()` and `ApiListener::DeleteConfigObject()` explicitly call `RelayMessage()` with `log = false`.
https://github.com/Icinga/icinga2/blob/dc79c4e59a38971b148116d42e3c02372373620d/lib/remote/apilistener-configsync.cpp#L376
https://github.com/Icinga/icinga2/blob/dc79c4e59a38971b148116d42e3c02372373620d/lib/remote/apilistener-configsync.cpp#L426

And in general, I don't think it would be a good idea to me to rely on the replay log for config sync, as the default log duration is one day (i.e. if a node is offline for more than a day, it would break nonetheless) and there are even examples in the documentation for disabling it completely.

The other way to fix this would be updating the initial config sync for each connection to also handle propagating the deletion of objects, but this change would require some serious changes.

File: lib/remote/apilistener.cpp [hunk 1]
```diff
@@ -1032,6 +1032,17 @@ void ApiListener::SyncSendMessage(const Endpoint::Ptr& endpoint, const Dictionar
 	}
 }
 
+/**
+ * Relay a message to a directly connected zone or to a global zone. If some other zone is passed as the target zone,
+ * it is not relayed.
```
Comment (Al2Klimov) [inline lib/remote/apilistener.cpp:1037]: _I'd_ break just before "If".

File: lib/remote/apilistener.cpp [hunk 2]
```diff
@@ -1032,6 +1032,17 @@ void ApiListener::SyncSendMessage(const Endpoint::Ptr& endpoint, const Dictionar
...
+ *
+ * @param targetZone The zone to relay to.
+ * @param origin Information about where this message is relayed from (if it was not generated locally)
+ * @param message The message to relay
+ * @param currentZoneMaster The current master node of the local zone
+ * @return true if the message has been relayed to all relevant endpoints,
+ *         false if it hasn't and must be persisted in the replay log
```
Comment (Al2Klimov) [inline lib/remote/apilistener.cpp:1044]: _I'd_ be consequent w/ (not) using full stops.

File: lib/remote/apilistener.cpp [hunk 3]
```diff
@@ -1050,82 +1061,88 @@ bool ApiListener::RelayMessageOne(const Zone::Ptr& targetZone, const MessageOrig
...
 			if (zone->GetParent() == localZone) {
-				std::set<Endpoint::Ptr> endpoints = zone->GetEndpoints();
-				targetEndpoints.insert(endpoints.begin(), endpoints.end());
+				allTargetZones.insert(zone);
 			}
 		}
 	} else {
-		targetEndpoints = targetZone->GetEndpoints();
+		/* whereas if it's not global, the message is just relayed to the zone itself */
+		allTargetZones.insert(targetZone);
```
Comment (Al2Klimov) [inline lib/remote/apilistener.cpp:1075]: And localZone?

File: lib/remote/apilistener.cpp [hunk 4]
```diff
@@ -1050,82 +1061,88 @@ bool ApiListener::RelayMessageOne(const Zone::Ptr& targetZone, const MessageOrig
...
 
-		log_needed = true;
+	for (const Zone::Ptr& currentTargetZone : allTargetZones) {
+		bool relayed = false, log_needed = false, log_done = false;
 
-		/* Don't relay messages to disconnected endpoints. */
-		if (!targetEndpoint->GetConnected()) {
-			if (targetZone == localZone)
-				log_done = false;
+		for (const Endpoint::Ptr &targetEndpoint : currentTargetZone->GetEndpoints()) {
```
Comment (Al2Klimov) [inline lib/remote/apilistener.cpp:1083]: 1. `Endpoint::Ptr& targetEndpoint`, not `Endpoint::Ptr &targetEndpoint`.

Comment (Al2Klimov) [inline lib/remote/apilistener.cpp:1083]: 2. Feel free to use `auto&`.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]

File: lib/remote/apilistener.cpp (hunk 3 above)
Comment (julianbrost) [reply lib/remote/apilistener.cpp:1075]: Why do you think it's needed? The old code also only considers targetZone in this case: https://github.com/Icinga/icinga2/blob/dc79c4e59a38971b148116d42e3c02372373620d/lib/remote/apilistener.cpp#L1068

I'm not 100% sure about this case as I mostly considered global zones so I kept it as it is.

Comment (Al2Klimov) [reply lib/remote/apilistener.cpp:1075]: Fine.

File: lib/remote/apilistener.cpp (hunk 4 above)
Comment (julianbrost) [reply lib/remote/apilistener.cpp]: I'd stick to the type names. They weren't too much work to type out and I think it's clearer this way.

**Review by Al2Klimov — APPROVED** [review]
If it fixes the problem...

**Comment by lippserd** [comment]
> If it fixes the problem...

Please verify whether it does.

**Review by Al2Klimov — APPROVED** [review]
## Before

```
➜  icinga2 git:(1450e1bb7) curl -fksSLu root:icinga -H 'Accept: application/json' -X PUT 'https://localhost:5661/v1/objects/hostgroups/lolcat' -d '{ "attrs": { "zone": "global-templates" }, "pretty": true }'; echo
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}
➜  icinga2 git:(1450e1bb7) prefix1/sbin/icinga2 daemon -C; prefix1/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:06:08 +0100] information/cli: Icinga application loader (version: v2.12.0-144-g1450e1bb7)
[2020-11-11 12:06:08 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:06:08 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:06:08 +0100] information/ApiListener: My API identity: m1
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 1 ApiUser.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 1 HostGroup.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:06:08 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-11 12:06:08 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix1/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:06:08 +0100] information/cli: Finished validating the configuration file(s).
Object 'lolcat' of type 'HostGroup':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * __name = "lolcat"
  * action_url = ""
  * display_name = "lolcat"
  * groups = null
  * name = "lolcat"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 24
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf"
  * templates = [ "lolcat" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * type = "HostGroup"
  * vars = null
  * zone = "global-templates"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf', lines 3:2-3:26
➜  icinga2 git:(1450e1bb7) prefix2/sbin/icinga2 daemon -C; prefix2/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:06:22 +0100] information/cli: Icinga application loader (version: v2.12.0-144-g1450e1bb7)
[2020-11-11 12:06:22 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:06:22 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:06:22 +0100] information/ApiListener: My API identity: a1
[2020-11-11 12:06:22 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:06:22 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:06:22 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:06:22 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:06:22 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:06:22 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:06:22 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:06:22 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix2/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:06:22 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(1450e1bb7) prefix3/sbin/icinga2 daemon -C; prefix3/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:06:40 +0100] information/cli: Icinga application loader (version: v2.12.0-144-g1450e1bb7)
[2020-11-11 12:06:40 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:06:40 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:06:40 +0100] information/ApiListener: My API identity: a2
[2020-11-11 12:06:40 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:06:40 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:06:40 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:06:40 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:06:40 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:06:40 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:06:40 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:06:40 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix3/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:06:40 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(1450e1bb7) prefix4/sbin/icinga2 daemon -C; prefix4/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:06:54 +0100] information/cli: Icinga application loader (version: v2.12.0-144-g1450e1bb7)
[2020-11-11 12:06:54 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:06:54 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:06:54 +0100] information/ApiListener: My API identity: a3
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 1 HostGroup.
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:06:54 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:06:54 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix4/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:06:54 +0100] information/cli: Finished validating the configuration file(s).
Object 'lolcat' of type 'HostGroup':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * __name = "lolcat"
  * action_url = ""
  * display_name = "lolcat"
  * groups = null
  * name = "lolcat"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 24
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf"
  * templates = [ "lolcat" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * type = "HostGroup"
  * vars = null
  * zone = "global-templates"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf', lines 3:2-3:26
➜  icinga2 git:(1450e1bb7) cat prefix1/etc/icinga2/zones.conf
object Endpoint "m1" {
	host = "127.0.0.1"
	port = 5661
}

object Zone "master" {
	endpoints = [ "m1" ]
}

object Endpoint "a1" {
	host = "127.0.0.1"
	port = 5662
}

object Zone "a1" {
	endpoints = [ "a1" ]
	parent = "master"
}

object Endpoint "a2" {
	host = "127.0.0.1"
	port = 5663
}

object Zone "a2" {
	endpoints = [ "a2" ]
	parent = "master"
}

object Endpoint "a3" {
	host = "127.0.0.1"
	port = 5664
}

object Zone "a3" {
	endpoints = [ "a3" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}
➜  icinga2 git:(1450e1bb7)
```

## After

```
➜  icinga2 git:(bugfix/message-routing-for-global-zones) curl -fksSLu root:icinga -H 'Accept: application/json' -X PUT 'https://localhost:5661/v1/objects/hostgroups/lolcat' -d '{ "attrs": { "zone": "global-templates" }, "pretty": true }'; echo
{
    "results": [
        {
            "code": 200.0,
            "status": "Object was created"
        }
    ]
}
➜  icinga2 git:(bugfix/message-routing-for-global-zones) prefix1/sbin/icinga2 daemon -C; prefix1/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:13:41 +0100] information/cli: Icinga application loader (version: v2.12.0-145-gcb476172e)
[2020-11-11 12:13:41 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:13:41 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:13:41 +0100] information/ApiListener: My API identity: m1
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 1 ApiUser.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 1 HostGroup.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:13:41 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-11 12:13:41 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix1/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:13:41 +0100] information/cli: Finished validating the configuration file(s).
Object 'lolcat' of type 'HostGroup':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * __name = "lolcat"
  * action_url = ""
  * display_name = "lolcat"
  * groups = null
  * name = "lolcat"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 24
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf"
  * templates = [ "lolcat" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * type = "HostGroup"
  * vars = null
  * zone = "global-templates"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix1/var/lib/icinga2/api/packages/_api/80a76565-a2fc-467d-876c-46b4e1017d1c/conf.d/hostgroups/lolcat.conf', lines 3:2-3:26
➜  icinga2 git:(bugfix/message-routing-for-global-zones) prefix2/sbin/icinga2 daemon -C; prefix2/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:14:00 +0100] information/cli: Icinga application loader (version: v2.12.0-145-gcb476172e)
[2020-11-11 12:14:00 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:14:00 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:14:00 +0100] information/ApiListener: My API identity: a1
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 1 HostGroup.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:14:00 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-11 12:14:00 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix2/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:14:00 +0100] information/cli: Finished validating the configuration file(s).
Object 'lolcat' of type 'HostGroup':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix2/var/lib/icinga2/api/packages/_api/21547a95-83cd-4af6-892f-bbb3f79644b5/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * __name = "lolcat"
  * action_url = ""
  * display_name = "lolcat"
  * groups = null
  * name = "lolcat"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 24
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix2/var/lib/icinga2/api/packages/_api/21547a95-83cd-4af6-892f-bbb3f79644b5/conf.d/hostgroups/lolcat.conf"
  * templates = [ "lolcat" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix2/var/lib/icinga2/api/packages/_api/21547a95-83cd-4af6-892f-bbb3f79644b5/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * type = "HostGroup"
  * vars = null
  * zone = "global-templates"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix2/var/lib/icinga2/api/packages/_api/21547a95-83cd-4af6-892f-bbb3f79644b5/conf.d/hostgroups/lolcat.conf', lines 3:2-3:26
➜  icinga2 git:(bugfix/message-routing-for-global-zones) prefix3/sbin/icinga2 daemon -C; prefix3/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:14:18 +0100] information/cli: Icinga application loader (version: v2.12.0-145-gcb476172e)
[2020-11-11 12:14:18 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:14:18 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:14:18 +0100] information/ApiListener: My API identity: a2
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 1 HostGroup.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:14:18 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-11 12:14:18 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix3/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:14:18 +0100] information/cli: Finished validating the configuration file(s).
Object 'lolcat' of type 'HostGroup':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix3/var/lib/icinga2/api/packages/_api/5b2fe254-d2d6-48a5-bccc-361ce22c9f5b/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * __name = "lolcat"
  * action_url = ""
  * display_name = "lolcat"
  * groups = null
  * name = "lolcat"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 24
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix3/var/lib/icinga2/api/packages/_api/5b2fe254-d2d6-48a5-bccc-361ce22c9f5b/conf.d/hostgroups/lolcat.conf"
  * templates = [ "lolcat" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix3/var/lib/icinga2/api/packages/_api/5b2fe254-d2d6-48a5-bccc-361ce22c9f5b/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * type = "HostGroup"
  * vars = null
  * zone = "global-templates"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix3/var/lib/icinga2/api/packages/_api/5b2fe254-d2d6-48a5-bccc-361ce22c9f5b/conf.d/hostgroups/lolcat.conf', lines 3:2-3:26
➜  icinga2 git:(bugfix/message-routing-for-global-zones) prefix4/sbin/icinga2 daemon -C; prefix4/sbin/icinga2 object list -t hostgroup
[2020-11-11 12:14:37 +0100] information/cli: Icinga application loader (version: v2.12.0-145-gcb476172e)
[2020-11-11 12:14:37 +0100] information/cli: Loading configuration file(s).
[2020-11-11 12:14:37 +0100] information/ConfigItem: Committing config item(s).
[2020-11-11 12:14:37 +0100] information/ApiListener: My API identity: a3
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 4 Endpoints.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 1 HostGroup.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 5 Zones.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-11 12:14:37 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-11 12:14:37 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix4/var/cache/icinga2/icinga2.vars'
[2020-11-11 12:14:37 +0100] information/cli: Finished validating the configuration file(s).
Object 'lolcat' of type 'HostGroup':
  % declared in '/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * __name = "lolcat"
  * action_url = ""
  * display_name = "lolcat"
  * groups = null
  * name = "lolcat"
  * notes = ""
  * notes_url = ""
  * package = "_api"
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 24
    * last_line = 1
    * path = "/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf"
  * templates = [ "lolcat" ]
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf', lines 1:0-1:24
  * type = "HostGroup"
  * vars = null
  * zone = "global-templates"
    % = modified in '/Users/aklimov/NET/WS/icinga2/prefix4/var/lib/icinga2/api/packages/_api/d0b92a71-a839-415c-ac38-2dc47ed2b77a/conf.d/hostgroups/lolcat.conf', lines 3:2-3:26
➜  icinga2 git:(bugfix/message-routing-for-global-zones)
```

**Review by N-o-X — APPROVED** [review]
