### PR TITLE
Process `config::update/delete` cluster events gracefully

### LINKED ISSUE #9721: API ConficSync - Packages - Out of Sync/Missing
## Describe the bug

Due to heavy usage of the API Host/Services creation with relatively long names <128 Characters there seems to be a inconsistency with the API Sync behaviour between the Master and the Satellites.
While on the HA-Masters there seems to be fine, during a fresh Config Sync/Deployment the Satellites seem to receive an inconsistent Config with missing parts on one side and another missing parts on the other side.
This leads to both not accepting the newly provided config due to the missing parts of the config which the partner Satellite received and vice versa.

with missing part on one side and another missing part on the other side

This shows in the Icinga check signaling
```
Last zone sync stage validation failed at 2023-xx-xx 07:52:02 +0100
```

In the Startup.log there is shown what Host/Services are Missing which variates due to the missing other half.
Also the Synced Zone on both Satellite Partners is never the same but should be. 

```
Satellite1 #> ls /var/lib/icinga2/api/packages/_api/*/conf.d/hosts | wc -l
1106
Satellite2 #> ls /var/lib/icinga2/api/packages/_api/*/conf.d/hosts | wc -l
1152
```

The Startup.log shows the missing files .. which have (maybe) a problematic naming scheme ?

```
[2023-03-09 12:28:36 +0100] information/ConfigItem: Committing config item(s).
[2023-03-09 12:28:36 +0100] warning/CheckerComponent: Attribute 'concurrent_checks' for object 'checker' of type 'CheckerComponent' is deprecated and should not be used.
[2023-03-09 12:28:36 +0100] information/ApiListener: My API identity: Satellite1
[2023-03-09 12:28:37 +0100] critical/config: Error: Validation failed for object 'test:dev:test01:aa-rest-functiontest-secure:healthcheck!aa-rest-functiontest-secure:aa-rest-functiontest-secure:test01:dev:secure' of type 'Service'; Attribute 'host_name': Object 'test:dev:test01:aa-rest-functiontest-secure:healthcheck' of type 'Host' does not exist.
Location: in /var/lib/icinga2/api/packages/_api/3cf45951-0f22-495b-855c-59856870f1eb/conf.d/services/test%3Adev%3Atest01%3Aaa-rest-functiontest-secure%3Ahealthcheck%21aa-rest-functiontest-secure%3Aaa-rest-functiontest-secure%3Atest01%3Adev%3Asecure.conf: 4:2-4:69
/var/lib/icinga2/api/packages/_api/3cf45951-0f22-495b-855c-59856870f1eb/conf.d/services/test%3Adev%3Atest01%3Aaa-rest-functiontest-secure%3Ahealthcheck%21aa-rest-functiontest-secure%3Aaa-rest-functiontest-secure%3Atest01%3Adev%3Asecure.conf(2):
...
```

Problematic Host/Service Name consist out of the following schema:
```
test:dev:test01:aa-rest-functiontest-secure:healthcheck!aa-rest-functiontest-secure:aa-rest-functiontest-secure:test01:dev:secure
```
URL Encoded:
```
test%3Adev%3Atest01%3Aaa-rest-functiontest-secure%3Ahealthcheck%21aa-rest-functiontest-secure%3Aaa-rest-functiontest-secure%3Atest01%3Adev%3Asecure
```

Also the Issue seems just to present since the update from version 2.11.x to 2.12.x

## Expected behavior

Config Sync should be working and should sync properly between the config Master and the Satellites Partners without loosing Config (half) to the partner Node/Satellite and also Sync properly the packages folder. 

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.9-1)
* Operating System and version:
OS name | Red Hat Enterprise Linux Server
OS Version | 7.9 (Maipo)
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
```
[2023-03-01 15:15:15 +0100] information/cli: Icinga application loader (version: r2.12.9-1)
[2023-03-01 15:15:15 +0100] information/cli: Loading configuration file(s).
[2023-03-01 15:15:19 +0100] information/ConfigItem: Committing config item(s).
[2023-03-01 15:15:20 +0100] information/ApiListener: My API identity: Master01
[2023-03-01 15:15:29 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 80.2667/s (4816/min 4816/5min 4816/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #6 (InfluxdbWriter, influxdbp01) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #8 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #9 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #7 (InfluxdbWriter, influxdbp02) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:39 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 56, rate: 86.8/s (5208/min 5208/5min 5208/15min);
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 Users.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 68 ScheduledDowntimes.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 7 TimePeriods.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 6323 Zones.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 4 ServiceGroups.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 164214 Services.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 27877 Hosts.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 EventCommands.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 NotificationCommands.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 220503 Notifications.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 345 HostGroups.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 6331 Endpoints.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 924 Downtimes.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 125 Comments.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 11 ApiUsers.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 406 CheckCommands.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 InfluxdbWriters.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2023-03-01 15:16:07 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2023-03-01 15:16:07 +0100] information/cli: Finished validating the configuration file(s).
```

## Additional context
ref/NC/777526

### PR DESCRIPTION
**Pull request by yhabteab**
Since the internal `config::Update` cluster events are using [`ConfigObjectUtility::CreateObject()`](https://github.com/Icinga/icinga2/blob/master/lib/remote/apilistener-configsync.cpp#L123) as well to create received runtime objects, we shouldn't persist the config file first to the disk and then load and validate it with [`ConfigCompiler::CompileFile()`](https://github.com/Icinga/icinga2/blob/master/lib/config/configcompiler.cpp#L259-L264). Otherwise, we are forced to remove the newly created file whenever we can't validate, commit or activate it. This approach would also have the downside that two cluster events for the same object arriving at the same moment from two different endpoints would result in two different threads simultaneously creating and loading the same configuration file - whereby only one of them surpasses the validation process, while the other one is facing an object `re-definition` error and tries to remove that configuration file it mistakenly thinks it has created. As a consequence, an object successfully created by the former is implicitly deleted by the latter thread, causing the objects to mysteriously disappear.

This PR fixes this by preserving the config in a temporary file for the entire validation process and is only moved to the actual config when the object was successfully created, otherwise that temp file will be discarded. Doing so, guarantees that two different threads simultaneously creating and loading the same configuration file do not interfere with each other. When one thread fails to pass object validation, it only deletes its temporary file and does not affect the other thread in any way. This PR additionally prevents two cluster events relating to the same object from being processed simultaneously.

## Tests

<details>
<summary>Master 1</summary>

```bash
object Endpoint "master1" {
}

object Endpoint "master2" {
	host = "IP-Address"
	log_duration = 30m
}

object Zone "master" {
	endpoints = [ "master1", "master2" ]
}

object Endpoint "satellite1" {
	log_duration = 30m
}

object Endpoint "satellite2" {
	log_duration = 30m
}

object Zone "satellite" {
	endpoints = [ "satellite1", "satellite2" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}
```

</details>

<details>
<summary>Master 2</summary>

```bash
object Endpoint "master1" {
//	host = "IP-Address"
//	port = "5665"
	log_duration = 30m
}

object Endpoint "master2" { }

object Zone "master" {
	endpoints = [ "master1", "master2" ]
}

object Endpoint "satellite1" {
	log_duration = 30m
}

object Endpoint "satellite2" {
	log_duration = 30m
}

object Zone "satellite" {
	endpoints = [ "satellite1", "satellite2" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}
```

</details>

<details>
<summary>Satellite</summary>

```bash
object Endpoint "master1" {
	host = "IP"
	port = "5665"
}

object Endpoint "master2" {
	host = "IP"
	port = "5665"
}

object Zone "master" {
	endpoints = [ "master1", "master2" ]
}

object Endpoint "satellite1" {
}

object Endpoint "satellite2" {
	log_duration = 30m
}

object Zone "satellite" {
	endpoints = [ "satellite1", "satellite2" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}
```

</details>

#### Before

<details>
<summary>Master 1</summary>

```bash
root@debian-11:~# ls /var/lib/icinga2/api/packages/_api/9ff3d418-8691-4ca1-aba6-0fe2efec029a/conf.d/hosts/ | wc -l
1000
```

</details>

<details>
<summary>Master 2</summary>

```bash
root@config-sync centos]# ls /var/lib/icinga2/api/packages/_api/97d86dee-d245-468f-b7dc-bd6044376e2a/conf.d/hosts | wc -l
1000
```

</details>

<details>
<summary>Satellite</summary>

```bash
[root@config-sync-2 ~]# ls /var/lib/icinga2/api/packages/_api/fd7da15d-7167-4e25-8da0-21fc97381c1b/conf.d/hosts | wc -l
755
```

To make things even more mysterious, when you query one of the missing hosts via the API, you get the desired result, but it refers to a non-existent path. Nevertheless, the host disappears forever and cannot even be found via the API when the icinga2 daemon is restarted.

```bash
~/Workspace/icinga2 (master ✗) curl -k -s -S -i -u root:icinga 'https://10.27.0.198:5665/v1/objects/hosts/example-197?pretty=1'

{
    "results": [
        {
            "attrs": {
                "__name": "example-197",
            ...
           "source_location": {
                    "first_column": 0,
                    "first_line": 1,
                    "last_column": 24,
                    "last_line": 1,
                    "path": "/var/lib/icinga2/api/packages/_api/fd7da15d-7167-4e25-8da0-21fc97381c1b/conf.d/hosts/example-197.conf"
                },
....
```

```bash
[root@config-sync-2 ~]# cat /var/lib/icinga2/api/packages/_api/fd7da15d-7167-4e25-8da0-21fc97381c1b/conf.d/hosts/example-197.conf
cat: /var/lib/icinga2/api/packages/_api/fd7da15d-7167-4e25-8da0-21fc97381c1b/conf.d/hosts/example-197.conf: Datei oder Verzeichnis nicht gefunden
```

</details>

#### After

**Satellite:**
```bash
root@config-sync-2 ~]# ls /var/lib/icinga2/api/packages/_api/760f4e88-1688-46fd-a017-48905eb7fbb4/conf.d/hosts | wc -l
1000
```

fixes #9721

### CODE REVIEW

File: lib/remote/configobjectutility.cpp [hunk 1]
```diff
@@ -275,6 +274,13 @@ bool ConfigObjectUtility::CreateObject(const Type::Ptr& type, const String& full
 		ConfigObject::Ptr obj = ctype->GetObject(fullName);
 
 		if (obj) {
+			// It's now safe to put the config on the disk as the object has surpassed the compiling/validation processes.
+			Utility::MkDirP(Utility::DirName(path), 0700);
+
+			std::ofstream fp(path.CStr(), std::ofstream::out | std::ostream::trunc);
+			fp << config;
+			fp.close();
+
```
Comment (Al2Klimov) [inline lib/remote/configobjectutility.cpp:283]: What about AtomicFile here? Would make it absolutely bullet proof.

**Review by Al2Klimov — APPROVED** [review]
This could explain

ref/IP/48850

**Comment by yhabteab** [comment]
There's one more point to clarify! Before this PR, faulty objects with the `ignore_on_error` flag set were written to disk, now they are not. Do you think this breaks anything? I mean, if the configuration is broken, why should we even bother saving it to the disk and deleting it when reloading the daemon?
https://github.com/Icinga/icinga2/blob/01a6c4c1ce15184f465a7f0fc309bcf6779cdeb3/lib/cli/daemoncommand.cpp#L314-L317

**Review by Al2Klimov — APPROVED** [review]
I agree.

**Comment by julianbrost** [comment]
> There's one more point to clarify! Before this PR, faulty objects with the `ignore_on_error` flag set were written to disk, now they are not. Do you think this breaks anything? I mean, if the configuration is broken, why should we even bother saving it to the disk and deleting it when reloading the daemon?

You can probably construct cases where the object might survive if it references a object that was temporarily removed before the object was added and is added back before the next reload. But given that `ignore_on_error` API-created objects are somewhat volatile anyways due to possibly being deleted on startup, that should probably be fine.

There's something else where the behavior probably changed: instantiating the object in memory isn't the only operation that can fail, creating the file might fail as well. Please explain what happens in this case. If you want to try it, you probably don't even have to consider the cluster sync, simply observing what happens on the initial node should be enough. Such an error could be induced by removing write permissions for example.

> Since the satellite receives two different events from both masters, it is not possible to avoid such situations, but the object will not be accidentally deleted from disk now.

Not possible? I doubt that, it would need a different approach though.

**Comment by Al2Klimov** [comment]
> There's something else where the behavior probably changed: instantiating the object in memory isn't the only operation that can fail, creating the file might fail as well.

Then what about creating the AtomicFile where the whole file has been created before, but committing where it's created now?

**Comment by yhabteab** [comment]
**Tests with `AtomicFile`:**

```bash
---
[2024-01-26 13:34:27 +0000] critical/ApiListener: Error: Import references unknown template: 'generic-service'
[2024-01-26 13:34:27 +0000] critical/ApiListener: Could not create object 'example-999!service-999':
[2024-01-26 13:34:27 +0000] critical/ApiListener: Error: Import references unknown template: 'generic-service'
[2024-01-26 13:34:27 +0000] critical/ApiListener: Could not create object 'example-1000!service-1000':
[2024-01-26 13:34:27 +0000] critical/ApiListener: Error: Import references unknown template: 'generic-service'
---
```

File sync triggered an Icinga 2 daemon reload:
```bash
---
[2024-01-26 13:34:29 +0000] information/ApiListener: 'api' stopped.
[2024-01-26 13:34:29 +0000] information/ApiListener: 'api' started.
[2024-01-26 13:34:29 +0000] information/ApiListener: Started new listener on '[10.27.0.198]:5665'
---
[2024-01-26 13:34:29 +0000] information/ApiListener: Applying configuration file update for path '/var/lib/icinga2/api/zones-stage/global-templates' (2168 Bytes).
[2024-01-26 13:34:29 +0000] information/ApiListener: Received configuration updates (1) from endpoint 'master2' are equal to production, skipping validation and reload.
[2024-01-26 13:34:31 +0000] critical/ApiListener: Could not create object 'example-602':
[2024-01-26 13:34:31 +0000] critical/ApiListener: Error: Object 'example-602' of type 'Host' re-defined: in /var/lib/icinga2/api/packages/_api/97469d41-cc06-4486-b8c8-788c6ecb3aab/conf.d/hosts/example-602.conf: 1:0-1:24; previous definition: in /var/lib/icinga2/api/packages/_api/97469d41-cc06-4486-b8c8-788c6ecb3aab/conf.d/hosts/example-602.conf: 1:0-1:24
[2024-01-26 13:34:31 +0000] critical/ApiListener: Could not create object 'example-669':
[2024-01-26 13:34:31 +0000] critical/ApiListener: Error: Object 'example-669' of type 'Host' re-defined: in /var/lib/icinga2/api/packages/_api/97469d41-cc06-4486-b8c8-788c6ecb3aab/conf.d/hosts/example-669.conf: 1:0-1:24; previous definition: in /var/lib/icinga2/api/packages/_api/97469d41-cc06-4486-b8c8-788c6ecb3aab/conf.d/hosts/example-669.conf: 1:0-1:24
---
```

```bash
[root@config-sync-2 ~]# ls /var/lib/icinga2/api/packages/_api/97469d41-cc06-4486-b8c8-788c6ecb3aab/conf.d/hosts | wc -l
1000
[root@config-sync-2 ~]# ls /var/lib/icinga2/api/packages/_api/97469d41-cc06-4486-b8c8-788c6ecb3aab/conf.d/services | wc -l
1000
```

**Comment by yhabteab** [comment]
> There's something else where the behavior probably changed: instantiating the object in memory isn't the only operation that can fail, creating the file might fail as well. Please explain what happens in this case. If you want to try it, you probably don't even have to consider the cluster sync, simply observing what happens on the initial node should be enough. Such an error could be induced by removing write permissions for example.

Same inconsistency! Icinga 2 fails with:
```bash
[2024-01-26 14:47:24 +0000] critical/ApiListener: Error: Function call 'mkstemp' for file '/var/lib/icinga2/api/packages/_api/166b6876-61cc-4feb-b10a-0efbe051dc2c/conf.d/hosts/example-2001.conf.tmp.oGHmxh' failed with error code 13, 'Permission denied'
[2024-01-26 14:47:24 +0000] critical/ApiListener: Error: Function call 'mkstemp' for file '/var/lib/icinga2/api/packages/_api/166b6876-61cc-4feb-b10a-0efbe051dc2c/conf.d/hosts/example-2002.conf.tmp.SK6dgw' failed with error code 13, 'Permission denied'
```

However, the objects can still be found via the API!
```bash
~/Workspace/icinga2 (Api-connect_timeout-DNS ✗) curl -k -s -S -i -u root:icinga 'https://10.27.0.198:5665/v1/objects/hosts/example-2001?pretty=1'

---
{
    "results": [
        {
            "attrs": {
                "__name": "example-2001",
                "source_location": {
                    "first_column": 0,
                    "first_line": 1,
                    "last_column": 25,
                    "last_line": 1,
                    "path": "/var/lib/icinga2/api/packages/_api/166b6876-61cc-4feb-b10a-0efbe051dc2c/conf.d/hosts/example-2001.conf"
                },
---
```

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
> > There's something else where the behavior probably changed: instantiating the object in memory isn't the only operation that can fail, creating the file might fail as well.
> 
> Then what about creating the AtomicFile where the whole file has been created before, but committing where it's created now?

Additionally, I'd also _write_ everything ASAP, just as before. Only the _commit_ has to be where it is right now in this PR.

**Comment by Al2Klimov** [comment]
You'd ensure you have the permission (Hello SELinux!) and enough disk space to write the file. Also, while on it, call boost::iostreams::stream#flush() immediately after <<, just to be sure.

**Comment by julianbrost** [comment]
@yhabteab Did you also try what happend when trying that without this PR? That should have returned an error without leaving behind the object in memory.

Also, as your logs show the error twice, I presume you also tested this in the config sync scenario. However, the same difference in behavior should show on the node handling an HTTP request for creating an object. If it couldn't be written to disk before, it wasn't created at all. With this PR, it's created in memory but not persisted on disk (and even though the client probably receives an error in this case, a subsequent GET request would return the object).

**Comment by yhabteab** [comment]
> @yhabteab Did you also try what happend when trying that without this PR? That should have returned an error without leaving behind the object in memory.

**r2.14.2-1):**
```bash
[2024-01-26 15:28:08 +0000] warning/HttpServerConnection: Error while processing HTTP request: Function call 'std::ifstream::open' for file '/var/lib/icinga2/api/packages/_api/166b6876-61cc-4feb-b10a-0efbe051dc2c/conf.d/hosts/example-2001.conf' failed with error code 2, 'No such file or directory'

---
{
    "error": 404,
    "status": "The requested path 'v1/objects/hosts/example-2002' could not be found or the request method is not valid for this path."
}
```

**This PR:** Not, so good!
```bash
{
    "results": [
        {
            "code": 500,
            "errors": [
                "Error: Function call 'mkstemp' for file '/var/lib/icinga2/api/packages/_api/166b6876-61cc-4feb-b10a-0efbe051dc2c/conf.d/hosts/example-2005.conf.tmp.zdkA6q' failed with error code 13, 'Permission denied'\n"
            ],
            "status": "Object could not be created."
        }
    ]
}
```

**Comment by yhabteab** [comment]
> If it couldn't be written to disk before, it wasn't created at all. With this PR, it's created in memory but not persisted on disk (and even though the client probably receives an error in this case, a subsequent GET request would return the object)

Fixed!

**Review by Al2Klimov — APPROVED** [review]
Still not perfect as Icinga could still leave a temp file on crash, but it is an improvement! 👍

File: lib/remote/configobjectutility.cpp [hunk 2]
```diff
@@ -198,13 +199,26 @@ bool ConfigObjectUtility::CreateObject(const Type::Ptr& type, const String& full
 		return false;
 	}
 
+	// AtomicFile doesn't create not yet existing directories, so we have to do it by our ourselves.
```
Comment (julianbrost) [inline lib/remote/configobjectutility.cpp:202]: That's one "our" too much.

File: lib/remote/configobjectutility.cpp [hunk 3]
```diff
@@ -198,13 +199,26 @@ bool ConfigObjectUtility::CreateObject(const Type::Ptr& type, const String& full
...
+	// Given that the internal config::Update cluster events are using this as well to create synced runtime objects,
+	// we don't want to write the config first to the disk and then load and validate it with CompileFile.
+	// Otherwise, we are forced to remove the newly created file whenever we can't validate, commit or activate it,
+	// even if something goes terribly wrong. This approach would also have the downside that two cluster events for
+	// the same object arriving at the same time from two different endpoints would result in two threads simultaneously
+	// creating and loading the same configuration file - whereby only one of them surpasses the validation process,
+	// while the other is facing an object `re-definition` error and tries to remove that configuration file it
+	// mistakenly thinks it has created. As a consequence, an object successfully created by the former is implicitly
+	// deleted by the latter thread, causing the objects to mysteriously disappear.
+	std::unique_ptr<Expression> expr = ConfigCompiler::CompileText(path, config, String(), "_api");
```
Comment (julianbrost) [inline lib/remote/configobjectutility.cpp:221]: That comment sounds more like the reasoning for using `AtomicFile` and has little to do with `CompileText()`, so I'd move it to just before the `AtomicFile` is created.

Also, please boil down the comment to what's relevant for the new code (IMHO: this function can be called concurrently (cluster config, but probably also HTTP requests), `AtomicFile` is used so multiple threads don't affect each other and that that only the one committing the object in-memory also commits the file). How it broke before/what issue it fixes is more something for the commit message and PR description.

**Review by julianbrost — CHANGES_REQUESTED** [review]

**Review by julianbrost — CHANGES_REQUESTED** [review]
This PR makes the result of the object creation more reliable, however, it still shows the following in the logs:

```
[2024-02-13 09:20:31 +0100] critical/ApiListener: Error: Object 'test-sat-a-693' of type 'Host' re-defined: in /var/lib/icinga2/api/packages/_api/c705dc49-038c-474a-9833-5a63b18d96ed/conf.d/hosts/test-sat-a-693.conf: 1:0-1:27; previous definition: in /var/lib/icinga2/api/packages/_api/c705dc49-038c-474a-9833-5a63b18d96ed/conf.d/hosts/test-sat-a-693.conf: 1:0-1:27
Location: in /var/lib/icinga2/api/packages/_api/c705dc49-038c-474a-9833-5a63b18d96ed/conf.d/hosts/test-sat-a-693.conf: 1:0-1:27
[...]
[2024-02-13 09:20:31 +0100] information/ConfigObjectUtility: Created and activated object 'test-sat-a-487' of type 'Host'.
```

So a config sync that's working fine now might still easily log a few hundred critical messages. I think we'd be better off if we didn't try to create the same object concurrently in the first place.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
I agree. Why to show tons of errors where none are?

ref/IP/48850

File: lib/remote/apilistener-configsync.cpp [hunk 4]
```diff
@@ -104,7 +110,32 @@ Value ApiListener::ConfigUpdateObjectAPIHandler(const MessageOrigin::Ptr& origin
 		return Empty;
 	}
 
+	auto isObjectLocked = [&ptype, &objName] {
+		auto type = ApiListener::m_ObjectNames.find(ptype.get());
+		if (type == ApiListener::m_ObjectNames.end()) {
```
Comment (Al2Klimov) [inline lib/remote/apilistener-configsync.cpp:115]: I'd capture _this_ instead of using `ApiListener::`.

File: lib/remote/apilistener-configsync.cpp [hunk 5]
```diff
@@ -104,7 +110,32 @@ Value ApiListener::ConfigUpdateObjectAPIHandler(const MessageOrigin::Ptr& origin
...
+			return false;
+		}
+
+		return type->second.find(objName) != type->second.end();
+	};
+
+	std::unique_lock<std::mutex> lock(m_ObjectNamesMutex);
+	if (isObjectLocked()) {
```
Comment (Al2Klimov) [inline lib/remote/apilistener-configsync.cpp:123]: The _if_ shouldn't be necessary.

File: lib/remote/apilistener-configsync.cpp [hunk 6]
```diff
@@ -258,6 +297,28 @@ Value ApiListener::ConfigDeleteObjectAPIHandler(const MessageOrigin::Ptr& origin
...
+		m_ObjectNamesCV.wait(lock, [&isObjectLocked]{ return !isObjectLocked(); });
+	}
+	// Add object name to the locked list to block all other threads that try to process a message affecting the same object.
+	m_ObjectNames[ptype.get()].emplace(objName);
+
+	Defer unblockAndNotifyOne([&ptype, &objName]{
```
Comment (Al2Klimov) [inline lib/remote/apilistener-configsync.cpp:316]: Isn't _lock_ just for the mapping? Do you have to hold it during the whole delete operation?

File: lib/remote/apilistener-configsync.cpp [hunk 7]
```diff
@@ -113,6 +144,14 @@ Value ApiListener::ConfigUpdateObjectAPIHandler(const MessageOrigin::Ptr& origin
...
 		newObject = true;
 
+		Defer unlockAndNotifyOne([&lock, &ptype, &objName]{
+			m_ObjectNames[ptype.get()].erase(objName);
+			// Release the mutex before notifying a thread, otherwise it will be blocked immediately after being awakened.
+			lock.unlock();
+
+			m_ObjectNamesCV.notify_one();
+		});
+
```
Comment (Al2Klimov) [inline lib/remote/apilistener-configsync.cpp:154]: Why all this? I'd just unconditionally _Defer_, like when deleting below.

File: lib/remote/apilistener-configsync.cpp (hunk 4 above)
Comment (yhabteab) [reply lib/remote/apilistener-configsync.cpp:115]: That's a static method there's no `this`. `ApiListener::` is just some leftover from the previous version

File: lib/remote/apilistener-configsync.cpp (hunk 5 above)
Comment (yhabteab) [reply lib/remote/apilistener-configsync.cpp:123]: > Any thread that intends to wait on a std::condition_variable must:
> 1. Acquire a [std::unique_lock](http://en.cppreference.com/w/cpp/thread/unique_lock)<[std::mutex](http://en.cppreference.com/w/cpp/thread/mutex)> on the mutex used to protect the shared variable.
> 2. Do one of the following:
>    1. Check the condition, in case it was already updated and notified.

[`cppreference`](https://en.cppreference.com/w/cpp/thread/condition_variable) clearly says to do so! Why would you want to enter a thread in a wait mode that doesn't have to?

Comment (Al2Klimov) [reply lib/remote/apilistener-configsync.cpp:123]: And it says that your wait() is equivalent to:

```c++
while (!!isLocked())
{
    wait(lock);
}
```

File: lib/remote/apilistener-configsync.cpp (hunk 7 above)
Comment (yhabteab) [reply lib/remote/apilistener-configsync.cpp:154]: But I want to notify as soon as the new object is successfully created or failing and not waiting for the entire method to complete.

**Review by julianbrost — CHANGES_REQUESTED** [review]
The locking in `ConfigUpdateObjectAPIHandler()` and `ConfigDeleteObjectAPIHandler()` looks similar but not identical. Why? Shouldn't both functions do pretty much the same, i.e. protect a type+name combination from concurrent changes, do their change, unlock the type+name combination?

Also, I think this would greatly benefit from moving it into a separate class rather than inlining the implementation.

File: lib/remote/apilistener-configsync.cpp (hunk 5 above)
Comment (julianbrost) [reply lib/remote/apilistener-configsync.cpp:123]: You didn't quote the "or" branch of the "Do one of the following":

> Use the predicated overload of `wait`, `wait_for`, and `wait_until`, which performs the same three steps.

File: lib/remote/apilistener-configsync.cpp (hunk 7 above)
Comment (julianbrost) [reply lib/remote/apilistener-configsync.cpp:154]: What's the rest of the method? Updating an already existing object? Not sure if doing that concurrently for the same object is a good idea. At least only performing only one config update for an object at the same time sounds like a sensible idea.

Comment (yhabteab) [reply lib/remote/apilistener-configsync.cpp:154]: > What's the rest of the method? Updating an already existing object?

Only if the received object version is newer than the existing one.

File: lib/remote/apilistener-configsync.cpp [hunk 8]
```diff
@@ -104,6 +107,15 @@ Value ApiListener::ConfigUpdateObjectAPIHandler(const MessageOrigin::Ptr& origin
 		return Empty;
 	}
 
+	// Wait for the object name to become available for processing.
+	m_ConfigSyncPolicy->WaitForObject(ptype, objName);
+	// Add object name to the locked list to block all other threads that try to process a message affecting the same object.
+	m_ConfigSyncPolicy->BlockObject(ptype, objName);
```
Comment (julianbrost) [inline lib/remote/apilistener-configsync.cpp:113]: Those two calls should be a single operation. As both calls lock individually, other threads might interfere in between, i.e. a race condition.

File: lib/remote/apilistener-configsync.cpp [hunk 9]
```diff
@@ -462,3 +483,39 @@ void ApiListener::SendRuntimeConfigObjects(const JsonRpcConnection::Ptr& aclient
...
+	{
+		std::unique_lock<std::mutex> lock(m_Mutex);
+		m_Objects[ptype.get()].erase(objName);
+	}
+
+	if (notifyAll) {
+		m_CV.notify_all();
+	} else {
+		m_CV.notify_one();
+	}
```
Comment (julianbrost) [inline lib/remote/apilistener-configsync.cpp:520]: You don't seem to ever set `notifyAll = true`, that seems to be unintentional. Also, I was already wondering before why you used `notify_all()` in some places and `notify_all()` in others. I don't see a way (at least without quite some extra complexity) to ensure that `notify_one()` would wake the correct thread.

File: lib/remote/apilistener.hpp [hunk 10]
```diff
@@ -71,6 +71,22 @@ enum class ApiCapabilities : uint_fast64_t
 	IfwApiCheckCommand = 1u << 1u,
 };
 
+class ConfigSyncRule
```
Comment (julianbrost) [inline lib/remote/apilistener.hpp:74]: I don't really get the name here, why "rule"? Maybe something like `ObjectNameMutex`, as it provides/emulates a mutex per object name.

File: lib/remote/apilistener.hpp [hunk 11]
```diff
@@ -71,6 +71,22 @@ enum class ApiCapabilities : uint_fast64_t
...
+
+	void BlockObject(const Type::Ptr& ptype, const String& objName);
+	void UnBlockNotify(const Type::Ptr& ptype, const String& objName, bool notifyAll = false);
+
+private:
+	bool IsObjectBlocked(const Type::Ptr& ptype, const String& objName);
+
+	std::mutex m_Mutex;
+	std::condition_variable m_CV;
+	std::unordered_map<Type*, std::set<String>> m_Objects;
```
Comment (julianbrost) [inline lib/remote/apilistener.hpp:87]: Maybe rename to `m_Locked` or maybe even `m_LockedObjectNames` to make more clear that being referenced in this map+set means that it's currently locked.

File: lib/remote/apilistener.hpp [hunk 12]
```diff
@@ -257,6 +273,9 @@ class ApiListener final : public ObjectImpl<ApiListener>
 	mutable std::mutex m_ActivePackageStagesLock;
 	std::map<String, String> m_ActivePackageStages;
 
+	/* update/delete object config sync */
+	static std::unique_ptr<ConfigSyncRule> m_ConfigSyncPolicy;
```
Comment (julianbrost) [inline lib/remote/apilistener.hpp:277]: I don't get the naming here either. Also, why a `unique_ptr`?

```suggestion
	/* ensures that at most one create/update/delete is being processed per object at each time */
	mutable ConfigSyncRule m_ObjectConfigChangeLock;
```

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/remote/apilistener.hpp (hunk 12 above)
Comment (yhabteab) [reply lib/remote/apilistener.hpp:277]: Without a pointer, you cannot use a static instance of `ObjectNamesMutex` as a member of `ApiListener`.  Making it `mutable` is also useless, since all methods that access this variable are static.

Comment (julianbrost) [reply lib/remote/apilistener.hpp:277]: > Without a pointer, you cannot use a static instance of `ObjectNamesMutex` as a member of `ApiListener`.

That should be possible. What prevents you from doing so?

> Making it `mutable` is also useless, since all methods that access this variable are static.

They are static, but they are doing `ApiListener::Ptr listener = ApiListener::GetInstance();` anyways.

File: lib/remote/apilistener-configsync.cpp [hunk 13]
```diff
@@ -462,3 +477,53 @@ void ApiListener::SendRuntimeConfigObjects(const JsonRpcConnection::Ptr& aclient
...
 }
+
+/**
+ * Wait for the given object type and name to become available for processing
+ * and lock it again before releasing the lock.
+ *
+ * @param Type::Ptr ptype The type of the object you want to wait for
+ * @param String objName The object name you want to wait for
+ */
+void ObjectNameMutex::WaitForObject(const Type::Ptr& ptype, const String& objName)
```
Comment (julianbrost) [inline lib/remote/apilistener-configsync.cpp:488]: This mixes up the public interface and the implementation details in a way that's confusing, especially here:

> lock it again before releasing the lock

One time, "lock" seems to refer to the locking mechanism provided to the caller once and to the internal `m_Mutex` the other time.

Also, I'd just follow the typical Lock/Unlock naming for the functions, locking is the primary goal here and `std::mutex::lock()` also waits without explicitly having it in the name.

File: lib/remote/apilistener-configsync.cpp [hunk 14]
```diff
@@ -462,3 +477,53 @@ void ApiListener::SendRuntimeConfigObjects(const JsonRpcConnection::Ptr& aclient
...
+ * @param String objName
+ *
+ * @return bool
+ */
+bool ObjectNameMutex::IsObjectBlocked(const Type::Ptr& ptype, const String& objName)
+{
+	auto type = m_LockedObjectNames.find(ptype.get());
+	if (type == m_LockedObjectNames.end()) {
+		return false;
+	}
```
Comment (julianbrost) [inline lib/remote/apilistener-configsync.cpp:511]: This is the cumbersome to check in C++ if a map/set contains an element without (accidentally) inserting it. However, if this wouldn't find the element, it would be inserted in the next step anyways, so IMHO the lock function could just do `auto& locked = m_LockedObjectNames[ptype.get()];` and then use this for all following operations, making them so simple that they don't really need a separate function.

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: lib/remote/apilistener-configsync.cpp [hunk 15]
```diff
@@ -462,3 +477,37 @@ void ApiListener::SendRuntimeConfigObjects(const JsonRpcConnection::Ptr& aclient
...
+	m_LockedObjectNames[ptype.get()].emplace(objName);
+}
+
+/**
+ * Remove the specified object name of the given type from the locked list and notify all waiting threads.
+ *
+ * @param Type::Ptr ptype The type of the object you want to unblock
+ * @param String objName The name of the object you want to unblock
+ */
+void ObjectNameMutex::UnLock(const Type::Ptr& ptype, const String& objName)
```
Comment (julianbrost) [inline lib/remote/apilistener-configsync.cpp:506]: Please call it `Unlock()` as that's a single word and is also how the method is capitalized in `ObjectLock`.

**Review by julianbrost — CHANGES_REQUESTED** [review]

**Review by Al2Klimov — COMMENTED** [review]
Damn, forget to send my review.

File: lib/remote/apilistener.hpp [hunk 16]
```diff
@@ -71,6 +71,18 @@ enum class ApiCapabilities : uint_fast64_t
...
+public:
+	void Lock(const Type::Ptr& ptype, const String& objName);
+	void UnLock(const Type::Ptr& ptype, const String& objName);
+
+private:
+	std::mutex m_Mutex;
+	std::condition_variable m_CV;
+	std::unordered_map<Type*, std::set<String>> m_LockedObjectNames;
+};
+
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply lib/remote/apilistener.hpp:85]: I have absolutely no idea what you're talking about! This class literally locks and unlocks Mutex and you want another Mutex on top of that?

[the remark this answers is not in the document]
Comment (Al2Klimov) [reply lib/remote/apilistener.hpp:85]: Your class is like std::mutex. And I'd like something like std::unique_lock on top. Btw. depending on how you name your methods, you could actually use std::unique_lock itself! 💡

File: lib/remote/apilistener.hpp [hunk 17]
```diff
@@ -71,6 +71,18 @@ enum class ApiCapabilities : uint_fast64_t
...
+class ObjectNameMutex
+{
+public:
+	void Lock(const Type::Ptr& ptype, const String& objName);
+	void UnLock(const Type::Ptr& ptype, const String& objName);
+
+private:
+	std::mutex m_Mutex;
+	std::condition_variable m_CV;
+	std::unordered_map<Type*, std::set<String>> m_LockedObjectNames;
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply lib/remote/apilistener.hpp:83]: Lookup is always `log(n)`, while with `unordered_set` it could be `O(n)`.

File: lib/remote/apilistener-configsync.cpp [hunk 18]
```diff
@@ -462,3 +477,37 @@ void ApiListener::SendRuntimeConfigObjects(const JsonRpcConnection::Ptr& aclient
 	Log(LogInformation, "ApiListener")
 		<< "Finished syncing runtime objects to endpoint '" << endpoint->GetName() << "'.";
 }
+
+/**
+ * Wait for the specified object name of the given type to become available for processing.
+ *
+ * @param Type::Ptr ptype The type of the object you want to wait for
+ * @param String objName The object name you want to wait for
+ */
```
[the remark this answers is not in the document]
Comment (julianbrost) [reply lib/remote/apilistener-configsync.cpp:486]: Feel free to explain why you think that's the case.

For me, the point of this class is to pretty much emulate the following:

```c++
std::map<Type*, std::map<String, std::mutex>> m_ObjectConfigChangeLock;

m_ObjectConfigChangeLock[t][n].lock();
// do some operation
m_ObjectConfigChangeLock[t][n].unlock();
```

But in a way where the maps don't grow over time as they contain everything that was locked at some time in the past.

If you look at `std::mutex` and its documentation, it's primarily about locking, not waiting, which is just a unpleasant thing it sometimes has to do.

File: lib/remote/apilistener.hpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (julianbrost) [reply lib/remote/apilistener.hpp:85]: > This just screams for a RAII style class like CpuBoundWork.

I mean that would be nice to have.

> Especially as there's >1 usage...

Well, the number is 2, so IMHO that's also fine with `Defer`.

> ~Btw. depending on how you name your methods, you could actually use std::unique_lock itself!~

I also thought about that before. Names aren't the only issue here. You can't pass extra parameters and `std::unique_lock` takes a reference to the underlying mutex, whereas with this class, if a name is not locked, there's no memory behind it so nothing that could be referenced.

File: lib/remote/apilistener.hpp (hunk 17 above)
[the remark this answers is not in the document]
Comment (julianbrost) [reply lib/remote/apilistener.hpp:83]: That's the same for `std::unordered_map` and `std::unordered_set`. With both, lookups may become linear with hash collisions (which may happen with a bad hash function (one that just does `return 0;` would be a particularly bad example) or values that were intentionally chosen to result in the same hash value).

Anyways, the number of objects locked at the same time here is limited by the number of connections we accept config from (that's 3), so those data structures won't ever get that big making the exact choice is pretty much irrelevant (I was just wondering why you mixed them).

File: lib/remote/apilistener-configsync.cpp [hunk 19]
```diff
@@ -462,3 +481,37 @@ void ApiListener::SendRuntimeConfigObjects(const JsonRpcConnection::Ptr& aclient
...
+ * @param Type::Ptr ptype The type of the object you want to unlock
+ * @param String objName The name of the object you want to unlock
+ */
+void ObjectNameMutex::Unlock(const Type::Ptr& ptype, const String& objName)
+{
+	{
+		std::unique_lock<std::mutex> lock(m_Mutex);
+		m_LockedObjectNames[ptype.get()].erase(objName);
+	}
+	m_CV.notify_all();
```
Comment (Al2Klimov) [inline lib/remote/apilistener-configsync.cpp:516]: But why the scope?

Comment (yhabteab) [reply lib/remote/apilistener-configsync.cpp:516]: > The notifying thread does not need to hold the lock on the same mutex as the one held by the waiting thread(s). Doing so may be a pessimization, since the notified thread would immediately block again, waiting for the notifying thread to release the lock, though some implementations recognize the pattern and do not attempt to wake up the thread that is notified under lock.

Just read this one in cppreference.

**Review by Al2Klimov — APPROVED** [review]
