### PR TITLE
IcingaDB: Check whether or not cr is nullptr

### LINKED ISSUE #8592: intrusive_ptr assertion failed in Icinga DB while modifying objects using the API
While reproducing #8587, I also noticed the following crash in Icinga DB. This happened while triggering a bug involving undefined behavior, so this might as well be some secondary effect, but that's not immediately obvious for me, so I'm opening this to not forget about this.

```
icinga2: /usr/include/boost/smart_ptr/intrusive_ptr.hpp:199: T* boost::intrusive_ptr<T>::operator->() const [with T = icinga::CheckResult]: Assertion `px != 0' failed.
[2021-01-11 16:08:14 +0000] notice/ApiListener: Relaying 'event::NotificationSentToAllUsers' message
Caught SIGABRT.
Current time: 2021-01-11 16:08:14 +0000

[2021-01-11 16:08:14 +0000] notice/Process: Running command 'sleep' '1': PID 7371
[2021-01-11 16:08:14 +0000] information/Notification: Completed sending 'DowntimeEnd' notification 'host-23442!s21!dummy-service-notification' for checkable 'host-23442!s21' and user 'icingaadmin' using command 'dummy'.
[2021-01-11 16:08:14 +0000] notice/ApiListener: Relaying 'event::NotificationSentUser' message
[2021-01-11 16:08:14 +0000] critical/Application: Icinga 2 has terminated unexpectedly. Additional information can be found in '/var/log/icinga2/crash/report.1610381294.971214'
Context:
	(0) Sending notifications for object 'host-23442!s21'
	(1) Deactivating object 'host-23442!s21!d90c2d04-42a6-42b5-9c15-3599c450ffda' of type 'Downtime'

[2021-01-11 16:08:15 +0000] notice/cli: Seemless worker (PID 68) stopped, stopping as well
```

```
  Application version: v2.12.0-416-gce536ecdc

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 5.10.4-arch2-1
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: bf8250764a61
  OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
Stacktrace:

	(0) libpthread.so.0: <unknown function> (+0x12730) [0x7fe87b619730]
	(1) libc.so.6: gsignal (+0x10b) [0x7fe87abc57bb]
	(2) libc.so.6: abort (+0x121) [0x7fe87abb0535]
	(3) libc.so.6: <unknown function> (+0x2240f) [0x7fe87abb040f]
	(4) libc.so.6: <unknown function> (+0x30102) [0x7fe87abbe102]
	(5) icinga2: boost::intrusive_ptr<icinga::CheckResult>::operator->() const (+0x37) [0x56373629c3c7]
	(6) icinga2: icinga::IcingaDB::SendSentNotification(boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&) (+0x3b9) [0x5637365712a9]
	(7) icinga2: icinga::IcingaDB::NotificationSentToAllUsersHandler(boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&) (+0xcb) [0x56373657a67f]
	(8) icinga2: <unknown function> (+0x21582ea) [0x56373655b2ea]
	(9) icinga2: <unknown function> (+0x2189024) [0x56373658c024]
	(10) icinga2: boost::function8<void, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>::operator()(boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) const (+0xe4) [0x56373639e3c6]
	(11) icinga2: boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, 0u, 1u, 2u, 3u, 4u, 5u, 6u, 7u, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>(boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>&, boost::signals2::detail::unsigned_meta_array<0u, 1u, 2u, 3u, 4u, 5u, 6u, 7u>, std::tuple<boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&> const&, boost::enable_if<boost::is_void<boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>::result_type>, void>::type*) const (+0xc1) [0x563736398d8d]
	(12) icinga2: boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&, 8ul>(boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>&, std::tuple<boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&> const&, mpl_::size_t<8ul>) const (+0x2e) [0x563736390600]
	(13) icinga2: boost::signals2::detail::void_type boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > const&) const (+0x48) [0x56373637983c]
	(14) icinga2: boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >::dereference() const (+0x54) [0x56373635d91e]
	(15) icinga2: boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >::reference boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > const&) (+0x18) [0x5637363427b4]
	(16) icinga2: boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (+0x20) [0x56373631dfdc]
	(17) icinga2: void boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >) const (+0x29) [0x5637362f47e3]
	(18) icinga2: void boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >) const (+0x34) [0x5637362d14c6]
	(19) icinga2: boost::signals2::detail::signal_impl<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::function<void (boost::signals2::connection const&, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) (+0x254) [0x5637362b5412]
	(20) icinga2: boost::signals2::signal<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::function<void (boost::signals2::connection const&, boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr<icinga::Notification> const&, boost::intrusive_ptr<icinga::Checkable> const&, std::set<boost::intrusive_ptr<icinga::User>, std::less<boost::intrusive_ptr<icinga::User> >, std::allocator<boost::intrusive_ptr<icinga::User> > > const&, icinga::NotificationType const&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) (+0x65) [0x5637362a253b]
	(21) icinga2: icinga::Notification::BeginExecuteNotification(icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, bool, bool, icinga::String const&, icinga::String const&) (+0x1f1c) [0x563736234d20]
	(22) icinga2: icinga::Checkable::SendNotifications(icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&) (+0x740) [0x56373619dbc4]
	(23) icinga2: icinga::NotificationComponent::SendNotificationsHandler(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&) (+0x47) [0x5637364ad9bf]
	(24) icinga2: void std::__invoke_impl<void, void (icinga::NotificationComponent::*&)(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&), icinga::NotificationComponent*&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&>(std::__invoke_memfun_deref, void (icinga::NotificationComponent::*&)(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&), icinga::NotificationComponent*&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&) (+0xd6) [0x5637364b8aa4]
	(25) icinga2: std::__invoke_result<void (icinga::NotificationComponent::*&)(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&), icinga::NotificationComponent*&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&>::type std::__invoke<void (icinga::NotificationComponent::*&)(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&), icinga::NotificationComponent*&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&>(void (icinga::NotificationComponent::*&)(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&), icinga::NotificationComponent*&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&) (+0xaa) [0x5637364b82a6]
	(26) icinga2: void std::_Bind<void (icinga::NotificationComponent::*(icinga::NotificationComponent*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>, std::_Placeholder<5>))(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&)>::__call<void, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul>(std::tuple<boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>) (+0x12c) [0x5637364b7a20]
	(27) icinga2: void std::_Bind<void (icinga::NotificationComponent::*(icinga::NotificationComponent*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>, std::_Placeholder<5>))(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&)>::operator()<boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&, void>(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) (+0xcc) [0x5637364b7084]
	(28) icinga2: boost::detail::function::void_function_obj_invoker6<std::_Bind<void (icinga::NotificationComponent::*(icinga::NotificationComponent*, std::_Placeholder<1>, std::_Placeholder<2>, std::_Placeholder<3>, std::_Placeholder<4>, std::_Placeholder<5>))(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&)>, void, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>::invoke(boost::detail::function::function_buffer&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) (+0x78) [0x5637364b5d0e]
	(29) icinga2: boost::function6<void, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>::operator()(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) const (+0xac) [0x56373639b960]
	(30) icinga2: boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, 0u, 1u, 2u, 3u, 4u, 5u, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>(boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>&, boost::signals2::detail::unsigned_meta_array<0u, 1u, 2u, 3u, 4u, 5u>, std::tuple<boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&> const&, boost::enable_if<boost::is_void<boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>::result_type>, void>::type*) const (+0x9b) [0x56373639646b]
	(31) icinga2: boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&, 6ul>(boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>&, std::tuple<boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType&, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&> const&, mpl_::size_t<6ul>) const (+0x2e) [0x56373638af2e]
	(32) icinga2: boost::signals2::detail::void_type boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > const&) const (+0x48) [0x56373636ca6e]
	(33) icinga2: boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >::dereference() const (+0x54) [0x5637363529a8]
	(34) icinga2: boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >::reference boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > const&) (+0x18) [0x563736337846]
	(35) icinga2: boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (+0x20) [0x56373630dc0e]
	(36) icinga2: void boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >) const (+0x29) [0x5637362e53a3]
	(37) icinga2: void boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)> >, boost::signals2::mutex> >) const (+0x34) [0x5637362c6278]
	(38) icinga2: boost::signals2::detail::signal_impl<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::function<void (boost::signals2::connection const&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) (+0x24d) [0x5637362ac6e5]
	(39) icinga2: boost::signals2::signal<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::function<void (boost::signals2::connection const&, boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr<icinga::Checkable> const&, icinga::NotificationType, boost::intrusive_ptr<icinga::CheckResult> const&, icinga::String const&, icinga::String const&, boost::intrusive_ptr<icinga::MessageOrigin> const&) (+0x5d) [0x56373629c463]
	(40) icinga2: icinga::Checkable::NotifyDowntimeEnd(boost::intrusive_ptr<icinga::Downtime> const&) (+0x13a) [0x563736194118]
	(41) icinga2: void std::__invoke_impl<void, void (*&)(boost::intrusive_ptr<icinga::Downtime> const&), boost::intrusive_ptr<icinga::Downtime> const&>(std::__invoke_other, void (*&)(boost::intrusive_ptr<icinga::Downtime> const&), boost::intrusive_ptr<icinga::Downtime> const&) (+0x31) [0x56373639c313]
	(42) icinga2: std::__invoke_result<void (*&)(boost::intrusive_ptr<icinga::Downtime> const&), boost::intrusive_ptr<icinga::Downtime> const&>::type std::__invoke<void (*&)(boost::intrusive_ptr<icinga::Downtime> const&), boost::intrusive_ptr<icinga::Downtime> const&>(void (*&)(boost::intrusive_ptr<icinga::Downtime> const&), boost::intrusive_ptr<icinga::Downtime> const&) (+0x37) [0x563736397029]
	(43) icinga2: void std::_Bind<void (*(std::_Placeholder<1>))(boost::intrusive_ptr<icinga::Downtime> const&)>::__call<void, boost::intrusive_ptr<icinga::Downtime> const&, 0ul>(std::tuple<boost::intrusive_ptr<icinga::Downtime> const&>&&, std::_Index_tuple<0ul>) (+0x48) [0x56373638d062]
	(44) icinga2: void std::_Bind<void (*(std::_Placeholder<1>))(boost::intrusive_ptr<icinga::Downtime> const&)>::operator()<boost::intrusive_ptr<icinga::Downtime> const&, void>(boost::intrusive_ptr<icinga::Downtime> const&) (+0x41) [0x563736370fd5]
	(45) icinga2: boost::detail::function::void_function_obj_invoker1<std::_Bind<void (*(std::_Placeholder<1>))(boost::intrusive_ptr<icinga::Downtime> const&)>, void, boost::intrusive_ptr<icinga::Downtime> const&>::invoke(boost::detail::function::function_buffer&, boost::intrusive_ptr<icinga::Downtime> const&) (+0x33) [0x563736356ca7]
	(46) icinga2: boost::function1<void, boost::intrusive_ptr<icinga::Downtime> const&>::operator()(boost::intrusive_ptr<icinga::Downtime> const&) const (+0x65) [0x56373639f547]
	(47) icinga2: boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)>, 0u, boost::intrusive_ptr<icinga::Downtime> const&>(boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)>&, boost::signals2::detail::unsigned_meta_array<0u>, std::tuple<boost::intrusive_ptr<icinga::Downtime> const&> const&, boost::enable_if<boost::is_void<boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)>::result_type>, void>::type*) const (+0x36) [0x563736399ac4]
	(48) icinga2: boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)>, boost::intrusive_ptr<icinga::Downtime> const&, 1ul>(boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)>&, std::tuple<boost::intrusive_ptr<icinga::Downtime> const&> const&, mpl_::size_t<1ul>) const (+0x2e) [0x563736392890]
	(49) icinga2: boost::signals2::detail::void_type boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > const&) const (+0x48) [0x56373637fa46]
	(50) icinga2: boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> >::dereference() const (+0x54) [0x563736362746]
	(51) icinga2: boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> >::reference boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > const&) (+0x18) [0x563736347aae]
	(52) icinga2: boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (+0x20) [0x563736326414]
	(53) icinga2: void boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> >) const (+0x29) [0x5637362fc1bd]
	(54) icinga2: void boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, boost::intrusive_ptr<icinga::Downtime> const&>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)> >, boost::signals2::mutex> >) const (+0x34) [0x5637362d70e8]
	(55) icinga2: boost::signals2::detail::signal_impl<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)>, boost::function<void (boost::signals2::connection const&, boost::intrusive_ptr<icinga::Downtime> const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr<icinga::Downtime> const&) (+0x202) [0x5637362b9b90]
	(56) icinga2: boost::signals2::signal<void (boost::intrusive_ptr<icinga::Downtime> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (boost::intrusive_ptr<icinga::Downtime> const&)>, boost::function<void (boost::signals2::connection const&, boost::intrusive_ptr<icinga::Downtime> const&)>, boost::signals2::mutex>::operator()(boost::intrusive_ptr<icinga::Downtime> const&) (+0x32) [0x5637362a4cf4]
	(57) icinga2: icinga::Downtime::Stop(bool) (+0xa4) [0x5637361e6260]
	(58) icinga2: icinga::ConfigObject::Deactivate(bool, icinga::Value const&) (+0x1f5) [0x563735d151a3]
	(59) icinga2: icinga::ConfigObjectUtility::DeleteObjectHelper(boost::intrusive_ptr<icinga::ConfigObject> const&, bool, boost::intrusive_ptr<icinga::Array> const&, boost::intrusive_ptr<icinga::Array> const&, icinga::Value const&) (+0x403) [0x563735f6b25b]
	(60) icinga2: icinga::ConfigObjectUtility::DeleteObjectHelper(boost::intrusive_ptr<icinga::ConfigObject> const&, bool, boost::intrusive_ptr<icinga::Array> const&, boost::intrusive_ptr<icinga::Array> const&, icinga::Value const&) (+0x31c) [0x563735f6b174]
	(61) icinga2: icinga::ConfigObjectUtility::DeleteObject(boost::intrusive_ptr<icinga::ConfigObject> const&, bool, boost::intrusive_ptr<icinga::Array> const&, boost::intrusive_ptr<icinga::Array> const&, icinga::Value const&) (+0xe2) [0x563735f6b9ea]

***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***

Failed to launch GDB: No such file or directory
```

This was triggered using the following script (although I only observed this crash once):
```
#!/bin/bash

h="host-$RANDOM"

while true; do

	curl -skSu root:icinga -H 'Accept: application/json' -X PUT "https://127.0.0.1:5665/v1/objects/hosts/$h" -d '{"attrs":{"check_command":"dummy"}}'
	echo

	for s in s{1..100}; do
		curl -skSu root:icinga -H 'Accept: application/json' -X PUT "https://127.0.0.1:5665/v1/objects/services/$h!$s" -d '{"attrs":{"check_command":"dummy"}}'
		echo
	done

	curl -skSu root:icinga -H 'Accept: application/json' -X POST "https://127.0.0.1:5665/v1/actions/schedule-downtime" -d '{"type":"Service", "filter":"host.name==\"'"$h"'\"", "start_time":'$(date +%s)', "end_time":'$(date -d 1hour +%s)', "author":"icingaadmin", "comment":"42", "pretty":true}'
	echo

	sleep 3

	curl -skSu root:icinga -H 'Accept: application/json' -X DELETE "https://127.0.0.1:5665/v1/objects/hosts/$h?cascade=1"
	echo


done
```

The cluster has two master nodes, the crash happened on the primary one, i.e. the config master and the one against which the API queries were executed. It had the following notifications configures:

```
object User "icingaadmin" {
}

object NotificationCommand "dummy" {
	command = ["sleep", "1"]
}

apply Notification "dummy-host-notification" to Host {
	command = "dummy"
	users = ["icingaadmin"]
	assign where true
}

apply Notification "dummy-service-notification" to Service {
	command = "dummy"
	users = ["icingaadmin"]
	assign where true
}
```

### PR DESCRIPTION
**Pull request by Yonas-net**
resolves #8592

### CODE REVIEW

**Review by Al2Klimov — APPROVED** [review]

File: lib/icingadb/icingadb-objects.cpp [hunk 1]
```diff
@@ -1324,7 +1324,7 @@ void IcingaDB::SendSentNotification(
 		"notification_id", GetObjectIdentifier(notification),
 		"host_id", GetObjectIdentifier(host),
 		"type", Convert::ToString(type),
-		"state", Convert::ToString(service ? Convert::ToLong(cr->GetState()) : Convert::ToLong(Host::CalculateState(cr->GetState()))),
+		"state", Convert::ToString(cr ? service ? Convert::ToLong(cr->GetState()) : Convert::ToLong(Host::CalculateState(cr->GetState())) : 99),
```
Comment (julianbrost) [inline lib/icingadb/icingadb-objects.cpp:1327]: I've already seen this magic 99 appear elsewhere in the code. Is there really no constant for this?

Comment (Al2Klimov) [reply lib/icingadb/icingadb-objects.cpp:1327]: Exactly. (If it already appears multiple times, I consider it another construction area.)

**Review by julianbrost — APPROVED** [review]
