### PR TITLE
Fix broken runtime config sync

### LINKED ISSUE #9721: API ConficSync - Packages - Out of Sync/Missing
## Describe the bug

Due to heavy usage of the API Host/Services creation with relatively long names <128 Characters there seems to be a inconsistency with the API Sync behaviour between the Master and the Satellites.
While on the HA-Masters there seems to be fine, during a fresh Config Sync/Deployment the Satellites seem to receive an inconsistent Config with missing parts on one side and another missing parts on the other side.
This leads to both not accepting the newly provided config due to the missing parts of the config which the partner Satellite received and vice versa.

with missing part on one side and another missing part on the other side

This shows in the Icinga check signaling
```
Last zone sync stage validation failed at 2023-xx-xx 07:52:02 +0100
```

In the Startup.log there is shown what Host/Services are Missing which variates due to the missing other half.
Also the Synced Zone on both Satellite Partners is never the same but should be. 

```
Satellite1 #> ls /var/lib/icinga2/api/packages/_api/*/conf.d/hosts | wc -l
1106
Satellite2 #> ls /var/lib/icinga2/api/packages/_api/*/conf.d/hosts | wc -l
1152
```

The Startup.log shows the missing files .. which have (maybe) a problematic naming scheme ?

```
[2023-03-09 12:28:36 +0100] information/ConfigItem: Committing config item(s).
[2023-03-09 12:28:36 +0100] warning/CheckerComponent: Attribute 'concurrent_checks' for object 'checker' of type 'CheckerComponent' is deprecated and should not be used.
[2023-03-09 12:28:36 +0100] information/ApiListener: My API identity: Satellite1
[2023-03-09 12:28:37 +0100] critical/config: Error: Validation failed for object 'test:dev:test01:aa-rest-functiontest-secure:healthcheck!aa-rest-functiontest-secure:aa-rest-functiontest-secure:test01:dev:secure' of type 'Service'; Attribute 'host_name': Object 'test:dev:test01:aa-rest-functiontest-secure:healthcheck' of type 'Host' does not exist.
Location: in /var/lib/icinga2/api/packages/_api/3cf45951-0f22-495b-855c-59856870f1eb/conf.d/services/test%3Adev%3Atest01%3Aaa-rest-functiontest-secure%3Ahealthcheck%21aa-rest-functiontest-secure%3Aaa-rest-functiontest-secure%3Atest01%3Adev%3Asecure.conf: 4:2-4:69
/var/lib/icinga2/api/packages/_api/3cf45951-0f22-495b-855c-59856870f1eb/conf.d/services/test%3Adev%3Atest01%3Aaa-rest-functiontest-secure%3Ahealthcheck%21aa-rest-functiontest-secure%3Aaa-rest-functiontest-secure%3Atest01%3Adev%3Asecure.conf(2):
...
```

Problematic Host/Service Name consist out of the following schema:
```
test:dev:test01:aa-rest-functiontest-secure:healthcheck!aa-rest-functiontest-secure:aa-rest-functiontest-secure:test01:dev:secure
```
URL Encoded:
```
test%3Adev%3Atest01%3Aaa-rest-functiontest-secure%3Ahealthcheck%21aa-rest-functiontest-secure%3Aaa-rest-functiontest-secure%3Atest01%3Adev%3Asecure
```

Also the Issue seems just to present since the update from version 2.11.x to 2.12.x

## Expected behavior

Config Sync should be working and should sync properly between the config Master and the Satellites Partners without loosing Config (half) to the partner Node/Satellite and also Sync properly the packages folder. 

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.9-1)
* Operating System and version:
OS name | Red Hat Enterprise Linux Server
OS Version | 7.9 (Maipo)
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
```
[2023-03-01 15:15:15 +0100] information/cli: Icinga application loader (version: r2.12.9-1)
[2023-03-01 15:15:15 +0100] information/cli: Loading configuration file(s).
[2023-03-01 15:15:19 +0100] information/ConfigItem: Committing config item(s).
[2023-03-01 15:15:20 +0100] information/ApiListener: My API identity: Master01
[2023-03-01 15:15:29 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 80.2667/s (4816/min 4816/5min 4816/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #6 (InfluxdbWriter, influxdbp01) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #8 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #9 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:30 +0100] information/WorkQueue: #7 (InfluxdbWriter, influxdbp02) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2023-03-01 15:15:39 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 56, rate: 86.8/s (5208/min 5208/5min 5208/15min);
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 Users.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 68 ScheduledDowntimes.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 7 TimePeriods.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 6323 Zones.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 4 ServiceGroups.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 164214 Services.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 27877 Hosts.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 EventCommands.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 NotificationCommands.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 220503 Notifications.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 345 HostGroups.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 6331 Endpoints.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 924 Downtimes.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 125 Comments.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 11 ApiUsers.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 406 CheckCommands.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 2 InfluxdbWriters.
[2023-03-01 15:16:06 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2023-03-01 15:16:07 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2023-03-01 15:16:07 +0100] information/cli: Finished validating the configuration file(s).
```

## Additional context
ref/NC/777526

### LINKED ISSUE #10012: Runtime created objects don't get synced
## Describe the bug

https://github.com/Icinga/icinga2/pull/9980/commits/008fcd1744a08342271ed374aeaf94b0433b7c82 changed the creation process for runtime objects and retains their config in a temporary file. After the object has been successfully created and activated, the temporary file is moved to the actual config file (which is known by the config compiler), otherwise it is simply discarded. However, since the object activation triggers an `OnActiveChanged` event, it tries to sync the configuration with the other endpoint. Doing this works well if the endpoints are connecting after the object has been created, but not if they are already connected. This is because when sending the config update, it is going to access the configuration file of the recently created object, but as its config is still in the temporary file, it won't find it, thus it won't be able to sync it.

https://github.com/Icinga/icinga2/blob/d551eaea273e4159d7acb4f5a03eda478ecf4730/lib/remote/apilistener-configsync.cpp#L354-L356

### PR DESCRIPTION
**Pull request by yhabteab**
Basically the same as in #9980, but this PR additionally prohibits concurrent API requests targeting the same object. Consequently, no API request is being processed for an object whilst processing a cluster "config update/delete" event for that very same object and vice versa.

## Tests

<details>
<summary>Master 1</summary>

```bash
object Endpoint "master1" {
}

object Endpoint "master2" {
	host = "IP-Address"
	log_duration = 30m
}

object Zone "master" {
	endpoints = [ "master1", "master2" ]
}

object Endpoint "satellite1" {
	log_duration = 30m
}

object Endpoint "satellite2" {
	log_duration = 30m
}

object Zone "satellite" {
	endpoints = [ "satellite1", "satellite2" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}
```

</details>

<details>
<summary>Master 2</summary>

```bash
object Endpoint "master1" {
//	host = "IP-Address"
//	port = "5665"
	log_duration = 30m
}

object Endpoint "master2" { }

object Zone "master" {
	endpoints = [ "master1", "master2" ]
}

object Endpoint "satellite1" {
	log_duration = 30m
}

object Endpoint "satellite2" {
	log_duration = 30m
}

object Zone "satellite" {
	endpoints = [ "satellite1", "satellite2" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}
```

</details>

<details>
<summary>Satellite</summary>

```bash
object Endpoint "master1" {
	host = "IP"
	port = "5665"
}

object Endpoint "master2" {
	host = "IP"
	port = "5665"
}

object Zone "master" {
	endpoints = [ "master1", "master2" ]
}

object Endpoint "satellite1" {
}

object Endpoint "satellite2" {
	log_duration = 30m
}

object Zone "satellite" {
	endpoints = [ "satellite1", "satellite2" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}
```

</details>

Start both masters and create some objects via the API, wait until the two masters have synchronised their configuration and then start the satellite.

### Tests for #10012

Start two Icinga endpoints that are connected to each other and must accept config updates from each other (`accept_config = true`).

```bash
for j in {1..100} ; do
    curl -k -s -S -i -u root:icinga -H 'Accept: application/json' \
    -X PUT "https://localhost:5665/v1/objects/hosts/example-$j" \
    -d '{ "templates": [ "generic-host" ], "attrs": { "address": "127.0.0.1", "check_command": "hostalive", "vars.os" : "Linux" }, "pretty": true }'
done
```
It doesn't silently aborts the synchronisation attempts.

fixes #9721

### CODE REVIEW

**Comment by julianbrost** [comment]
This looks like it significantly changes what was only added in #9980. If it stays that way, it might make sense to revert #9980 as a whole and make a complete new attempt. That would make the backport of this cleaner (as you wouldn't have to backport a commit and its reversion at once).

What's the reason for moving `ObjectNameMutex` to `types.{hpp,cpp}`?

ceab5a6f5276d40db7c4eb75e9a596791ebaa88a seems to add a second independent `ObjectNameMutex`. What's the reason for that, shouldn't this use the same one?

**Comment by yhabteab** [comment]
> What's the reason for moving `ObjectNameMutex` to `types.{hpp,cpp}`?

Well, my first thought was that we might be using it even more than we thought in https://github.com/Icinga/icinga2/pull/9980, and that it might introduce a circular dependency. However, if you are strongly against it, then of course I can undo it.

> [ceab5a6](https://github.com/Icinga/icinga2/commit/ceab5a6f5276d40db7c4eb75e9a596791ebaa88a) seems to add a second independent `ObjectNameMutex`. What's the reason for that, shouldn't this use the same one?

Feels strange to use the same mutex for the cluster config sync and the API request. Otherwise, there's nothing against it, I guess.

**Comment by yhabteab** [comment]
> > [ceab5a6](https://github.com/Icinga/icinga2/commit/ceab5a6f5276d40db7c4eb75e9a596791ebaa88a) seems to add a second independent `ObjectNameMutex`. What's the reason for that, shouldn't this use the same one?
> 
> Feels strange to use the same mutex for the cluster config sync and the API request. Otherwise, there's nothing against it, I guess.

Plus `ConfigObjectUtility:CreateObject()` can also be used without an API listener.

**Comment by julianbrost** [comment]
> Well, my first thought was that we might be using it even more than we thought in #9980, and that it might introduce a circular dependency. However, if you are strongly against it, then of course I can undo it.

I mainly asked the question because if it is moved, it's more code that was added in #9980 that wouldn't stay the way it was added there. So if it's moved, that would be more reason for me to revert #9980 completely and do a clean new PR. (I haven't looked at the PR in enough detail to assess whether it should be moved.)

> Feels strange to use the same mutex for the cluster config sync and the API request. Otherwise, there's nothing against it, I guess.

Why does it feel strange? Think of what this mutex is supposed to protect: the consistency of the configuration of a specific object. So anything that attempts to modify the object at runtime should use the same mutex.

Imagine someone would send a `PUT /v1/objects/hosts/foo` request to Master 1 and then the same HTTP request to Master 2 at about the same it receives the JSON-RPC request from Master 1 to create the object. Should both requests be processed at the same time on Master 2?

> Plus `ApiListener::ConfigUpdateObjectAPIHandler()` calls `CreateObject()` while holding a lock on that object and its type, so that's a good reason not to use the same mutex, I'd say.

Does the locking in `ConfigUpdateObjectAPIHandler()` actually do anything useful anymore, or would the locking performed in `CreateObject()` already suffice for `ConfigUpdateObjectAPIHandler()`?

**Comment by yhabteab** [comment]
> Does the locking in `ConfigUpdateObjectAPIHandler()` actually do anything useful anymore,

IMHO yes, it does! It acquires the lock before it does `ctype->GetObject(objName);`, which would cause two config updates to think the object doesn't exist yet and try to create it when it doesn't.

>  or would the locking performed in CreateObject() already suffice for ConfigUpdateObjectAPIHandler()?

That would be too late for the cluster config sync part.

**Comment by julianbrost** [comment]
> > Feels strange to use the same mutex for the cluster config sync and the API request. Otherwise, there's nothing against it, I guess.
> 
> Why does it feel strange? Think of what this mutex is supposed to protect: the consistency of the configuration of a specific object. So anything that attempts to modify the object at runtime should use the same mutex.
> 
> Imagine someone would send a `PUT /v1/objects/hosts/foo` request to Master 1 and then the same HTTP request to Master 2 at about the same it receives the JSON-RPC request from Master 1 to create the object. Should both requests be processed at the same time on Master 2?

What about that part? Currently, the PR adds different locking based on whether an object is created via HTTP or JSON-RPC. Both would create the same object though, so both should use the same locking. Wouldn't you end up with race conditions between HTTP and JSON-RPC otherwise?

**Comment by yhabteab** [comment]
> What about that part? Currently, the PR adds different locking based on whether an object is created via HTTP or JSON-RPC. Both would create the same object though, so both should use the same locking. Wouldn't you end up with race conditions between HTTP and JSON-RPC otherwise?

I don't think so! In case of a JSON-RPC connection, the object is locked twice! There is only one case in which a race condition may occur. This's when the API request enters `CreateObject()`, while the cluster sync takes place in this part of the code. It's hard to trigger, I'd say!
https://github.com/Icinga/icinga2/blob/a259a68e353dfdf10b2c778f35358b7e41de45aa/lib/remote/apilistener-configsync.cpp#L117-L133

**Comment by yhabteab** [comment]
I've tested all use the cases of the config sync and it is working perfectly now. However, we still need to address the use of `ObjectNameMutex` in the `modifyobjecthandler.cpp` file, particularly whether it is even necessary to lock the object name there.

**Comment by julianbrost** [comment]
> However, we still need to address the use of `ObjectNameMutex` in the `modifyobjecthandler.cpp` file, particularly whether it is even necessary to lock the object name there.

Some synchronization has to happen there for sure. Am I missing something or isn't even using `ObjectLock` so that two post requests that modify the same object could result in some race condition?

At first glance, `ObjectNameMutex` also doesn't sound like a bad idea there. That will prevent both starting a modification before the object was fully created and triggering a deletion while the modification is still being processed.

**Comment by yhabteab** [comment]
> Am I missing something or isn't even using `ObjectLock` so that two post requests that modify the same object could result in some race condition?

There is no `olock` on the actual configuration object, but only on the `restore_attributes` and these acquired in `RestoreAttribute()`.

File: lib/remote/configobjectslock.hpp [hunk 1]
```diff
@@ -69,4 +74,29 @@ class ConfigObjectsSharedLock
...
+
+	~ObjectNameLock();
+
+private:
+	String m_ObjectName;
+	Type::Ptr m_Type;
+
+	static std::mutex m_Mutex;
+	static std::condition_variable m_CV;
+	static std::map<Type*, std::set<String>> m_LockedObjectNames;
```
Comment (Al2Klimov) [inline lib/remote/configobjectslock.hpp:99]: Consider unordered_{map,set}.

Comment (julianbrost) [reply lib/remote/configobjectslock.hpp:99]: The exact types won't matter that much here as the overall size of those containers will stay rather small anyways.

For completeness, as I already talked with @yhabteab about it: I was thinking about maybe making this a `std::set<std::pair<Type*, String>>` instead (or `std::unordered_set` for that matter, there won't be much of a difference), as that would reduce the map + set operations down to just the set operations. But this seems to bring no huge improvements for simplifying the code (which would have been my motivation here, not performance).

File: lib/remote/configobjectutility.cpp [hunk 2]
```diff
@@ -198,11 +200,15 @@ bool ConfigObjectUtility::CreateObject(const Type::Ptr& type, const String& full
...
 
-	std::ofstream fp(path.CStr(), std::ofstream::out | std::ostream::trunc);
-	fp << config;
-	fp.close();
+	AtomicFile::Write(path, 0644, config);
+
+	Defer removeConfigPath([&path]{
+		// Something went wrong so remove the object's config accordingly.
+		Utility::Remove(path);
+	});
```
Comment (julianbrost) [inline lib/remote/configobjectutility.cpp:211]: Minor detail: you could move the comment out of the lambda and make it say that it's to remove the file in all the error cases and that the defer is cancelled on success so that the file is persisted in this case.

**Review by julianbrost — CHANGES_REQUESTED** [review]
Looks fine in general to me. One commit message refers to the outdated class name `ObjectNameMutex` though. And if you're touching the PR anyways, you might do a slight improvement to one of the comments (see my inline comment).

**Comment by tbauriedel** [comment]
ref/NC/804054

**Review by Al2Klimov — DISMISSED** [review]

**Comment by julianbrost** [comment]
I'm somewhat confused how PRs and issues belong together here.

> This PR kind of reverts [008fcd1](https://github.com/Icinga/icinga2/commit/008fcd1744a08342271ed374aeaf94b0433b7c82)

That part of the PR description is outdated, isn't it? That was already reverted in #10018.

If I understand correctly, #10012 describes the problem introduced by #9980 and was thus fixed with the revert in #10018. What remains is the original issue from #9721 where this PR is now the second attempt to fix it.

Therefor, I'd do the following:

- Close #10012 as "fixed by #10018"
- Change this PR to "fixes #9721"

Do you agree that this correctly represents the current state of these issues and PRs?

**Comment by yhabteab** [comment]
Done! I've also just rebased the PR!

File: lib/remote/configobjectslock.cpp [hunk 3]
```diff
@@ -22,3 +25,37 @@ ConfigObjectsSharedLock::ConfigObjectsSharedLock(std::try_to_lock_t)
...
+{
+	std::unique_lock<std::mutex> lock(m_Mutex);
+	m_CV.wait(lock, [this]{
+		auto& locked = m_LockedObjectNames[m_Type.get()];
+		return locked.find(m_ObjectName) == locked.end();
+	});
+
+	// Add object name to the locked list again to block all other threads that try
+	// to process a message affecting the same object.
+	m_LockedObjectNames[ptype.get()].emplace(objName);
```
Comment (julianbrost) [inline lib/remote/configobjectslock.cpp:51]: I don't understand why the comment says "again".

**Review by julianbrost — CHANGES_REQUESTED** [review]
Can you please provide instructions how to test this? Probably similar to #9980 but even that PR description misses information on when to create objects via the API and when to restart what. Additionally, how can one test now that this doesn't have the same problem as #10012?

File: lib/remote/apilistener-configsync.cpp [hunk 4]
```diff
@@ -8,6 +8,7 @@
 #include "base/json.hpp"
 #include "base/convert.hpp"
 #include "config/vmops.hpp"
+#include "remote/configobjectslock.hpp"
 #include <fstream>
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply lib/remote/apilistener-configsync.cpp:12]: Well, they are wrong since `remote/` comes after `base/` and `config/` and I didn't want to change that.

File: lib/remote/configobjectslock.cpp (hunk 3 above)
Comment (yhabteab) [reply lib/remote/configobjectslock.cpp:51]: Do you reach that point if the `objectName` is already in the `m_LockedObjectNames` map? No, so insert it *again* to block all other waiting threads. It's that simple!

Comment (julianbrost) [reply lib/remote/configobjectslock.cpp:51]: "Again" sounds like it was important that it was in there before. That's not the case as you can lock an object for the first time, and even if it's the second time, that's not relevant for anything here.

File: lib/remote/apilistener-configsync.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (julianbrost) [reply lib/remote/apilistener-configsync.cpp:12]: I knew there was some special ordering documented, but seems like this would only apply to `remote/apilistener.hpp` here, not `remote/*` (as I initially thought without looking it up): https://icinga.com/docs/icinga-2/latest/doc/21-development/#source

**Comment by K0nne** [comment]
Are there any updates on this? The configsync between our configmasters has died again.

**Review by julianbrost — APPROVED** [review]
I did a slightly different test for this PR which both tests for the original issue (#9721) and the new temporarily introduced one (#10012):

Take a cluster with a HA master zone (master-1, master-2) and a satellite zone, shouldn't matter if it's HA, in my case it was (zone satallite-a with nodes satellite-a-1 and satellite-a-2). Next, stop all satellites and run the loop from the PR with a slight modification to add the objects in the satellite-a zone (i.e. add `"zone": "satellite-a"` to the JSON attributes). Finally, after the objects were created, start the satellites again and observe how many of the newly created hosts were synced to which node.

## v2.14.2

Sync to the online master works reliably, sync on reconnect to the satellites that were offline when the objects were created is unreliable (i.e. demonstrates the original issue #9721).

Number of test hosts present in `/var/lib/icinga2/api/packages/_api/` per node:

```
    100 master-1
    100 master-2
     72 satellite-a-1
     95 satellite-a-2
```

## 04ef105caa2765c8b679d3f49692c68f3627ebf8 (merge commit of #9980)

Sync on reconnect worked fine with that, however it broke the online sync (i.e. demonstrates the temporarily introduced issue 10012):

```
    100 master-1
      0 master-1
    100 satellite-a-1
    100 satellite-a-2
```

## This PR

Now all nodes receive and store their config:

```
    100 master-1
    100 master-2
    100 satellite-a-1
    100 satellite-a-2
```
