### PR TITLE
Icinga DB: on every check result update state only 1x, not 3x in a row

### LINKED ISSUE #9501: On every check result Icinga DB updates state 3x in a row
## Describe the bug

On every check Icinga 2

1. updates next check in advance (to un-due the checkable in the next check based due index of the checker) and triggers hooks for that
2. actually runs the check
3. finally updates next check and triggers hooks for that
4. triggers hooks for the new check result

in the same second and the Icinga DB feature provides hooks for both events which – both! –

1. update icinga:nextupdate:$TYPE (for overdue)
2. update icinga:$TYPE:state

## To Reproduce

1. Get (literally) only one host
2. Turn on Icinga DB
3. Watch `redis-cli monitor |grep -v icinga:stats`

```
1661518091.374926 [0 127.0.0.1:48288] "HSET" "icinga:host:state" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "{\"check_attempt\":1,\"check_commandline\":\"'random'\",\"check_source\":\"aklimov-42584.novalocal\",\"check_timeout\":60000,\"environment_id\":\"def27cba1e92155b421f34e09d96cf82a13950e5\",\"execution_time\":0,\"hard_state\":0,\"host_id\":\"3ed405d82247dc00a4ffb00b531de75dd44d7c45\",\"id\":\"3ed405d82247dc00a4ffb00b531de75dd44d7c45\",\"in_downtime\":false,\"is_acknowledged\":0,\"is_active\":true,\"is_flapping\":false,\"is_handled\":false,\"is_problem\":false,\"is_reachable\":true,\"last_state_change\":1661518082145,\"last_update\":1661518082145,\"latency\":0,\"next_check\":1661518100525,\"next_update\":1661518110526,\"normalized_performance_data\":\"time=1661518082.145002 value=538 value_1m=484.200000 value_5m=430.400000 uptime=26.780809\",\"output\":\"Hello from aklimov-42584.novalocal. Icinga 2 has been running for 26 seconds. Version: r2.13.5-1\",\"performance_data\":\"time=1661518082.145002 value=538 value_1m=484.200000 value_5m=430.400000 uptime=26.780809\",\"previous_hard_state\":1,\"previous_soft_state\":1,\"scheduling_source\":\"aklimov-42584.novalocal\",\"severity\":0,\"soft_state\":0,\"state_type\":1}"
1661518091.375024 [0 127.0.0.1:48288] "HSET" "icinga:checksum:host:state" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "{\"checksum\":\"6b7e0f9995fe2bce4f1addaabc88985a62615465\"}"
1661518091.375049 [0 127.0.0.1:48288] "ZADD" "icinga:nextupdate:host" "1661518110.526364" "3ed405d82247dc00a4ffb00b531de75dd44d7c45"
1661518091.375058 [0 127.0.0.1:48288] "HSET" "icinga:host:state" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "{\"check_attempt\":1,\"check_commandline\":\"'random'\",\"check_source\":\"aklimov-42584.novalocal\",\"check_timeout\":60000,\"environment_id\":\"def27cba1e92155b421f34e09d96cf82a13950e5\",\"execution_time\":0,\"hard_state\":1,\"host_id\":\"3ed405d82247dc00a4ffb00b531de75dd44d7c45\",\"id\":\"3ed405d82247dc00a4ffb00b531de75dd44d7c45\",\"in_downtime\":false,\"is_acknowledged\":0,\"is_active\":true,\"is_flapping\":false,\"is_handled\":false,\"is_problem\":true,\"is_reachable\":true,\"last_state_change\":1661518091335,\"last_update\":1661518091335,\"latency\":0,\"next_check\":1661518100525,\"next_update\":1661518110526,\"normalized_performance_data\":\"time=1661518091.335494 value=432 value_1m=388.800000 value_5m=345.600000 uptime=35.971301\",\"output\":\"Hello from aklimov-42584.novalocal. Icinga 2 has been running for 35 seconds. Version: r2.13.5-1\",\"performance_data\":\"time=1661518091.335494 value=432 value_1m=388.800000 value_5m=345.600000 uptime=35.971301\",\"previous_hard_state\":0,\"previous_soft_state\":0,\"scheduling_source\":\"aklimov-42584.novalocal\",\"severity\":2112,\"soft_state\":1,\"state_type\":1}"
1661518091.375138 [0 127.0.0.1:48288] "HSET" "icinga:checksum:host:state" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "{\"checksum\":\"c36939a63fac73c805d9b86f9d866ccd796018f3\"}"
1661518091.375152 [0 127.0.0.1:48288] "ZADD" "icinga:nextupdate:host" "1661518110.526507" "3ed405d82247dc00a4ffb00b531de75dd44d7c45"
1661518091.375160 [0 127.0.0.1:48288] "HSET" "icinga:host:state" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "{\"check_attempt\":1,\"check_commandline\":\"'random'\",\"check_source\":\"aklimov-42584.novalocal\",\"check_timeout\":60000,\"environment_id\":\"def27cba1e92155b421f34e09d96cf82a13950e5\",\"execution_time\":0,\"hard_state\":1,\"host_id\":\"3ed405d82247dc00a4ffb00b531de75dd44d7c45\",\"id\":\"3ed405d82247dc00a4ffb00b531de75dd44d7c45\",\"in_downtime\":false,\"is_acknowledged\":0,\"is_active\":true,\"is_flapping\":false,\"is_handled\":false,\"is_problem\":true,\"is_reachable\":true,\"last_state_change\":1661518091335,\"last_update\":1661518091335,\"latency\":0,\"next_check\":1661518100525,\"next_update\":1661518110526,\"normalized_performance_data\":\"time=1661518091.335494 value=432 value_1m=388.800000 value_5m=345.600000 uptime=35.971301\",\"output\":\"Hello from aklimov-42584.novalocal. Icinga 2 has been running for 35 seconds. Version: r2.13.5-1\",\"performance_data\":\"time=1661518091.335494 value=432 value_1m=388.800000 value_5m=345.600000 uptime=35.971301\",\"previous_hard_state\":0,\"previous_soft_state\":0,\"scheduling_source\":\"aklimov-42584.novalocal\",\"severity\":2112,\"soft_state\":1,\"state_type\":1}"
1661518091.375235 [0 127.0.0.1:48288] "HSET" "icinga:checksum:host:state" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "{\"checksum\":\"c36939a63fac73c805d9b86f9d866ccd796018f3\"}"
1661518091.375246 [0 127.0.0.1:48288] "ZADD" "icinga:nextupdate:host" "1661518110.526507" "3ed405d82247dc00a4ffb00b531de75dd44d7c45"
1661518091.375294 [0 127.0.0.1:48288] "XADD" "icinga:runtime:state" "MAXLEN" "~" "1000000" "*" "runtime_type" "upsert" "redis_key" "icinga:host:state" "checksum" "c36939a63fac73c805d9b86f9d866ccd796018f3" "check_attempt" "1" "check_commandline" "'random'" "check_source" "aklimov-42584.novalocal" "check_timeout" "60000" "environment_id" "def27cba1e92155b421f34e09d96cf82a13950e5" "execution_time" "0" "hard_state" "1" "host_id" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "id" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "in_downtime" "0" "is_acknowledged" "0" "is_active" "1" "is_flapping" "0" "is_handled" "0" "is_problem" "1" "is_reachable" "1" "last_state_change" "1661518091335" "last_update" "1661518091335" "latency" "0" "next_check" "1661518100525" "next_update" "1661518110526" "normalized_performance_data" "time=1661518091.335494 value=432 value_1m=388.800000 value_5m=345.600000 uptime=35.971301" "output" "Hello from aklimov-42584.novalocal. Icinga 2 has been running for 35 seconds. Version: r2.13.5-1" "performance_data" "time=1661518091.335494 value=432 value_1m=388.800000 value_5m=345.600000 uptime=35.971301" "previous_hard_state" "0" "previous_soft_state" "0" "scheduling_source" "aklimov-42584.novalocal" "severity" "2112" "soft_state" "1" "state_type" "1"
1661518091.377448 [0 127.0.0.1:48288] "XADD" "icinga:history:stream:state" "*" "id" "5cc3f9cd8b3dfa921c3ecbfc7ad75b3be1ea439c" "environment_id" "def27cba1e92155b421f34e09d96cf82a13950e5" "host_id" "3ed405d82247dc00a4ffb00b531de75dd44d7c45" "state_type" "1" "soft_state" "1" "hard_state" "1" "check_attempt" "1" "previous_soft_state" "0" "previous_hard_state" "0" "max_check_attempts" "1" "event_time" "1661518091335" "event_id" "00f435c46a9b735b46b70967ef6910e5f7f2ca29" "event_type" "state_change" "output" "Hello from aklimov-42584.novalocal. Icinga 2 has been running for 35 seconds. Version: r2.13.5-1" "check_source" "aklimov-42584.novalocal" "scheduling_source" "aklimov-42584.novalocal" "object_type" "host" "endpoint_id" "a729e277505116d6b965144a43a0aecb360f6d56"
```

## Expected behavior

One ZADD, one HSET per check result.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.13.5
* Operating System and version: CentOS 7
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

ref/IP/42584

### PR DESCRIPTION
**Pull request by Al2Klimov**
Before (time: vertical, stack: horizontal):

* Checkable::ExecuteCheck
  * Checkable::UpdateNextCheck
    * IcingaDB::NextCheckChangedHandler
      * HSET icinga:host:state
      * HSET icinga:checksum:host:state
      * ZADD icinga:nextupdate:host
  * RandomCheckTask::ScriptFunc
    * Checkable::ProcessCheckResult
      * Checkable::UpdateNextCheck
        * IcingaDB::NextCheckChangedHandler
          * HSET icinga:host:state
          * HSET icinga:checksum:host:state
          * ZADD icinga:nextupdate:host
      * IcingaDB::NewCheckResultHandler
        * HSET icinga:host:state
        * HSET icinga:checksum:host:state
        * ZADD icinga:nextupdate:host
  * IcingaDB::StateChangeHandler
    * XADD icinga:runtime:state
    * IcingaDB::ForwardHistoryEntries
      * XADD icinga:history:stream:state

After:

* Checkable::ExecuteCheck
  * Checkable::UpdateNextCheck
    * IcingaDB::NextCheckChangedHandler
  * RandomCheckTask::ScriptFunc
    * Checkable::ProcessCheckResult
      * Checkable::UpdateNextCheck
        * IcingaDB::NextCheckChangedHandler
      * IcingaDB::NewCheckResultHandler
        * HSET icinga:host:state
        * HSET icinga:checksum:host:state
        * ZADD icinga:nextupdate:host
  * IcingaDB::StateChangeHandler
    * XADD icinga:runtime:state
    * IcingaDB::ForwardHistoryEntries
      * XADD icinga:history:stream:state

The first state + nextupdate (for overdue) update comes from next_check being
set to now + interval immediately before doing the actual check (not to trigger
it twice). This update is not only not important for the end user, but even
inappropriate. The end user SHALL see next_check being e.g. in -4s, not 5m, as
the check is running at the moment.

The second one is just redundant as IcingaDB::NewCheckResultHandler (the third
one) is called anyway and will update state + nextupdate as well.

fixes #9501

## Awesome

```
1662388048.691010 [0 127.0.0.1:50579] "HSET" "icinga:host:state" "9b5bb23ddee640aeb6f2e71be4336655ae3bd036" "{\"check_attempt\":1,\"check_commandline\":\"'random'\",\"check_source\":\"alexandersmbp2.int.netways.de\",\"check_timeout\":60000,\"environment_id\":\"dd1de01a2760747f4e82bf7fec93477dcb13e09c\",\"execution_time\":2,\"hard_state\":1,\"host_id\":\"9b5bb23ddee640aeb6f2e71be4336655ae3bd036\",\"id\":\"9b5bb23ddee640aeb6f2e71be4336655ae3bd036\",\"in_downtime\":false,\"is_acknowledged\":0,\"is_active\":true,\"is_flapping\":false,\"is_handled\":false,\"is_problem\":true,\"is_reachable\":true,\"last_state_change\":1662388039211,\"last_update\":1662388048686,\"latency\":3,\"next_check\":1662388058157,\"next_update\":1662388068168,\"normalized_performance_data\":\"time=1662388048.686628 value=590 value_1m=531 value_5m=472 uptime=9.477065\",\"output\":\"Hello from alexandersmbp2.int.netways.de. Icinga 2 has been running for 9 seconds. Version: v2.13.0-425-g60eb41ce9\",\"performance_data\":\"time=1662388048.686628 value=590 value_1m=531 value_5m=472 uptime=9.477065\",\"previous_hard_state\":0,\"previous_soft_state\":0,\"scheduling_source\":\"alexandersmbp2.int.netways.de\",\"severity\":2112,\"soft_state\":1,\"state_type\":1}"
1662388048.691232 [0 127.0.0.1:50579] "HSET" "icinga:checksum:host:state" "9b5bb23ddee640aeb6f2e71be4336655ae3bd036" "{\"checksum\":\"5dcfed0c38d806df8f97353e24998fe5cefbe782\"}"
1662388048.691344 [0 127.0.0.1:50579] "ZADD" "icinga:nextupdate:host" "1662388068.168299" "9b5bb23ddee640aeb6f2e71be4336655ae3bd036"
```

## Even more awesome

```
{"results":[{"code":200,"status":"Successfully rescheduled check for object '0'."}]}
```

```
1662388202.253110 [0 127.0.0.1:50579] "HSET" "icinga:host:state" "9b5bb23ddee640aeb6f2e71be4336655ae3bd036" "{\"check_attempt\":1,\"check_commandline\":\"'random'\",\"check_source\":\"alexandersmbp2.int.netways.de\",\"check_timeout\":60000,\"environment_id\":\"dd1de01a2760747f4e82bf7fec93477dcb13e09c\",\"execution_time\":1,\"hard_state\":1,\"host_id\":\"9b5bb23ddee640aeb6f2e71be4336655ae3bd036\",\"id\":\"9b5bb23ddee640aeb6f2e71be4336655ae3bd036\",\"in_downtime\":false,\"is_acknowledged\":0,\"is_active\":true,\"is_flapping\":false,\"is_handled\":false,\"is_problem\":true,\"is_reachable\":true,\"last_state_change\":1662388190821,\"last_update\":1662388200298,\"latency\":4,\"next_check\":2000000000000,\"next_update\":2000000010013,\"normalized_performance_data\":\"time=1662388200.298245 value=498 value_1m=448.200000 value_5m=398.400000 uptime=161.088683\",\"output\":\"Hello from alexandersmbp2.int.netways.de. Icinga 2 has been running for 2 minutes and 41 seconds. Version: v2.13.0-425-g60eb41ce9\",\"performance_data\":\"time=1662388200.298245 value=498 value_1m=448.200000 value_5m=398.400000 uptime=161.088683\",\"previous_hard_state\":0,\"previous_soft_state\":0,\"scheduling_source\":\"alexandersmbp2.int.netways.de\",\"severity\":2112,\"soft_state\":1,\"state_type\":1}"
1662388202.253286 [0 127.0.0.1:50579] "HSET" "icinga:checksum:host:state" "9b5bb23ddee640aeb6f2e71be4336655ae3bd036" "{\"checksum\":\"a9e5fe2332862ce9b5d077cc1b6100a443bffda1\"}"
1662388202.253410 [0 127.0.0.1:50579] "ZADD" "icinga:nextupdate:host" "2000000010.013584" "9b5bb23ddee640aeb6f2e71be4336655ae3bd036"
```

### CODE REVIEW

**Comment by julianbrost** [comment]
Looks like the IDO had the same issue in the past and the fix there was to introduce `Checkable::OnNextCheckUpdated` additional to `Checkable::OnNextCheckChanged`: b960850ce353aaf16a7f1da574b955817b8fd1bd

So just reusing that signal should also do the job for Icinga DB.

File: lib/icingadb/icingadb-objects.cpp [hunk 1]
```diff
@@ -126,7 +126,7 @@ void IcingaDB::ConfigStaticInitialize()
 		IcingaDB::NewCheckResultHandler(checkable);
 	});
 
-	Checkable::OnNextCheckChanged.connect([](const Checkable::Ptr& checkable, const Value&) {
+	Checkable::OnNextCheckUpdated.connect([](const Checkable::Ptr& checkable) {
 		IcingaDB::NextCheckChangedHandler(checkable);
```
Comment (julianbrost) [inline lib/icingadb/icingadb-objects.cpp:130]: Should rename `IcingaDB::NextCheckChangedHandler` as well to keep them consistent.

**Review by julianbrost — CHANGES_REQUESTED** [review]

**Review by julianbrost — APPROVED** [review]
