### PR TITLE
Fix flapping calculation and events

### LINKED ISSUE #5270: check_load.exe & check_network.exe on Windows 2008 SP 1 64bit
Hi,

I installed Icinga 2 agent on a Win 2008 host. It's the only host where check_load and check_network are failing. When I run these commands from command line, it looks like this:

```
PS C:\Program Files\ICINGA2\sbin> .\check_network.exe
Failed to format error message, last error was: 3221228472
PS C:\Program Files\ICINGA2\sbin> .\check_load.exe
The operation completed successfully.
```

I have other Windows clients (Windows 2012 Server) which do not fail.

icinga2-2.6.3-2-g9d26a9c 

Cheers,
  Marianne

screen shot 2017-05-17 at 12 20 37

### LINKED ISSUE #5720: Flapping tests and bugs
## Expected Behavior

No notifications are sent if flapping is disabled.

## Current Behavior

enable_flapping is false, but Icinga 2 sends Flapping Stop notifications.

This diff does not take into account if flapping detection is enabled.

```
        /* Flapping start/end notifications */
-       if (send_notification && !was_flapping && is_flapping) {
+       if (!in_downtime && !was_flapping && is_flapping) {
```

The origin of the changed behaviour is coming from 

```
+       UpdateFlappingStatus(old_state != cr->GetState());

-       if (GetStateType() == StateTypeHard)
-               UpdateFlappingStatus(stateChange);
```

where Flapping is updated every time. This would allow the above code change to work, but also here GetEnableFlapping() is missing.

Both code parts should explicitly check for GetEnableFlapping().

## Possible Solution

Disable flapping detection algorithm if explicitly disabled.

Furthermore, test if flapping start is properly sent. This doesn't look like this, I don't have any downtimes set.

## Steps to Reproduce (for bugs)

1. Run latest snapshot build
2. Add a service check which uses `random` as check command and low *_interval settings

```
# icinga2 object list --name 'graylog-host'
Object 'graylog-host' of type 'Host':
  % declared in '/etc/icinga2/demo/graylog2-demo.conf', lines 46:1-46:26
  * __name = "graylog-host"
  * action_url = ""
  * address = "127.0.0.1"
    % = modified in '/etc/icinga2/demo/graylog2-demo.conf', lines 47:3-47:23
  * address6 = ""
  * check_command = "hostalive"
    % = modified in '/etc/icinga2/demo/graylog2-demo.conf', lines 48:3-48:29
  * check_interval = 300
  * check_period = ""
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "graylog-host"
  * enable_active_checks = true
  * enable_event_handler = true
  * enable_flapping = false
  * enable_notifications = true
  * enable_passive_checks = true
  * enable_perfdata = true
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
  * name = "graylog-host"
  * notes = ""
  * notes_url = ""
  * package = "_etc"
  * retry_interval = 60
  * source_location
    * first_column = 1
    * first_line = 46
    * last_column = 26
    * last_line = 46
    * path = "/etc/icinga2/demo/graylog2-demo.conf"
  * templates = [ "graylog-host" ]
    % = modified in '/etc/icinga2/demo/graylog2-demo.conf', lines 46:1-46:26
  * type = "Host"
  * vars
    * notification_groups = [ "osmc" ]
      % = modified in '/etc/icinga2/demo/graylog2-demo.conf', lines 56:3-56:39
    * random = [ 1, 2, 3, 4, 5 ]
      % = modified in '/etc/icinga2/demo/graylog2-demo.conf', lines 54:3-54:32
    * streams
      * icinga2
        % = modified in '/etc/icinga2/demo/graylog2-demo.conf', lines 50:3-52:3
        * graylog2_stream_id = "54610d26e4b059482bbfab0f"
  * volatile = false
  * zone = ""
```

## Context

This floods anyone with notifications, especially to notice the web's history tab.

screen shot 2017-11-05 at 17 57 45

## Your Environment

* Version used (`icinga2 --version`): 
```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.7.1-306-g36fddaf)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.5.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```

* Enabled features (`icinga2 feature list`): 
```
Disabled features: command compatlog debuglog elastic graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker gelf ido-mysql mainlog notification
```

* Icinga Web 2 version and modules (System - About): v2.4.2, ee7fa2c48ca61f1d8d85c84f26e5b5abc5e8b22e

### PR DESCRIPTION
**Pull request by dnsmichi**
This PR also adds flapping_current, threshold_{high,low} to the API event streams.

fixes #5720

### CODE REVIEW

File: lib/icinga/checkable.hpp [hunk 1]
```diff
@@ -237,6 +236,9 @@ class I2_ICINGA_API Checkable : public ObjectImpl<Checkable>
 	std::set<intrusive_ptr<Dependency> > m_ReverseDependencies;
 
 	void GetAllChildrenInternal(std::set<Checkable::Ptr>& children, int level = 0) const;
+
+	/* Flapping */
```
Comment (gunnarbeutner) [inline lib/icinga/checkable.hpp]: Was this moved intentionally?

Comment (dnsmichi) [reply lib/icinga/checkable.hpp]: Yep. Flapping calculation should only be triggered by a check result update, but not called from anywhere else.
