### PR TITLE
Don't fail to remove obsolete downtimes

### LINKED ISSUE #10042: Scheduled Downtime won't be changed/deleted after reload
## Describe the bug
If I create a Scheduled Downtime in a global Zone via DSL, it is not possible to delete/change it afterwards

## To Reproduce
- Create a scheduled Downtime /etc/icinga2/zones.d/global-satellites/downtimes.conf:
```
	apply ScheduledDowntime "test123" to Host {
	  author = "Lasse"
	  comment = "test 123"

	  fixed = false
	  duration = 60m

	  ranges = {
	    "sunday 3" = "20:00-22:00"
	  }

	  assign where host.name == "msd-lwtest01"
	}
```
- Reload
- Check Downtime:
`icinga2 object list --type ScheduledDowntime --name 'msd-lwtest01!test123'`
- Change Downtime:
```
	apply ScheduledDowntime "test123" to Host {
	  author = "Lasse"
	  comment = "test 123"

	  fixed = false
	  duration = 60m

	  ranges = {
	    "sunday 1" = "20:00-22:00"
	  }

	  assign where host.vars.cloud_object_name == "vm-msd-lwtest01"
	}
```
- Reload
- Check Downtime:
`icinga2 object list --type ScheduledDowntime --name 'msd-lwtest01!test123'`

Result: The old Downtime will not be changed and is still active
In the Log you can find the following lines:
```
[2024-04-16 13:41:24 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:41:24 +0200] notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/37356bcb-7b59-441c-82fc-f384fae69a60/conf.d/downtimes/msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965.conf
[2024-04-16 13:41:24 +0200] information/ConfigObjectUtility: Created and activated object 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965' of type 'Downtime'.
[2024-04-16 13:41:24 +0200] information/Downtime: Added downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965' between '2024-04-21 20:00:00' and '2024-04-21 22:00:00', author: 'Lasse', flexible with 3600s duration
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!service-rsyslog' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!pending_mcms_updates' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!pending_updates' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!sentinelone-agent-status' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!disk' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!service-sssd' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!service-sentinelone' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!swap' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!interface-status' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!pending_updates_security-only' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!uptime' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!disk-io' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!service-chronyd' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!ntp-status' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!memory' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!about-me' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!dmesg' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!mountpoints-status' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!service-vmtoolsd' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!selinux-mode' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!cpu' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:56 +0200] notice/Downtime: Checkable 'msd-lwtest01!service-crond' already in a NOT-OK state. Triggering downtime now.
[2024-04-16 13:45:57 +0200] notice/ApiListener: Received config update for object: {"config":"object Downtime \"916b75be-2881-40f4-ab62-de302e93c965\" ignore_on_error {\n\tauthor = \"Lasse\"\n\tauthoritative_zone = \"master\"\n\tcomment = \"test 123\"\n\tconfig_owner = \"msd-lwtest01!test123\"\n\tconfig_owner_hash = \"7d7c18a918e1b2e7397f941b7080a5b0a8c1b65905d86d123838f21f69e1e7e3\"\n\tduration = 3600.000000\n\tend_time = 1713729600.000000\n\tentry_time = 1713267684.576673\n\tfixed = false\n\thost_name = \"msd-lwtest01\"\n\tparent = \"\"\n\tscheduled_by = \"msd-lwtest01!test123\"\n\tstart_time = 1713722400.000000\n\ttriggered_by = \"\"\n\tversion = 1713267684.576721\n\tzone = \"msd-private_vcloud\"\n}\n","modified_attributes":{},"name":"msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965","original_attributes":[],"type":"Downtime","version":1713267684.576721,"zone":"msd-private_vcloud"}
[2024-04-16 13:46:01 +0200] notice/ApiListener: Received config update for object: {"config":"object Downtime \"916b75be-2881-40f4-ab62-de302e93c965\" ignore_on_error {\n\tauthor = \"Lasse\"\n\tauthoritative_zone = \"master\"\n\tcomment = \"test 123\"\n\tconfig_owner = \"msd-lwtest01!test123\"\n\tconfig_owner_hash = \"7d7c18a918e1b2e7397f941b7080a5b0a8c1b65905d86d123838f21f69e1e7e3\"\n\tduration = 3600.000000\n\tend_time = 1713729600.000000\n\tentry_time = 1713267684.576673\n\tfixed = false\n\thost_name = \"msd-lwtest01\"\n\tparent = \"\"\n\tscheduled_by = \"msd-lwtest01!test123\"\n\tstart_time = 1713722400.000000\n\ttriggered_by = \"\"\n\tversion = 1713267684.576721\n\tzone = \"msd-private_vcloud\"\n}\n","modified_attributes":{},"name":"msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965","original_attributes":[],"type":"Downtime","version":1713267684.576721,"zone":"msd-private_vcloud"}
[2024-04-16 13:46:05 +0200] notice/ApiListener: Received config update for object: {"config":"object Downtime \"916b75be-2881-40f4-ab62-de302e93c965\" ignore_on_error {\n\tauthor = \"Lasse\"\n\tauthoritative_zone = \"master\"\n\tcomment = \"test 123\"\n\tconfig_owner = \"msd-lwtest01!test123\"\n\tconfig_owner_hash = \"7d7c18a918e1b2e7397f941b7080a5b0a8c1b65905d86d123838f21f69e1e7e3\"\n\tduration = 3600.000000\n\tend_time = 1713729600.000000\n\tentry_time = 1713267684.576673\n\tfixed = false\n\thost_name = \"msd-lwtest01\"\n\tparent = \"\"\n\tscheduled_by = \"msd-lwtest01!test123\"\n\tstart_time = 1713722400.000000\n\ttriggered_by = \"\"\n\tversion = 1713267684.576721\n\tzone = \"msd-private_vcloud\"\n}\n","modified_attributes":{},"name":"msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965","original_attributes":[],"type":"Downtime","version":1713267684.576721,"zone":"msd-private_vcloud"}
[2024-04-16 13:46:08 +0200] notice/ApiListener: Received config update for object: {"config":"object Downtime \"916b75be-2881-40f4-ab62-de302e93c965\" ignore_on_error {\n\tauthor = \"Lasse\"\n\tauthoritative_zone = \"master\"\n\tcomment = \"test 123\"\n\tconfig_owner = \"msd-lwtest01!test123\"\n\tconfig_owner_hash = \"7d7c18a918e1b2e7397f941b7080a5b0a8c1b65905d86d123838f21f69e1e7e3\"\n\tduration = 3600.000000\n\tend_time = 1713729600.000000\n\tentry_time = 1713267684.576673\n\tfixed = false\n\thost_name = \"msd-lwtest01\"\n\tparent = \"\"\n\tscheduled_by = \"msd-lwtest01!test123\"\n\tstart_time = 1713722400.000000\n\ttriggered_by = \"\"\n\tversion = 1713267684.576721\n\tzone = \"msd-private_vcloud\"\n}\n","modified_attributes":{},"name":"msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965","original_attributes":[],"type":"Downtime","version":1713267684.576721,"zone":"msd-private_vcloud"}
[2024-04-16 13:46:56 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:46:56 +0200] critical/ScheduledDowntime: Exception occurred during removal of obsolete downtime for scheduled downtime 'msd-lwtest01!test123': Error: Cannot remove downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965'. It is owned by scheduled downtime object 'msd-lwtest01!test123'
[2024-04-16 13:47:56 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:47:56 +0200] critical/ScheduledDowntime: Exception occurred during removal of obsolete downtime for scheduled downtime 'msd-lwtest01!test123': Error: Cannot remove downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965'. It is owned by scheduled downtime object 'msd-lwtest01!test123'
[2024-04-16 13:48:56 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:48:56 +0200] critical/ScheduledDowntime: Exception occurred during removal of obsolete downtime for scheduled downtime 'msd-lwtest01!test123': Error: Cannot remove downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965'. It is owned by scheduled downtime object 'msd-lwtest01!test123'
[2024-04-16 13:49:56 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:49:56 +0200] critical/ScheduledDowntime: Exception occurred during removal of obsolete downtime for scheduled downtime 'msd-lwtest01!test123': Error: Cannot remove downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965'. It is owned by scheduled downtime object 'msd-lwtest01!test123'
[2024-04-16 13:50:56 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:50:56 +0200] critical/ScheduledDowntime: Exception occurred during removal of obsolete downtime for scheduled downtime 'msd-lwtest01!test123': Error: Cannot remove downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965'. It is owned by scheduled downtime object 'msd-lwtest01!test123'
[2024-04-16 13:51:56 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:51:56 +0200] critical/ScheduledDowntime: Exception occurred during removal of obsolete downtime for scheduled downtime 'msd-lwtest01!test123': Error: Cannot remove downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965'. It is owned by scheduled downtime object 'msd-lwtest01!test123'
[2024-04-16 13:52:56 +0200] debug/ScheduledDowntime: Creating new Downtime for ScheduledDowntime "msd-lwtest01!test123"
[2024-04-16 13:52:56 +0200] critical/ScheduledDowntime: Exception occurred during removal of obsolete downtime for scheduled downtime 'msd-lwtest01!test123': Error: Cannot remove downtime 'msd-lwtest01!916b75be-2881-40f4-ab62-de302e93c965'. It is owned by scheduled downtime object 'msd-lwtest01!test123'
```

## Expected behavior
The Downtime should be updated or deleted. Furthermore, in the logfile is written, `'Checkable msd-lwtest01!cpu' already in a NOT-OK state. Triggering downtime now`, but the downtime should be started in the future and not at the reload time.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.14.1
* Operating System and version: RedHat 8.9
* Enabled features (`icinga2 feature list`): api checker debuglog icingadb influxdb2 mainlog notification syslog
* Icinga Web 2 version and modules (System - About): 2.12.1
* Config validation (`icinga2 daemon -C`): No Errors
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

### PR DESCRIPTION
**Pull request by yhabteab**
### Before

See #10042 

### After

- Deleting downtimes automatically due to owner config hash change.
```bash
[2024-05-15 16:52:17 +0200] information/ConfigObjectUtility: Deleted object 'downtime-test!39752e43-ffb6-40ee-8d17-c129a1b2f7c6' of type 'Downtime'.
[2024-05-15 16:52:17 +0200] information/Downtime: Removed downtime 'downtime-test!39752e43-ffb6-40ee-8d17-c129a1b2f7c6' from checkable 'downtime-test' (Reason: cancelled by 'downtime-test!backup-downtime').
```

- Deleting a downtime that belongs to a `ScheduledDowntime` object via the API
```bash
 curl -k -s -S -i -u root:icinga -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/remove-downtime' \
 -d '{ "downtime": "downtime-test!baa2338e-34b0-44a1-94fa-c24f9b1f2b0a", "pretty": true }'

–––
HTTP/1.1 400 Bad Request
Server: Icinga/v2.14.0-175-g81aec894c
Content-Type: application/json
Content-Length: 246

{
    "results": [
        {
            "code": 400,
            "status": "Cannot remove downtime 'downtime-test!baa2338e-34b0-44a1-94fa-c24f9b1f2b0a'. It is owned by scheduled downtime object 'downtime-test!backup-downtime'"
        }
    ]
}
```

fixes #10042

### CODE REVIEW

File: lib/icinga/scheduleddowntime.cpp [hunk 1]
```diff
@@ -323,7 +323,7 @@ void ScheduledDowntime::RemoveObsoleteDowntimes()
 			auto configOwnerHash (downtime->GetConfigOwnerHash());
 
 			if (!configOwnerHash.IsEmpty() && configOwnerHash != downtimeOptionsHash)
-				Downtime::RemoveDowntime(downtime->GetName(), false, true);
+				Downtime::RemoveDowntime(downtime->GetName(), false, true, true);
```
Comment (Al2Klimov) [inline lib/icinga/scheduleddowntime.cpp:326]: OK, I see. Due to the new usage here...

File: lib/icinga/downtime.cpp [hunk 2]
```diff
@@ -397,12 +397,12 @@ void Downtime::RemoveDowntime(const String& id, bool includeChildren, bool cance
 
 	String reason;
 
-	if (expired) {
+	if (downtime->IsExpired()) {
```
Comment (Al2Klimov) [inline lib/icinga/downtime.cpp:400]: ... that param doesn't necessarily indicate expiry anymore, so you have to differentiate actual expiry and GetConfigOwnerHash() mismatch in the logs. But then I'd just adjust the expiry condition as you did here and handle the GetConfigOwnerHash() mismatch in yet another else-if with a proper reason.

File: lib/icinga/downtime.cpp [hunk 3]
```diff
@@ -359,7 +359,7 @@ Downtime::Ptr Downtime::AddDowntime(const Checkable::Ptr& checkable, const Strin
 	return downtime;
 }
 
-void Downtime::RemoveDowntime(const String& id, bool includeChildren, bool cancelled, bool expired,
+void Downtime::RemoveDowntime(const String& id, bool includeChildren, bool cancelled, bool force,
```
Comment (Al2Klimov) [inline lib/icinga/downtime.cpp:362]: Or! I'd make another bool param not to calculate the hash twice. While on it, those 3 may be worth merging into one enum.

File: lib/icinga/downtime.hpp [hunk 4]
```diff
@@ -18,6 +18,14 @@ enum DowntimeChildOptions
 	DowntimeNonTriggeredChildren
 };
 
+enum DowntimeRemovalReason
+{
+	DowntimeExpired,
+	DowntimeRemovedByUser,
+	DowntimeRemovedByConfigOwner,
+	DowntimeRemovedForce
```
Comment (Al2Klimov) [inline lib/icinga/downtime.hpp:26]: This one shouldn't be necessary.

File: lib/icinga/downtime.cpp [hunk 5]
```diff
@@ -557,7 +565,7 @@ void Downtime::DowntimesOrphanedTimerHandler()
 	for (const Downtime::Ptr& downtime : ConfigType::GetObjectsByType<Downtime>()) {
 		/* Only remove downtimes which are activated after daemon start. */
 		if (downtime->IsActive() && !downtime->HasValidConfigOwner())
-			RemoveDowntime(downtime->GetName(), false, false, true);
+			RemoveDowntime(downtime->GetName(), false, DowntimeRemovedForce);
```
Comment (Al2Klimov) [inline lib/icinga/downtime.cpp:568]: Here the config owner is the reason.

File: lib/icinga/checkable-downtime.cpp [hunk 6]
```diff
@@ -12,7 +12,7 @@ using namespace icinga;
 void Checkable::RemoveAllDowntimes()
 {
 	for (const Downtime::Ptr& downtime : GetDowntimes()) {
-		Downtime::RemoveDowntime(downtime->GetName(), true, true, true);
+		Downtime::RemoveDowntime(downtime->GetName(), true, DowntimeRemovedForce);
```
Comment (Al2Klimov) [inline lib/icinga/checkable-downtime.cpp:15]: * And here I'd just #10066

File: lib/icinga/downtime.cpp (hunk 5 above)
Comment (yhabteab) [reply lib/icinga/downtime.cpp:568]: That's not the only reason here!
https://github.com/Icinga/icinga2/blob/252b075d0f71013d37dd088fb17b58999ca3ef78/lib/icinga/downtime.cpp#L237-L242

File: lib/icinga/downtime.cpp [hunk 7]
```diff
@@ -369,19 +369,19 @@ void Downtime::RemoveDowntime(const String& id, bool includeChildren, bool cance
 
 	String config_owner = downtime->GetConfigOwner();
 
-	if (!config_owner.IsEmpty() && !expired) {
+	if (!config_owner.IsEmpty() && removalReason != DowntimeExpired && removalReason != DowntimeRemovedByConfigOwner) {
```
Comment (Al2Klimov) [inline lib/icinga/downtime.cpp:372]: Now as you have only 3 enum values, you can just change != to == in f9ae1d58cbab7fd2432a90643c73a0368f7b8495. I.e.:

```suggestion
	if (!config_owner.IsEmpty() && removalReason == DowntimeRemovedByUser) {
```

**Review by Al2Klimov — APPROVED** [review]

**Comment by Al2Klimov** [comment]
And why exactly?

**Comment by yhabteab** [comment]
> And why exactly?

Because the object deletion event for these child downtimes is initially triggered on the current endpoint, and their deletion event should also be synchronised to the sender of the deletion event of the parent downtime.

File: lib/icinga/downtime.cpp [hunk 8]
```diff
@@ -369,19 +369,19 @@ void Downtime::RemoveDowntime(const String& id, bool includeChildren, bool cance
...
 		for (const Downtime::Ptr& child : downtime->GetChildren()) {
-			Downtime::RemoveDowntime(child->GetName(), true, true);
+			Downtime::RemoveDowntime(child->GetName(), true, removalReason, removedBy);
 		}
 	}
 
-	if (cancelled) {
-		downtime->SetRemovalInfo(removedBy, Utility::GetTime());
+	if (removalReason != DowntimeExpired) {
+		downtime->SetRemovalInfo(removedBy, Utility::GetTime(), origin);
```
Comment (Al2Klimov) [inline lib/icinga/downtime.cpp:384]: Why don't we omit ALL the origin passthrough additions for now and discuss them separately?

Comment (yhabteab) [reply lib/icinga/downtime.cpp:384]: No problem! `Downtime::RemoveDowntime()` is never called from outside with the `origin` param set anyway, so I am wondering why it was introduced in the first place.

**Review by Al2Klimov — APPROVED** [review]
