### PR TITLE
Icinga DB: only start multiple Redis connections after the first one succeeded

### LINKED ISSUE #8920: Icinga DB: only start multiple Redis connections after the first one succeeded
When you have configured broken connection details in an `IcingaDB` object, multiple connections are started at once and they will all log that they failed to connect. There already was #8883 which was fixed by #8894, but this only affects success messages.

This could be improved by only spawning secondary connections, after the first one succeeded. This would only help with connections that are broken from the very beginning, not if Redis dies while Icinga is running.

So another option would be to reuse the `m_Parent` relation between Redis connections that's already there for logging and stats collection and only actually attempt to establish a new connection in the child if the parent is in a good state. The trivial implementation (`if (m_Parent && !m_Parent.IsGood()) { return; /* skip connection attempt */ }`) would introduce a delay by having to wait for the next timer, so a notification mechanism from parent to child after a successful connection would be nice.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #8920

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Blocked by

* #8544

**Comment by Al2Klimov** [comment]
## Before

```
➜  icinga2 git:(feature/icingadb-tls) prefix/sbin/icinga2 daemon
[2021-07-26 14:21:38 +0200] information/cli: Icinga application loader (version: v2.12.0-778-gd1561fb37)
[2021-07-26 14:21:38 +0200] information/cli: Loading configuration file(s).
[2021-07-26 14:21:38 +0200] information/ConfigItem: Committing config item(s).
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 244 CheckCommands.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 Host.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 3 Zones.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 11 Services.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 User.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-07-26 14:21:38 +0200] information/ConfigItem: Instantiated 1 IcingaDB.
[2021-07-26 14:21:38 +0200] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2021-07-26 14:21:38 +0200] information/ConfigItem: Triggering Start signal for config items
[2021-07-26 14:21:38 +0200] information/FileLogger: 'main-log' started.
[2021-07-26 14:21:39 +0200] information/IcingaDB: 'icingadb' started.
[2021-07-26 14:21:39 +0200] information/NotificationComponent: 'notification' started.
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] information/IcingaDB: Trying to connect to Redis server (async) on host '127.0.0.1:6380'
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] information/CheckerComponent: 'checker' started.
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:39 +0200] information/ConfigItem: Activated all objects.
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] information/IcingaDB: Trying to connect to Redis server (async) on host '127.0.0.1:6380'
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:21:44 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
^C[2021-07-26 14:21:46 +0200] information/Application: Received request to shut down.
[2021-07-26 14:21:46 +0200] information/Application: Shutting down...
[2021-07-26 14:21:46 +0200] information/CheckerComponent: 'checker' stopped.
[2021-07-26 14:21:46 +0200] information/NotificationComponent: 'notification' stopped.
[2021-07-26 14:21:46 +0200] information/IcingaDB: 'icingadb' stopped.
[2021-07-26 14:21:46 +0200] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-07-26 14:21:46 +0200] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(feature/icingadb-tls)
```

## After

```
➜  icinga2 git:(bugfix/icinga-db-only-start-multiple-redis-connections-after-the-first-one-succeeded-8920) prefix/sbin/icinga2 daemon
[2021-07-26 14:24:15 +0200] information/cli: Icinga application loader (version: v2.12.0-779-g35edc6abe)
[2021-07-26 14:24:15 +0200] information/cli: Loading configuration file(s).
[2021-07-26 14:24:15 +0200] information/ConfigItem: Committing config item(s).
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 244 CheckCommands.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 Host.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 3 Zones.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 11 Services.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 User.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Instantiated 1 IcingaDB.
[2021-07-26 14:24:15 +0200] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2021-07-26 14:24:15 +0200] information/ConfigObject: Restoring program state from file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-07-26 14:24:15 +0200] information/ConfigObject: Restored 291 objects. Loaded 0 new objects without state.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Triggering Start signal for config items
[2021-07-26 14:24:15 +0200] information/FileLogger: 'main-log' started.
[2021-07-26 14:24:15 +0200] information/IcingaDB: 'icingadb' started.
[2021-07-26 14:24:15 +0200] information/NotificationComponent: 'notification' started.
[2021-07-26 14:24:15 +0200] information/IcingaDB: Trying to connect to Redis server (async) on host '127.0.0.1:6380'
[2021-07-26 14:24:15 +0200] information/CheckerComponent: 'checker' started.
[2021-07-26 14:24:15 +0200] information/ConfigItem: Activated all objects.
[2021-07-26 14:24:15 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:24:15 +0200] information/Checkable: Checkable 'Alexanders-MacBook-Pro.local' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2021-07-26 14:24:15 +0200] information/Notification: Sending 'Problem' notification 'Alexanders-MacBook-Pro.local!mail-icingaadmin' for user 'icingaadmin'
[2021-07-26 14:24:15 +0200] information/Notification: Completed sending 'Problem' notification 'Alexanders-MacBook-Pro.local!mail-icingaadmin' for checkable 'Alexanders-MacBook-Pro.local' and user 'icingaadmin' using command 'mail-host-notification'.
[2021-07-26 14:24:20 +0200] information/IcingaDB: Trying to connect to Redis server (async) on host '127.0.0.1:6380'
[2021-07-26 14:24:20 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:24:25 +0200] information/IcingaDB: Trying to connect to Redis server (async) on host '127.0.0.1:6380'
[2021-07-26 14:24:25 +0200] critical/IcingaDB: Cannot connect to 127.0.0.1:6380: Connection refused
[2021-07-26 14:24:30 +0200] information/IcingaDB: Trying to connect to Redis server (async) on host '127.0.0.1:6380'
[2021-07-26 14:24:30 +0200] information/IcingaDB: Connected to Redis server
[2021-07-26 14:24:30 +0200] information/IcingaDB: Starting initial config/status dump
[2021-07-26 14:24:30 +0200] information/IcingaDB: Initial config/status dump finished in 0.199788 seconds.
^C[2021-07-26 14:24:33 +0200] information/Application: Received request to shut down.
[2021-07-26 14:24:33 +0200] information/Application: Shutting down...
[2021-07-26 14:24:33 +0200] information/CheckerComponent: 'checker' stopped.
[2021-07-26 14:24:33 +0200] information/NotificationComponent: 'notification' stopped.
[2021-07-26 14:24:33 +0200] information/IcingaDB: 'icingadb' stopped.
[2021-07-26 14:24:33 +0200] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-07-26 14:24:33 +0200] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(bugfix/icinga-db-only-start-multiple-redis-connections-after-the-first-one-succeeded-8920)
```

**Review by julianbrost — CHANGES_REQUESTED** [review]
Totally not what I had in mind when writing the issue (I'd probably have done it within `RedisConnection`), but should do the trick.

File: lib/icingadb/icingadb.cpp [hunk 1]
```diff
@@ -67,21 +67,29 @@ void IcingaDB::Start(bool runtimeCreated)
...
+	auto connectedCallback ([this](boost::asio::yield_context& yc) {
 		m_WorkQueue.Enqueue([this]() { OnConnectedHandler(); });
 	});
+
+	m_Rcon->SetConnectedCallback([this, connectedCallback](boost::asio::yield_context& yc) {
+		for (auto& kv : m_Rcons) {
+			kv.second->Start();
+		}
+
+		m_Rcon->SetConnectedCallback(connectedCallback);
```
Comment (julianbrost) [inline lib/icingadb/icingadb.cpp:80]: Why is this needed? Only the first call to `OnConnectedHandler()` should do anything anyways (there's a check in there and on any subsequent call, it should just return).

Comment (Al2Klimov) [reply lib/icingadb/icingadb.cpp:80]: It’s named `OnConnectedHandler`. A programmer who works on all this expects it being called on every connect. This PR's goal isn’t to make the code as complicated as possible, but to only change _that one thing_.

Comment (julianbrost) [reply lib/icingadb/icingadb.cpp:80]: I don't understand the claim that this PR is supposed to change only one thing. Before, `OnConnectHandler` was only called for the parent connection, so isn't this changing another thing?

By the way, the name `OnConnectedHandler` was chosen when there was only a single connection. So I think it would also be fine to just rename it to better reflect the current purpose instead of complicating the code for the sake of its name. But isn't this really another construction area?

Comment (Al2Klimov) [reply lib/icingadb/icingadb.cpp:80]: Before, all Redis connections were started at the same time. After, they’re started by the m_ConnectedCallback, but only the first m_ConnectedCallback() time. So yes, only one thing.

Comment (julianbrost) [reply lib/icingadb/icingadb.cpp:80]: Upon closer inspection: Once `OnConnectedHandler()` is called, Icinga starts with the initial dump using *all* connections, including the child connections that are started at the very same time. Is there anything that ensures that queries issued to the child connections won't get lost because they're not yet ready? Or would the correct behavior actually be to only call `OnConnectedHandler()` after all connections are ready?

Comment (Al2Klimov) [reply lib/icingadb/icingadb.cpp:80]: They won’t get lost. They’ll get queued.

Comment (julianbrost) [reply lib/icingadb/icingadb.cpp:80]: Well, yes, there's a queue. But looks like there's nothing that prevents the execution of these jobs before the connection is ready. This also explains the mysterious errors I asked about in our internal chat a few days ago.

Using this patch:
```diff
diff --git a/lib/icingadb/redisconnection.hpp b/lib/icingadb/redisconnection.hpp
index fff9a0036..aed339afa 100644
--- a/lib/icingadb/redisconnection.hpp
+++ b/lib/icingadb/redisconnection.hpp
@@ -13,6 +13,7 @@
 #include "base/string.hpp"
 #include "base/tlsstream.hpp"
 #include "base/value.hpp"
+#include "base/logger.hpp"
 #include <boost/asio/buffer.hpp>
 #include <boost/asio/buffered_stream.hpp>
 #include <boost/asio/deadline_timer.hpp>
@@ -257,7 +258,7 @@ private:
 class RedisDisconnected : public std::runtime_error
 {
 public:
-       inline RedisDisconnected() : runtime_error("")
+       inline RedisDisconnected() : runtime_error("redis disconnected")
        {
        }
 };
@@ -270,7 +271,7 @@ public:
 class RedisProtocolError : public std::runtime_error
 {
 protected:
-       inline RedisProtocolError() : runtime_error("")
+       inline RedisProtocolError() : runtime_error("redis protocol error")
        {
        }
 };
@@ -368,6 +369,7 @@ void RedisConnection::WriteOne(StreamPtr& stream, RedisConnection::Query& query,
        namespace asio = boost::asio;
 
        if (!stream) {
+               Log(LogWarning, "IcingaDB") << "Lost Query: " << query[0];
                throw RedisDisconnected();
        }
 
```

I receive this:
```
[2021-07-27 17:01:42 +0200] information/IcingaDB: Starting initial config/status dump
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:notificationcommand:customvar' 'icinga:notificationcommand:envvar' 'icinga:checksum:notificationcommand:envvar' 'icinga:notificationcommand:argument' 'icinga:checksum:notificationcommand:argument' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:eventcommand:customvar' 'icinga:eventcommand:envvar' 'icinga:checksum:eventcommand:envvar' 'icinga:eventcommand:argument' 'icinga:checksum:eventcommand:argument' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:servicegroup:customvar' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:zone:customvar' 'icinga:zone:parent' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:user:customvar' 'icinga:usergroup:member' 'icinga:user:state' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: MULTI
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'MULTI' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:usergroup:customvar' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:timeperiod:customvar' 'icinga:timeperiod:override:include' 'icinga:timeperiod:override:exclude' 'icinga:timeperiod:range' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: MULTI
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'MULTI' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:host:customvar' 'icinga:hostgroup:member' 'icinga:host:state' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: DEL
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Error during sending query 'DEL' 'icinga:endpoint:customvar' which has been fired and forgotten: redis disconnected
[2021-07-27 17:01:42 +0200] warning/IcingaDB: Lost Query: HSCAN
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] critical/IcingaDB: Exception during ConfigDump: redis disconnected
[2021-07-27 17:01:42 +0200] information/IcingaDB: Initial config/status dump finished in 0.205472 seconds.
```

Comment (Al2Klimov) [reply lib/icingadb/icingadb.cpp:80]: Other construction area. To be precise: #8939

**Review by julianbrost — APPROVED** [review]
To be honest, adding that callback logic here just to remove it again in #8939 is kind of pointless, but fine, at least we don't have to touch this PR again then.
