### PR TITLE
CheckerComponent#Stop(): don't wait for checks

### LINKED ISSUE #7888: Don't wait for checks on reload
## Describe the bug

Our reload is being slowed down by the running checks.

## To Reproduce

https://github.com/Icinga/icinga2/blob/cef4c46ba8399cf2cf944271c7da21c5a66f3868/lib/checker/checkercomponent.cpp#L79

## Expected behavior

Let's don't wait for them.

## Additional context

We (1) update next_check and (2) start the process. If we (3) just reload, we lose the check result. To avoid this, we could add a new internal attribute last_check_started and set it to now just before updating next_check. In the new main process on `Checkable#Start()` if we discover that last_check_started > last check result, we set next_check to last_check_started.

@N-o-X What's your opinion?

### LINKED ISSUE #8021: 2.12 RC31...11 stuck on reload Ubuntu 18.04
## Describe the bug
I know these are snapshots, but we have been testing due to zone bug reported in #7981 for 2.11.3 Satellites

2.12 RC7 fixed zone issue from #7981 

Semi-Live Landscape - 
3 Tier Landscape 
Level 1 (Master with 2 nodes)  2.11.3 / 2.12 RCx
Level 2 (Satellite with 2 nodes) 2.12 RCx / 2.12 RCx
Level 3 (Satellite with 1 node) 2.12 RCx

Tracking snapshots we noted this behavior with RC11, RC13, RC19:
1) Restart no problem and loads configs from Level 1 Master/Level 2 Satellite
2) Next (1st) Reload loads config from Level 1 Master/ Level 2 Satellite
3) Next (2nd) Reload process starts, but never completes on Satellite (Level 1 node 2, Level 2 Satellites)

Current time UTC 00:55
Note pid 5925 is new proc, and it has been in reload for 45 minutes.  
and though icinga2 says it killed it @ 00:35 still running (**30 minutes**).

Every 2.0s: ps -ef|grep sbin/icinga2|grep -v grep;echo "\n\n";service icinga2 status                                                                                                        level2sat01: Wed May 20 00:55:30 2020

**nagios    5925 15031  0 00:05 ?        00:00:06 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log**
nagios   15031     1  0 May19 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
nagios   21482 15031  2 May19 ?        00:01:38 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
nagios   21684 21482  0 May19 ?        00:00:01 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log

● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/icinga2.service.d
           └─limits.conf
   Active: reloading (reload) since Tue 2020-05-19 23:22:43 UTC; 1h 31min ago
 Main PID: 15031 (icinga2)
    Tasks: 38
   CGroup: /system.slice/icinga2.service
           ├─ 5925 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           ├─15031 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           ├─21482 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log
           └─21684 /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 --no-stack-rlimit daemon --close-stdio -e /var/log/icinga2/error.log

May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 5 Endpoints.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 361 Users.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 318 CheckCommands.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ConfigItem: Instantiated 108 Services.
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
May 19 23:22:43 level2sat01 icinga2[15031]: [2020-05-19 23:22:43 +0000] information/cli: Closing console log.
May 19 23:22:43 level2sat01 systemd[1]: Started Icinga host/service/network monitoring system.
**May 20 00:35:43 level2sat01 systemd[1]: icinga2.service: Reload operation timed out. Killing reload process.**

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): v2.12.0-rc1-19-gf71be9e80
* Operating System and version: aws #18~18.04.1Ubuntu
* Enabled features (`icinga2 feature list`):  api checker ido-mysql mainlog notification
* Icinga Web 2 version and modules (System - About):
company	1.0.0
cube	1.1.0
downtimecommander	0.0.1
enforceddashboard	0.0.0
ipl	v0.3.0
monitoring	2.8.0+rc1
pdfexport	0.9.1
pnp	1.1.0
reactbundle	0.7.0
reporting	0.10.0
setup	2.8.0+rc1

* Config validation (`icinga2 daemon -C`):
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 6 NotificationCommands.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 260 Notifications.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 7647 HostGroups.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 84 Hosts.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 5 Zones.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 5 Endpoints.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 361 Users.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 318 CheckCommands.
[2020-05-20 01:05:18 +0000] information/ConfigItem: Instantiated 108 Services.
[2020-05-20 01:05:18 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-05-20 01:05:18 +0000] information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Wed May 20 01:06:22$ icinga2 object list --type Endpoint
Object 'level1master02' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 10:1-10:40
  * __name = "level1master02"
  * host = "100.92.13.228"
    % = modified in '/etc/icinga2/zones.conf', lines 11:9-11:30
  * log_duration = 86400
  * name = "level1master02"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 12:9-12:21
  * source_location
    * first_column = 1
    * first_line = 10
    * last_column = 40
    * last_line = 10
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level1master02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 10:1-10:40
  * type = "Endpoint"
  * zone = ""

Object 'level3sat01' of type 'Endpoint':
  % declared in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 1:0-1:40
  * __name = "level3sat01"
  * host = "10.7.1.210"
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 2:5-2:23
  * log_duration = 86400
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 4:5-4:21
  * name = "level3sat01"
  * package = "_cluster"
  * port = "5665"
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 3:5-3:17
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 40
    * last_line = 1
    * path = "/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf"
  * templates = [ "level3sat01" ]
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/endpoints.conf', lines 1:0-1:40
  * type = "Endpoint"
  * zone = "level2_zone"

Object 'level2sat01' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 19:1-19:40
  * __name = "level2sat01"
  * host = ""
  * log_duration = 86400
  * name = "level2sat01"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 19
    * last_column = 40
    * last_line = 19
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level2sat01" ]
    % = modified in '/etc/icinga2/zones.conf', lines 19:1-19:40
  * type = "Endpoint"
  * zone = ""

Object 'level1master01' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 6:1-6:40
  * __name = "level1master01"
  * host = "100.92.12.49"
    % = modified in '/etc/icinga2/zones.conf', lines 7:9-7:29
  * log_duration = 86400
  * name = "level1master01"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 8:9-8:21
  * source_location
    * first_column = 1
    * first_line = 6
    * last_column = 40
    * last_line = 6
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level1master01" ]
    % = modified in '/etc/icinga2/zones.conf', lines 6:1-6:40
  * type = "Endpoint"
  * zone = ""

Object 'level2sat02' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 22:1-22:40
  * __name = "level2sat02"
  * host = "100.92.13.111"
    % = modified in '/etc/icinga2/zones.conf', lines 23:9-23:30
  * log_duration = 86400
  * name = "level2sat02"
  * package = "_etc"
  * port = "5665"
    % = modified in '/etc/icinga2/zones.conf', lines 24:9-24:21
  * source_location
    * first_column = 1
    * first_line = 22
    * last_column = 40
    * last_line = 22
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level2sat02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 22:1-22:40
  * type = "Endpoint"
  * zone = ""

root@level2sat01:/etc/icinga2
Wed May 20 01:06:34$ icinga2 object list --type Zone
Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 32:1-32:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 33:2-33:14
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 32
    * last_column = 30
    * last_line = 32
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 32:1-32:30
  * type = "Zone"
  * zone = ""

Object 'level2_zone' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 27:1-27:24
  * __name = "level2_zone"
  * endpoints = [ "level2sat01", "level2sat02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 28:2-28:67
  * global = false
  * name = "level2_zone"
  * package = "_etc"
  * parent = "global"
    % = modified in '/etc/icinga2/zones.conf', lines 29:2-29:18
  * source_location
    * first_column = 1
    * first_line = 27
    * last_column = 24
    * last_line = 27
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "level2_zone" ]
    % = modified in '/etc/icinga2/zones.conf', lines 27:1-27:24
  * type = "Zone"
  * zone = ""

Object 'level3_zone' of type 'Zone':
  % declared in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 1:0-1:21
  * __name = "level3_zone"
  * endpoints = [ "level3sat01" ]
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 3:5-3:45
  * global = false
  * name = "level3_zone"
  * package = "_cluster"
  * parent = "level2_zone"
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 2:5-2:25
  * source_location
    * first_column = 0
    * first_line = 1
    * last_column = 21
    * last_line = 1
    * path = "/var/lib/icinga2/api/zones/level2_zone/director/zones.conf"
  * templates = [ "level3_zone" ]
    % = modified in '/var/lib/icinga2/api/zones/level2_zone/director/zones.conf', lines 1:0-1:21
  * type = "Zone"
  * zone = "level2_zone"

Object 'global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 14:1-14:20
  * __name = "global"
  * endpoints = [ "level1master01", "level1master02" ]
    % = modified in '/etc/icinga2/zones.conf', lines 15:9-15:74
  * global = false
  * name = "global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 14
    * last_column = 20
    * last_line = 14
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 14:1-14:20
  * type = "Zone"
  * zone = ""

Object 'director-global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 36:1-36:29
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 37:2-37:14
  * name = "director-global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 36
    * last_column = 29
    * last_line = 36
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 36:1-36:29
  * type = "Zone"
  * zone = ""

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #7888
fixes #8021

### CODE REVIEW

File: lib/icinga/clusterevents.cpp [hunk 1]
```diff
@@ -24,6 +24,7 @@ INITIALIZE_ONCE(&ClusterEvents::StaticInitialize);
 
 REGISTER_APIFUNCTION(CheckResult, event, &ClusterEvents::CheckResultAPIHandler);
 REGISTER_APIFUNCTION(SetNextCheck, event, &ClusterEvents::NextCheckChangedAPIHandler);
+REGISTER_APIFUNCTION(SetLastCheckStarted, event, &ClusterEvents::LastCheckStartedChangedAPIHandler);
```
Comment (N-o-X) [inline lib/icinga/clusterevents.cpp:27]: Please add documentation about this in [19-technical-concepts.md#json-rpc-message-api](https://icinga.com/docs/icinga2/latest/doc/19-technical-concepts/#json-rpc-message-api)
